### ISSUE TITLE
On deploy, should warn when code contains a setwd() statement

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rsconnect#100]
For apps going to shinyapps.io, at least, there is no need for a setwd() statement since the app is expected to be isolated and self-contained.  rsconnect allows you to deploy code that contains a setwd() call, but the app then fails on shinyapps.io during runtime.  At deploy-time, a warning about setwd() statements would be appreciated.

**Comment by kevinushey** [comment]
Normally, absolute paths should be warned about regardless by the linter; similarly with paths that resolve outside of the project directory. Do we have a reproducible example for this one?

**Comment by ajmcoqui** [comment]
The tickets I have all involve absolute paths, but it is my understanding that using setwd() is discouraged in apps being deployed to shinyapps.io, so it may make sense to issue a warning when one is detected, regardless of the path in use.

**Comment by kevinushey** [comment]
Got it -- I just want to make sure we're not stomping on potentially legitimate uses of `setwd()`; e.g. it seems like someone could feasibly write code like this and it should work (assuming an application deployed with a `data` directory + a `data.csv` file):

```R
# move to data directory
setwd("data")

# read data file
data <- read.csv("data.csv")

# move back to parent directory
setwd("..")
```

**Comment by ajmcoqui** [comment]
Fair enough.  I was suggesting a warning rather than an error for just that reason (that there are valid, if unlikely, cases).

**Comment by hadley** [comment]
I think catching absolute paths is likely to be adequate here.

**Comment by simon-smart88** [comment]
@hadley Was this meant to be marked as completed because I can't see any changes associated with it and it still causes problems? Came here because this is one of the most common problems when newbies ask on SO why their app doesn't work when it's deployed.

**Comment by hadley** [comment]
Yes, and generally I don't think error checking user code is in code for rsconnect (although it would be useful to do elsewhere).
