### ISSUE TITLE
use "fake" packages for test dependencies

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#1011]
We should follow the example of renv and create a fake on-disk repository that contains the packages that are required by test content.

This would include at least:
* shiny
* plumber
* rmarkdown

For example, renv uses these packages:
https://github.com/rstudio/renv/tree/main/tests/testthat/packages

This is wired in with:
https://github.com/rstudio/renv/blob/63f3073aa60937498bc7d3f8a5a242bded237d4b/tests/testthat/helper-scope.R#L2-L59

The on-disk repository is created during setup:
https://github.com/rstudio/renv/blob/63f3073aa60937498bc7d3f8a5a242bded237d4b/tests/testthat/helper-setup.R#L151-L231

We can undo the changes from https://github.com/rstudio/rsconnect/pull/1010 with this change.

**Comment by hadley** [comment]
Or, and bear with me here, we don't do that, because it's probably harmless to skip these tests on CRAN, and creating a fake repo might be quite a bit of work? 😄

**Comment by aronatkins** [comment]
I'm feeling the same (skip on CRAN). I created this issue while chatting with @kevinushey to enumerate other options to #1010. Closing; we can revisit if we uncover other reasons to use this type of isolation.
