### ISSUE TITLE
quarto: provide feedback when inspect fails

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#1032]
Given the Quarto document:

````markdown
---
format: unsupported
---

This is a Quarto document that attempts to use an unrecognized format.
````

Running `quarto inspect` produces an error.

```bash
quarto inspect index.qmd
# => ERROR: Unknown format unsupported
```

However, when `rsconnect::writeManifest()` or `rsconnect:deployApp()` acts upon this file, there is no complaint.

```r
rsconnect::writeManifest()
```

The manifest declares that it should be `quarto-static` but is created without a `quarto` block. Additionally, a set of R packages is inferred, as if it needs knitr/rmarkdown.

When `rsconnect::deployApp()` publishes to Posit Connect, the lack of a Quarto block produces an error:

```
── Deployment complete ───
✖ Deployment failed with error: Unsupported App Mode.
```

This type of error can happen when the document uses a new type of format but the Quarto installation does not support that format.

**Comment by ChaitaC** [comment]
Verified on rsconnect dev build 
```
RemoteUsername: rstudio
RemoteRef: HEAD
RemoteSha: 2e59f9d56651189487e195a8140baebe580d3476
GithubRepo: rsconnect
GithubUsername: rstudio
```

Accurate feedback is provided when inspect fails 
```
✔ Re-deploying "quarto1234-1" using "server: rsc.radixu.com / username: ChaitaTest"
Error in `quartoInspect()`:
! Failed to run `quarto inspect` against your content:
ERROR: Unknown format unsupported
```
