### ISSUE TITLE
rsconnect::setProperty() does not work

### ISSUE THREAD

**Issue by AlejandroAyllon** [rstudio/rsconnect#1033]
Hi,

I tried to use `rsconnect::setProperty()` to change the parameters of my shiny apps and it seems does not work. The following examples don't return an error but the changes have not been applied. 

```
rsconnect::setProperty(propertyName = "application.shiny.scheduler.max.processes", propertyValue = 1, appName = "appName, force = TRUE)
rsconnect::setProperty(propertyName = "application.connect.scheduler.max.processes", propertyValue = 1, appName = "appName", force = TRUE)
```

I have tested with some properties but none of them work.

Thanks in advance.

**Comment by ssinnott** [comment]
The new value should be set after making the call but updated properties don not take effect until after the application redeploys. This can be done through the `deployApp` command in `rsconnect`.

https://rstudio.github.io/rsconnect/reference/deployApp.html

These values are also tunable through the shinyapps.io UI which handles the update after all the settings are changed.
