### ISSUE TITLE
App deployment via RStudio: Can't re-install packages from source.

### ISSUE THREAD

**Issue by Chrizsly** [rstudio/rsconnect#1047]
Hi, 

trying to deploy a simple shiny app from r studio. back-end code requires rClr, which is not available from CRAN. I get the following error message when trying to deploy: 

`Error in `createAppManifest()` at rsconnect/R/deployApp.R:645:3:
! All packages must be installed from a reproducible location.
✖ Can't re-install packages installed from source: rClr.`

Seems like a re-curring issue, but unable to find a quick solution. Thanks for the help!

**Comment by simon-smart88** [comment]
A bit late perhaps, buy you just need to install from github with `devtools::install_github("rdotnet/rClr")` and then `{renv}` will record that and install from the same location when it's deployed

**Comment by aronatkins** [comment]
Thanks for the assist, @simon-smart88. Closing this issue with that advice. Please re-open if you are still unable to deploy your application.
