### ISSUE TITLE
manifest.json is missing generated index.htm from files property

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#106]
The `index.htm` file is created by writeRmdIndex:
https://github.com/rstudio/rsconnect/blob/0a350894eaf4c7addb9424cad03a4f0348132461/R/rmdindex.R#L4

which is called from `bundleApp`:
https://github.com/rstudio/rsconnect/blob/aac8077b3d9d0d056d75e42093e70ad1d757ac38/R/bundle.R#L67

Unfortunately, this is after we create the `manifest.json`:
https://github.com/rstudio/rsconnect/blob/aac8077b3d9d0d056d75e42093e70ad1d757ac38/R/bundle.R#L59-L64

As a result, the `index.htm` file is not included in `manifest.files` and therefore never makes it into the Docker container used by shinyapps.io when running the application.

**Comment by aronatkins** [comment]
@jmcphers This feels like we just need to run 
```
  indexFiles <- writeRmdIndex(appName, bundleDir)
  on.exit(unlink(indexFiles), add = TRUE)
```
before the call to `createAppManifest`. Does that sound right?

**Comment by hadley** [comment]
Still looks like this is a problem.

**Comment by aronatkins** [comment]
We are internally discussing removing support for the embedded `index.htm` file.

**Comment by aronatkins** [comment]
Filed https://github.com/rstudio/rmarkdown/issues/2459 to track the fact that `rmarkdown::run` cannot cope with multiple Markdown files when none are Shiny.
