### ISSUE TITLE
Detect packages in `shinylive-r` sections and identify `filter: shinylive` in quarto docs

### ISSUE THREAD

**Issue by colearendt** [rstudio/rsconnect#1066]
I noticed in some published examples that `rsconnect` was not identifying to install the `shinylive` package when using `shinylive-r` code chunks (even if `library("shinylive")` is in that code chunk) in a Quarto document.

So some options:
- identify that `shinylive-r` means "install `shinylive`"
- identify that `filter: shinylive` means "install `shinylive`"
- not sure if packages have to be installed or if `library()` calls inside of `shinylive-r` chunks should be read

Example:

```
```{shinylive-r}
#| standalone: true
#| viewerHeight: 400
library(shiny)
library(bslib)
library(bsicons)
library(dplyr)
library(vetiver)
library(shinylive)
tidymodels::tidymodels_prefer(quiet = TRUE)
```

**Comment by aronatkins** [comment]
@colearendt - This is an renv issue; rsconnect relies on `renv::dependencies()` to capture package requirements.

CC @kevinushey

**Comment by aronatkins** [comment]
> Should I port this issue over to `renv`?

@colearendt If you wouldn't mind, yes. Please include a full example, if possible.

**Comment by aronatkins** [comment]
Closing, as this will become an renv issue.
