### ISSUE TITLE
Improve error message or perform fuzzy server matching

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rsconnect#107]
Tested on Ubuntu12-plain
Build #1535 

**Description:** When trying to publish a site, if you give full url instead of just server address @ rsconnect:deploysite() then IDE shows incorrect error message.

**Steps to reproduce:**
1. Create a folder with _site.yml, .rmd and index.rmd files 
2. Now run the following commands in IDE
3. Install rmarkdown and rsconnect packages if you don't have them
4. rmarkdown::render_site()
5. rsconnect::deploySite(render="local",account=“ChaitaTest”,server=“ip.address:3939”)

**Actual result:**  User cannot deploy site as the ip has port included in it, but the error message is not clear. (image attached)
![screen shot 2016-06-02 at 8 16 12 am](https://cloud.githubusercontent.com/assets/17551950/15746321/b1ee4a78-289b-11e6-9c32-a93083e277cc.png)

**Comment by jmcphers** [comment]
This isn't really specific to sites; we require that the server name match something from the server list exactly. We should give a better error message, or as @ChaitaC suggests just try to match a URL against the registered server URLs if the user didn't give the server's registered name.

**Comment by hadley** [comment]
Better error message now provided by `findAccounts()`
