### ISSUE TITLE
cran: donttest noSuggests

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#1074]
https://cran.r-project.org/web/checks/check_results_rsconnect.html

CRAN just reported donttest and noSuggests as additional issues against rsconnect.

These must be resolved before 2024-06-14.

**Comment by nealrichardson** [comment]
The donttest note isn't actually about donttest:

```
* checking for new files in some other directories ... NOTE
Found the following files/directories:
  ‘~/.cache/deno’ ‘~/.cache/deno/dep_analysis_cache_v1’
  ‘~/.cache/deno/gen’ ‘~/.cache/deno/npm’
```

**Comment by aronatkins** [comment]
> The donttest note isn't actually about donttest:

Understood. It's a side-effect of running Quarto. Quarto may have appeared on those hosts.
