### ISSUE TITLE
Prevent deploy if the bundle is an invalid shiny application

### ISSUE THREAD

**Issue by jspiewak** [rstudio/rsconnect#110]
User had an `app.R` instead of `ui.R` and `server.R`.
The bundle was pushed to shinyapps.io, an image built and a container started.
The deploy timed out after 30 seconds with no indication of what the failure was.
The user could not access the application's logs to see:

2016/06/28 15:57:46 Starting RStudio Connect v0.4.4.1986 [Cloud Edition]
2016/06/28 15:57:46 Debug logging enabled for area: connection
2016/06/28 15:57:46 Debug logging enabled for area: worker
2016/06/28 15:57:46 Using username: shiny
2016/06/28 15:57:46 AppDir specified ('/srv/connect/apps/mrPUP-dash2'), running in 'single-app-mode'.
2016/06/28 15:57:46 app directory doesn't contain a valid Shiny app

https://groups.google.com/d/msg/shinyapps-users/kC6VnfqLKAo/OMK3UotDCQAJ

@rstudio/connect unclear to me if Connect exited or just stopped. I think that shinyapps.io had to stop the container after waiting the 30 seconds for it to come up.

**Comment by aronatkins** [comment]
Connect is exiting. The "app directory doesn't contain a valid Shiny app" is fatal.

**Comment by jmcphers** [comment]
I believe Connect supports single-file Shiny apps now (reopen if this isn't the case!)
