### ISSUE TITLE
Dashes are removed from application name during deployment.

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#114]
I had opened the issue on `connect` repo since this was brining up a UI issue as well. But the actual issue is with `rsconnect` and affects `shinyapps.io` as well.

Refer to https://github.com/rstudio/connect/issues/3228 for details.

**Comment by jmcphers** [comment]
Should be resolved with https://github.com/rstudio/rsconnect/commit/b6ee55125da7beea8d6013900efbbf0993fae6a5.
