### ISSUE TITLE
"other destinations" deploy action only allows new deploy, not update

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#118]
I'm not sure if this should be filed against `rsconnect` or the IDE. Starting here.

If I select a prior deployment, I am allowed to either update or create a new deployment.
![screen shot 2016-09-15 at 2 28 02 pm](https://cloud.githubusercontent.com/assets/362187/18562214/c7c77542-7b50-11e6-9cf9-bb0bfad562ea.png)

However, if I select "Other destination...", I am not allowed to update.
![screen shot 2016-09-15 at 2 27 49 pm](https://cloud.githubusercontent.com/assets/362187/18562225/d6575d3e-7b50-11e6-9a18-fbf99d688016.png)

This made it very easy for me to end up with multiple deployment with the same name.
![screen shot 2016-09-15 at 2 25 45 pm](https://cloud.githubusercontent.com/assets/362187/18562251/f002e4c4-7b50-11e6-80b1-352bb2bf1070.png)

I have been in the habit of using "Other destination..." because that view lets me see both username and hostname.

I am pretty sure that before we introduced the notion of "title", keeping a constant app name would result in a deploy to the previous location.

**Comment by aronatkins** [comment]
In case it wasn't clear: I did not expect multiple deployments.

**Comment by aronatkins** [comment]
in addition, if I have multiple things with the same name, it is difficult to manage them because there is no disambiguation.
![screen shot 2016-09-15 at 2 32 51 pm](https://cloud.githubusercontent.com/assets/362187/18562386/76518a76-7b51-11e6-92ca-3d093642a4cd.png)

**Comment by jmcphers** [comment]
This is really all on the IDE side, so I'm closing this issue and I've opened one over there (#6113) with all your comments. 

Most of the behavior you describe is the title work doing what we expected it would, but perhaps we need to put some more thought into the design. Let's chat offline.
