### ISSUE TITLE
post-connect deploy, return to the dashboard URL, not the content URL

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#119]
If content has been previously deployed, we direct users to the "solo" URL for content, not the dashboard.

![screen shot 2016-09-15 at 2 35 08 pm](https://cloud.githubusercontent.com/assets/362187/18562453/bf936fba-7b51-11e6-9478-442602eda4e4.png)

Right now, we visit the dashboard (config url) only if the application needs configuration.

@trestletech seems to remember us wanting to change that behavior.

**Comment by hadley** [comment]
Based on reading the logic in `openURL()`, this has since been implemented.
