### ISSUE TITLE
rsconnect.max.bundle.size is too low for some shinyapps.io accounts

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rsconnect#124]
shinyapps.io accounts with the Basic plan and above are allowed to deploy application bundles up to 3GB in size, but the `rsconnect.max.bundle.size` defaults to 1GB.  If these shinyapps.io customers attempt to deploy application bundles that are between 1GB and 3GB in size, the deployment fails even though they are within their shinyapps.io plan limits because they hit the `rsconnect.max.bundle.size`.  The workaround is to set the `rsconnect.max.bundle.size` explicitly to allow a 3GB upload:

`options(rsconnect.max.bundle.size=3145728000)`

However, this is inconvenient an non-intuitive.  Since the goal of this setting is to prevent the accidental deployment of enormous directory trees, we could safely bump the default value up to 3GB to avoid the shinyapps.io deployment problem while still preventing an accidental massive deployment.  If a shinyapps.io customer has a smaller plan and attempts to deploy an application bundle that is within the 3GB rsconnect limit but larger than her shinyapps.io plan limit, shinyapps.io will reject it at the server, so the risk to this change seems small.

**Comment by jjallaire** [comment]
@jmcphers I'd be in favor of increasing the limit to 3GB. What do you think?

**Comment by jmcphers** [comment]
The only downside here is that if you accidentally deploy `~` you're now going to get a 3x longer hang while it accumulates files (the current limit is 1GB) until it hits the limit. That's probably an edge case, so I'd be fine with this change, but I'd prefer one that throttles by file count too.

**Comment by ajmcoqui** [comment]
@jspiewak do you have any feedback on throttling by file count?

**Comment by kevinushey** [comment]
What about catching attempts to deploy 'unlikely' directories? It seems like the most common culprit would be `~/` itself. What have we seen in the wild thus far?

**Comment by jspiewak** [comment]
@ajmcoqui No one has actually proposed what a file count limit might be. 10^3? 4? 5?

Honestly from a UI perspective, I would like to be prompted with a "did you really mean to do that?" dialog. If I say yes, then the option should be preserved for future deploys of the same project, whether from the console or the UI.

**Comment by ajmcoqui** [comment]
@kevinushey I have no data on whether attempts to deploy `~/` come up in the wild, but I would not be surprised if the current limit has saved people from accidents without them reporting it to us.

**Comment by aayushdua007** [comment]
Where do I actually write this "options(rsconnect.max.bundle.size=3145728000)" code? I have app.r and .Rprofile files. Any help would be appreciated. Thanks.

**Comment by jmcphers** [comment]
This goes in `.rsconnect_profile`. See `?rsconnect::rsconnectOptions` for details!

**Comment by nwheatleKite** [comment]
@aayushdua007, creating a .rsconnect_profile file in my project directory was not enough for the options to be recognized. I ran the options() code in the R studio Console 

\>`options(rsconnect.max.bundle.size=3145728000)` 

and this worked. I could check by running 

\> `getOption('rsconnect.max.bundle.size')`
