### ISSUE TITLE
Add a "debug mode" to the deployApp() function

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rsconnect#128]
There needs to be a way to turn on super-verbose output (HTTP, JSON, and stack traces; the exact R command being executed; etc.).  The IDE will have a switch somewhere to turn this on, to help us debug deployment problems.

Kevin's suggestion:  Perhaps as an R option (to avoid infecting APIs): options(rsconnect.verbose = 1, rsconnect.debug.level = 1)

**Comment by jmcphers** [comment]
I like @kevinushey's suggestion, except that there are already options which control verbose HTTP and JSON output, and it's confusing to have > 1 option controlling any given behavior (which has precedence?, etc.)

My proposal:

1) Add one new option, `rsconnect.error.trace`, which, if enabled, emits the traces of all errors occurring during deployment

2) Add an optional parameter to deployApp, which, if supplied, engages all of `rsconnect.http.trace`, `rsconnect.http.trace.json`, `rsconnect.http.verbose`, and `rsconnect.error.trace` if not already engaged, and prints the deployment command

**Comment by jmcphers** [comment]
This work is complete now!
