### ISSUE TITLE
Show unambiguous message when user trying to connect using http

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rsconnect#133]
Reported today by @tareefk 

When trying to deploy simple rmd he got the following error message

```
Preparing to deploy document...Error in response[[listName]] : subscript out of bounds
Calls: <Anonymous> ... getAppByName -> <Anonymous> -> listRequest -> append
Execution halted
```

Solution: Disconnect RSC connection to dogfood, and reconnect using https

Issue: The validation message was not clear and failed to indicate that user needs to reconnect using https

**Comment by ChaitaC** [comment]
Sorry moving this to connect.

**Comment by filipstachura** [comment]
Just want to let you know that this problem is still there.

Solution is the same - reconnecting with https.
