### ISSUE TITLE
Packrat errors should be better reported on deployment

### ISSUE THREAD

**Issue by trestletech** [rstudio/rsconnect#14]
(Migrated from https://github.com/rstudio/connect/issues/101)

For example, if I try to deploy with a version of packrat installed from source:

```
> rsconnect::deployApp(server = "dogfood")
Preparing to deploy application...DONE
Uploading application bundle...Error: Unable to retrieve package records for the following packages:
- 'packrat'
```

We should augment this error message with some prescriptions, e.g.
1. (For now) "Packages should be from CRAN or GitHub", or
2. (In the future) "This should be a packrat-managed project with local source tarballs that can be uploaded".

**Comment by hadley** [comment]
Superseded by #659 and work in #670
