### ISSUE TITLE
upload=FALSE to Connect fails with unhelpful error message

### ISSUE THREAD

**Issue by slopp** [rstudio/rsconnect#145]
Unlikely, but if a user attempts to deploy an app to a Connect server and specifies upload=FALSE the upload will fail with an error message:

**Error in data.frame(**name = "hello8", title = "", account = "seanlopp",  : 
  **arguments imply differing number of rows: 1, 0**

Upload=FALSE is not supported for Connect, so a more appropriate error message should be thrown

**Comment by jmcphers** [comment]
Good idea!
