### ISSUE TITLE
Internal Certificate Authorities difficult to use

### ISSUE THREAD

**Issue by trestletech** [rstudio/rsconnect#148]
Many organizations use internal CAs and install those certs as trusted in their user's browsers. (I'm not sure on the common mechanisms in play here, but could gather that info if helpful.)

rsconnect uses alternative mechanisms for connecting (curl, etc.) meaning that the machine hosting RStudio (often a desktop machine) needs to train curl to trust that internal CA. That's currently a manual process, as best I can tell.

Are there are any best practices around how to deploy an additional cert into curl or a better way for us to support this use case?

**Comment by CajH** [comment]
The certificates are stored in cert/cacert.pem in the R package folder. The path is hardcoded and might be overwritten when upgrading the R package.

Although ideally the certificates should be loaded from the browser (Internet Explorer in a Windows environment), there is also no possibility to set the path to the certificate. If there was an option to set a custom path, we could put the certificate in a repository in a place it cannot get overwritten.

The hardcoding is in http.R:
`options$cainfo <- system.file("cert/cacert.pem", package = "rsconnect")`

**Comment by jmcphers** [comment]
This is being tracked in https://github.com/rstudio/rsconnect/issues/178, and there is work happening to make it possible to set a custom path (via an environment variable) or use a cert specifically to connect to a particular server when needed.
