### ISSUE TITLE
Tar filename encoding issue

### ISSUE THREAD

**Issue by jspiewak** [rstudio/rsconnect#150]
A shinyapps.io user posted to the [group](https://groups.google.com/d/msg/shinyapps-users/g1Oc31vCv4U/wQjZOdC3EQAJ) about an issue.

The locale in the manifest.json is pt_BR.
The filename in the manifest.json is www/MUNICIPIOS_polígonos.txt
However, un-tar'ing the bundle results in a file named www/MUNICIPIOS_pol%EDgonos.txt

**Comment by kevinushey** [comment]
I'm guessing this is a Windows-only issue, but I wasn't able to reproduce this directly.

Do we have a reproducible example?

**Comment by jspiewak** [comment]
I have not reproduced it myself, simply looked at the user's bundle.
How is the tar'ing accomplished on Windows? Does that support í?

**Comment by jspiewak** [comment]
Had another case of this today. Is your proposed change safe, could it be merged soon?

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rsconnect/pull/165.
