### ISSUE TITLE
Update after deploying not working with multiple servers. 

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rsconnect#151]
IDE version (mac desktop) Version 1.1.47
Ubuhntu14-plain instance
Connect build #1.4.2-4

**Description:** Might be possible that rsconnect is getting tripped up when you have deployed the existing app somewhere else and then go to deploy (and update) it to a second location. It doesn’t always record the second location properly.

**Steps:**
1. Publish app 'Deploy1' on to `Dogfood` (https://rsc.radixu.com), destination account `<YourUserOnDogfood>`
2. Now deploy the same app on to `Beta` (https://beta.rstudioconnect.com/), destination account `<YourUserOnBeta>`
3. Now, change/Update content and reploy to `Beta` (Use same destination account that you used in step #2)

**Result:** This will trigger a new deploy and you won't be able to update content on `Beta`

- Try to update and redeploy on Dogfood, Content gets updated on Dogfood.

```
> packageDescription("rsconnect")
Package: rsconnect
Type: Package
Title: Deployment Interface for R Markdown Documents and Shiny
       Applications
Version: 0.7
Date: 2016-12-20
Author: JJ Allaire
Maintainer: JJ Allaire <jj@rstudio.com>
Description: Programmatic deployment interface for 'RPubs',
       'shinyapps.io', and 'RStudio Connect'. Supported content
       types include R Markdown documents, Shiny applications,
       plots, and static web content.
Depends: R (>= 3.0.0)
Imports: digest, PKI, RCurl, RJSONIO, packrat (>= 0.4.8-1), yaml (>=
       2.1.5), rstudioapi (>= 0.5)
Suggests: scrypt, knitr, testthat, rmarkdown (>= 1.1)
Enhances: BiocInstaller
License: GPL-2
RoxygenNote: 5.0.1
GithubRepo: rsconnect
GithubUsername: rstudio
GithubRef: master
GithubSHA1: 3a1715131e9fa7a29577098e16744542dc0cd627
Origin: RStudioIDE
Packaged: 2017-01-04 05:03:09 UTC; rstudio
Built: R 3.2.1; ; 2017-01-04 15:37:46 UTC; unix

-- File: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rsconnect/Meta/package.rds 
```

![screen shot 2017-01-26 at 9 57 41 am](https://cloud.githubusercontent.com/assets/17551950/22340672/d660d53c-e3b3-11e6-8337-7f69fda9063f.png)

**Comment by jmcphers** [comment]
I haven't been able to reproduce this; please reopen if you're still experiencing it!
