### ISSUE TITLE
add native CI function to RStudio Connect / rsconnect

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rsconnect#155]
I'm a huge fan of RStudio Connect, and I'm hoping we'll purchase it soon.
I just wish it would _also_ include tight integration with git(hub) (or some other SCM), and act as a CI service.

It might otherwise seem handy and work for smaller projects, but for bigger/more complex scripts, deploying from RStudio without checks and tight SCM integration seems a little scary to me.
(I, or someone else, will inevitably push something broken onto RStudio Connect).

I understand that I can *already* [deploy programmatically](http://docs.rstudio.com/connect/admin/appendix-rstudio-connect-deployment-guide.html) to RStudio Connect with `rsconnect::`, so we're going to use some Travis CI now.
However, this setup seems a bit suboptimal to me:

1. it's a bit tedious, because I have to manage *two* build environments with (CI and Connect), both with dependences etc.
2. At least (hosted) Travis kills the "on-premise" advantage of Connect, enterprise editions are *really* expensive and overkill. (Jenkins might be easier to use on-premise).
3. (At least) Travis isn't entirely trivial to get to work with R when more demanding dependencies come into play (partly because Travis is based on `precise`?). So anyway, Connect *already* has/needs a proper R build environment, so it'd be great to use this twice.

So, I'm really dreaming of a day I can ditch the separate CI.

**Does this make sense to anyone else, or am I thinking about this / using it all wrong?!**

@ajmcoqui gave me invaluable feedback on a related support issue.

**Comment by trestletech** [comment]
Thanks for the great feedback, Maximilian! I'm going to close this issue in this repo since this is where we track issues specifically with the rsconnect package. But I'll get this filed appropriately in our internal systems and will reach out via our support system if I need more input.

Thanks again!
