### ISSUE TITLE
Feature Request: `showProperties` returns size in bytes of app bundle 

### ISSUE THREAD

**Issue by martinjhnhadley** [rstudio/rsconnect#157]
When running an account for multiple users, to ensure fair usage we have a "maximum shiny app size" that we enforce as much as possible.

It would be useful if the `showProperties`function of `rsconnect` could return the actual byte size of an app bundle, as we could then routinely delete apps which flaunt our maximum file size.

The bundle size isn't included in the shinyapps.io dashboard itself, so it may be that this data is not easily surfaceable to the rsconnect API. However, for many users I think it could be a useful metric to return.

Cheers

**Comment by jmcphers** [comment]
Agree this would be helpful but as you surmise we don't have the data locally to make it possible.
