### ISSUE TITLE
Cannot publish application with dependency on R-Forge package

### ISSUE THREAD

**Issue by EricQLi** [rstudio/rsconnect#161]
As asked in [https://github.com/rstudio/shinydashboard/issues/190#issuecomment-282733827](url)
Some packages loaded in my app may cause problems:
```
require(shinydashboard)
require(Rdonlp2)
require(jpeg)
```
After I deployed the app using

```
options(encoding = "UTF-8")
deployApp()
```

it hints:

```
deployApp()
Failed to lint file 'app.R'
The linter failed with message:

input string 1 is invalid UTF-8
Failed to lint file 'app.R'
The linter failed with message:

input string 1 is invalid UTF-8
Failed to lint file 'app.R'
The linter failed with message:

input string 1 is invalid UTF-8
Preparing to deploy application...DONE
Uploading bundle for application: 159687...
Error: Unable to retrieve package records for the following packages:
- "Rdonlp2"
```

How could this be solved?

**Comment by EricQLi** [comment]
Could be the problem caused by the package Rdonlp2, because it was on https://r-forge.r-project.org/.

**Comment by bborgesr** [comment]
If you try to deploy it with the `Rdonlp2` package (i.e. a fake app without any calls to that package or that package's functions), does it work? If that's the case, I think the problem really is simply that RSC does not get packages from R-Forge... There is no good workaround for that yet... You can see if the authors have a github repo for the package, or you can try putting this in the `.Rprofile` for your project (though it is not guaranteed to work...):

```r
options(repos = c(getOption("repos"), rforge = "http://R-Forge.R-project.org"))
```

**Comment by EricQLi** [comment]
> If you try to deploy it with the Rdonlp2 package (i.e. a fake app without any calls to that package or that package's functions), does it work? If that's the case, I think the problem really is simply that RSC does not get packages from R-Forge... There is no good workaround for that yet... You can see if the authors have a github repo for the package, or you can try putting this in the .Rprofile for your project (though it is not guaranteed to work...):

>  ```
> options(repos
> 
>  = c(getOption("repos"), rforge = "http://R-Forge.R-project.org"))
> ```

I have tried to change the .Rprofile and deploy a fake app the Rdonlp2 package (i.e. a fake app without any calls to that package or that package's functions). It didn't work with Error:
```
Error: Unable to retrieve package records for the following packages:
- "Rdonlp2"
```

**Comment by bborgesr** [comment]
If you still get that error, your app still does `library(Rdonlp2)` or something to the same effect.... You need to remove all relations to that library in order to isolate the problem and see if it still persists.

**Comment by jiehwan94** [comment]
@bborgesr I don't know if the problem has been solved, but I am having a similar issue [here](https://github.com/rstudio/rsconnect/issues/164). Is it because of shinydashboard library?

**Comment by jmcphers** [comment]
shinyapps.io does not support R-forge packages, which is the root of the problem. There's a note to this effect in their user guide (with instructions on how to get in touch if this is an issue for you!)

https://docs.rstudio.com/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud
