### ISSUE TITLE
ERROR: there is no package called "shinydashboard"

### ISSUE THREAD

**Issue by jiehwan94** [rstudio/rsconnect#164]
I am trying to deploy my app.R file on shinyapp.io for the first time, but I am getting an error saying **ERROR: there is no package called "shinydashboard"** in the chrome tab. It runs fine when I run the app in RStudio. I found a similar post [https://github.com/rstudio/shinydashboard/issues/190](url) but it doesn't seem to have a sound solution.

Here is what I have from running devtools::session_info() and rsconnect::appDependencies(). Also, I have pasted my entire code in app.R below.

`> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   i386, mingw32               
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  Korean_Korea.949            
 tz       Asia/Seoul                  
 date     2017-03-15                  

Packages ---------------------------------------------------------------------------------------------------------------------
 package        * version  date       source                          
 assertthat       0.1      2013-12-06 CRAN (R 3.1.3)                  
 backports        1.0.5    2017-01-18 CRAN (R 3.3.2)                  
 bitops           1.0-6    2013-08-17 CRAN (R 3.1.3)                  
 codetools        0.2-15   2016-10-05 CRAN (R 3.3.2)                  
 DBI              0.6      2017-03-09 CRAN (R 3.3.3)                  
 devtools         1.11.1   2016-04-21 CRAN (R 3.1.3)                  
 digest           0.6.9    2016-01-08 CRAN (R 3.1.3)                  
 dimple         * 0.1      2017-03-13 Github (Bart6114/dimple@2c25304)
 dplyr          * 0.5.0    2016-06-24 CRAN (R 3.3.3)                  
 DT             * 0.2      2016-08-09 CRAN (R 3.3.3)                  
 evaluate         0.10     2016-10-11 CRAN (R 3.3.2)                  
 flexdashboard  * 0.4      2017-02-01 CRAN (R 3.3.2)                  
 googleVis      * 0.6.2    2017-01-01 CRAN (R 3.3.2)                  
 htmltools        0.3.5    2016-03-21 CRAN (R 3.1.3)                  
 htmlwidgets      0.6      2016-02-25 CRAN (R 3.1.3)                  
 httpuv           1.3.3    2015-08-04 CRAN (R 3.1.3)                  
 jsonlite         0.9.19   2015-11-28 CRAN (R 3.1.3)                  
 knitr            1.15.1   2016-11-22 CRAN (R 3.3.2)                  
 lazyeval         0.2.0    2016-06-12 CRAN (R 3.3.3)                  
 magrittr         1.5      2014-11-22 CRAN (R 3.1.3)                  
 memoise          1.0.0    2016-01-29 CRAN (R 3.1.3)                  
 mime             0.3      2015-03-29 CRAN (R 3.1.3)                  
 miniUI           0.1.1    2016-01-15 CRAN (R 3.3.2)                  
 R6               2.1.2    2016-01-26 CRAN (R 3.1.3)                  
 Rcpp             0.12.9   2017-01-14 CRAN (R 3.3.2)                  
 RCurl            1.95-4.8 2016-03-01 CRAN (R 3.1.3)                  
 RJSONIO          1.3-0    2014-07-28 CRAN (R 3.1.3)                  
 rmarkdown        1.3      2016-12-21 CRAN (R 3.3.2)                  
 rprojroot        1.2      2017-01-16 CRAN (R 3.3.2)                  
 rsconnect      * 0.7      2016-12-21 CRAN (R 3.3.3)                  
 shiny          * 1.0.0    2017-01-12 CRAN (R 3.3.2)                  
 shinydashboard * 0.5.3    2016-09-20 CRAN (R 3.3.2)                  
 shinyjs        * 0.9      2016-12-26 CRAN (R 3.3.2)                  
 stringi          1.0-1    2015-10-22 CRAN (R 3.1.3)                  
 stringr          1.0.0    2015-04-30 CRAN (R 3.1.3)                  
 tibble           1.2      2016-08-26 CRAN (R 3.3.3)                  
 withr            1.0.1    2016-02-04 CRAN (R 3.1.3)                  
 xtable           1.8-2    2016-02-05 CRAN (R 3.1.3)                  
 yaml             2.1.14   2016-11-12 CRAN (R 3.3.2)                  
> rsconnect::appDependencies()
          package    version source
1              BH   1.60.0-1   CRAN
2              DT        0.2   CRAN
3            MASS     7.3-45   CRAN
4             NLP      0.1-9   CRAN
5              R6      2.1.2   CRAN
6    RColorBrewer      1.1-2   CRAN
7            Rcpp     0.12.9   CRAN
8      assertthat        0.1   CRAN
9       backports      1.0.5   CRAN
10      base64enc      0.1-3   CRAN
11         bitops      1.0-6   CRAN
12        caTools     1.17.1   CRAN
13     colorspace      1.2-6   CRAN
14         crayon      1.3.1   CRAN
15           curl      0.9.7   CRAN
16      dichromat      2.0-0   CRAN
17         digest      0.6.9   CRAN
18         dimple        0.1 github
19       evaluate       0.10   CRAN
20  flexdashboard        0.4   CRAN
21        ggplot2      2.2.1   CRAN
22      googleVis      0.6.2   CRAN
23         gtable      0.1.2   CRAN
24          highr        0.5   CRAN
25      htmltools      0.3.5   CRAN
26    htmlwidgets        0.6   CRAN
27         httpuv      1.3.3   CRAN
28       jsonlite     0.9.19   CRAN
29          knitr     1.15.1   CRAN
30       labeling        0.3   CRAN
31       lazyeval      0.2.0   CRAN
32       magrittr        1.5   CRAN
33       markdown      0.7.7   CRAN
34        memoise      1.0.0   CRAN
35           mime        0.3   CRAN
36         miniUI      0.1.1   CRAN
37        munsell      0.4.2   CRAN
38        packrat    0.4.8-1   CRAN
39           plyr      1.8.4   CRAN
40         praise      1.0.0   CRAN
41          readr      0.2.2   CRAN
42       reshape2      1.4.1   CRAN
43      rmarkdown        1.3   CRAN
44      rprojroot        1.2   CRAN
45         scales      0.4.1   CRAN
46          shiny      1.0.0   CRAN
47 shinydashboard      0.5.3   CRAN
48        shinyjs        0.9   CRAN
49           slam     0.1-32   CRAN
50    sourcetools 0.1.5-9000 github
51        stringi      1.0-1   CRAN
52        stringr      1.0.0   CRAN
53       testthat      1.0.2   CRAN
54         tibble        1.2   CRAN
55             tm      0.6-2   CRAN
56      wordcloud        2.5   CRAN
57         xtable      1.8-2   CRAN
58           yaml     2.1.14   CRAN`

```
rm(list = ls())
library(shiny)
library(shinydashboard)
library(shinyjs)
library(googleVis)
library(flexdashboard)
library(DT)
library(dimple)
library(dplyr)
library(rsconnect)

rsconnect::setAccountInfo(name='jiehwan94', token='TOKEN', secret='SECRET')


ui1 <-tagList(
  div(id = "login",
      wellPanel(textInput("userName", "Username"),
                passwordInput("passwd", "Password"),
                br(),actionButton("Login", "Log in"))),
  tags$style(type="text/css", "#login {font-size:10px;   text-align: left;position:absolute;top: 40%;left: 50%;margin-top: -100px;margin-left: -150px;}")
)

ui2<- dashboardPage(
  dashboardHeader(title="S-League X Shoot!"),
  dashboardSidebar(
    gaugeOutput("plt1",height='130px'),
    sidebarMenu(
      menuItem("Shoot 소개", tabName = "shoot_info", icon= icon("heart", lib= "glyphicon")),
      menuItem("점수순위 및 분석", tabName = "leaderboard", icon= icon("bar-chart-o")),
      menuItem("참가신청서", tabName = "signup", icon=icon("pencil", lib= "glyphicon"),
               badgeLabel = "관리자", badgeColor = "red")
    ),
    uiOutput("checkbox")
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "shoot_info",
              fluidRow(
                tabBox(
                  id= "tabtab1", width = 12,
                  tabPanel("Shoot 소개",
                           fluidRow(div(img(src="1.jpg"), img(src="2.jpg"), img(src="3.jpg"))),
                           fluidRow(div(img(src="4.jpg"), img(src="5.jpg"), img(src="6.jpg")))
                  ),
                  tabPanel("소아암 소개 및 후원",
                           fluidRow(tags$a(img(src="66.jpg"),href="http://www.soaam.or.kr/donation/introduction.php?PHPSESSID=80f03a3e88d2ee7137d904c22e00a75b")),
                           fluidRow(div(img(src="11.jpg"))),
                           fluidRow(div(img(src="22.png"))),
                           fluidRow(div(img(src="33.png"))),
                           fluidRow(div(img(src="44.png"))),
                           fluidRow(div(img(src="55.png")))
                  ),
                  tabPanel("2016년도 Shoot 활동",
                           fluidRow(div(img(src="111.jpg"))),
                           fluidRow(div(img(src="222.jpg"))),
                           fluidRow(div(img(src="333.jpg"))),
                           fluidRow(div(img(src="444.jpg"))),
                           fluidRow(div(img(src="555.jpg"))),
                           fluidRow(div(img(src="666.jpg")))
                  )
                )
              )
      ),
      tabItem(tabName = "leaderboard",
              fluidRow(
                tabBox(
                  id= "tabtab2", width = 12,
                  tabPanel("선수별순위",
                           dataTableOutput("content"),
                           dimpleOutput("distPlot1"),
                           width=12),
                  tabPanel("팀별순위",
                           uiOutput("summa2"), 
                           dimpleOutput("distPlot2"),
                           width=6),
                  tabPanel("단과대별순위",
                           uiOutput("summa3"), 
                           dimpleOutput("distPlot3"),
                           width=6)
                )
              )
      ),
      tabItem(tabName = "signup",
              uiOutput("page") #This is the only difference between ui2 and ui3
      )
      
    ))
)
  ui3<- box(fluidRow(
                    tabBox(
                      id= "tabset1", width = 12,
                      tabPanel("참가신청서", textInput("name",  "이름"),
                               radioButtons("gender", "성별", list("남자","여자")),
                               selectInput("college", "대학",
                                           choices = list("간호대학", "경영대학",
                                                          "공과대학", "농업생명과학대학",
                                                          "미술대학", "법과대학",
                                                          "사범대학", "사회과학대학",
                                                          "수의과대학", "생활과학대학",
                                                          "약학대학", "음악대학",
                                                          "인문대학", "의과대학",
                                                          "자연과학대학", "기타"),
                                           selected = 1),
                               selectInput("team", "교내 소속축구팀",
                                           choices = list("싸커21", "아르마다",
                                                          "에코플러스", "아크로",
                                                          "P.O.S", "공대",
                                                          "자연대", "관악사",
                                                          "농대축구부 휘모리", "지오싸카스",
                                                          "새츠", "샥스",
                                                          "FC SEES", "Cells United",
                                                          "프리템포", "남풍",
                                                          "없음")),
                               textInput("score", "점수"),
                               actionButton("click_counter","Submit"), width=12),
                      tabPanel("참가자 삭제", textInput("delete_name", "삭제할 참가자 이름을 아래 박스에 기입한 뒤, 삭제 버튼을 눌러주세요."),
                               actionButton("delete_button","삭제"),
                               h4("주의사항: 동명이인이 있을시, 모두가 삭제되므로 삭제하지 않고자 하는 참가자의 정보를 다시 '참가신청서' tab에서 기입해줘야 함."),width=12)
                    )
                  ),
                  fluidRow(
                    box(dataTableOutput("nText"), width=12)
                  )
  )


server <- shinyServer(function(input, output, session) {
  
  Logged = FALSE;
  my_username <- "test"
  my_password <- "test"
  
  USER <- reactiveValues(Logged = Logged)
  
  
  
  observe({ 
    #print("Observe")
    if (USER$Logged == FALSE) {
      #print("1")
      if (!is.null(input$Login)) {
        #print("2")
        if (input$Login > 0) {
          #print("Username")
          Username <- isolate(input$userName)
          Password <- isolate(input$passwd)
          #print(sprintf("Username:%s Pass:%s",Username,Password))
          Id.username <- which(my_username == Username)
          Id.password <- which(my_password == Password)
          if (length(Id.username) > 0 & length(Id.password) > 0) {
            if (Id.username == Id.password) {
              #print("Success")
              USER$Logged <- TRUE
            } 
          }
        } 
      }
    }    
  })
  
  output$page <- renderUI({
    #print("output$page called")
    if (USER$Logged == FALSE){
      output$page <- renderUI({
        div(class="outer",do.call(bootstrapPage,c("",ui1)))
      })
    }
    if (USER$Logged == TRUE)
      ui3
  })
  
  output$page <- renderUI({
    if (USER$Logged==TRUE){
      return({  div(class="outer",do.call(bootstrapPage,c("",ui3)))  })
    } else {
      return({  div(class="outer",do.call(bootstrapPage,c("",ui1)))    })
    }
  })
  
  
  
  observe({
    values<- reactiveValues(df = NULL)
    money<- reactiveValues(a=0)
    
    
    observeEvent(input$click_counter, {
      
      # Button 클릭시, 500원씩 적립
      money$a<- money$a+10000
      
      # create df
      name<- input$name
      gender<- input$gender
      college<- input$college
      team<- input$team
      score<- as.numeric(input$score)
      rank<- 0
      
      new_row<- data.frame(rank,name,college,gender,team,score, stringsAsFactors = FALSE)
      
      values$df<- rbind(values$df, new_row)
      values$df<- values$df[order(values$df$score, decreasing=TRUE),]
      values$df$rank<- 1:nrow(values$df)
    })
    
    observeEvent(input$delete_button, {
      values$df<- values$df[-c(values$df$name==input$delete_name),]
    })
    
    output$nText<- renderDataTable({
      values$df}, options = list(orderClasses = TRUE,
                                 lengthMenu = c(5, 10, 30), pageLength = 5), rownames=FALSE)
    
    output$content<- renderDataTable({
      values$df}, options = list(orderClasses = TRUE,
                                 lengthMenu = c(5, 10, 30), pageLength = 10), rownames=FALSE)
    
    
    output$summa1 <- renderPrint({summary(values$df$score)})
    
    output$distPlot1<- renderdimple({
      name <- group_by (values$df, score)
      dd<- as.data.frame(summarise(name, n()))
      colnames(dd)<- c("score","count")
      
      dimple(dd,
             xCategory="score",
             xOrderRule="score",
             yMeasure="count")
    })
    
    df2<- data.frame()
    output$summa2 <- renderGvis({
      df2<<- df2[0,]
      for (team_name in unique(values$df$team)){
        rank <- 0
        team <- team_name
        score <- format(mean(values$df[values$df$team==team_name,]$score), digits=3)
        
        new_row<- data.frame(rank, team, score, stringsAsFactors = FALSE)
        
        df2 <<- rbind(df2, new_row)
        df2 <<- df2[order(as.numeric(df2$score), decreasing=TRUE),]
        df2$rank <<- 1:nrow(df2)
      }
      return(gvisTable(df2[order(df2$score, decreasing=TRUE),]))
    })
    
    dff2<- data.frame()
    output$distPlot2 <- renderdimple({
      dff2<<- dff2[0,]
      for (team_name in unique(values$df$team)){
        rank <- 0
        team <- team_name
        score <- format(mean(values$df[values$df$team==team_name,]$score), digits=3)
        
        new_row<- data.frame(rank, team, score, stringsAsFactors = FALSE)
        
        dff2 <<- rbind(dff2, new_row)
        dff2 <<- dff2[order(as.numeric(dff2$score), decreasing=TRUE),]
        dff2$rank <<- 1:nrow(dff2)
      }
      dimple(dff2,
             yCategory="team",
             yOrderRule="score",
             xMeasure="score")
    })
    
    
    df3<- data.frame()
    output$summa3 <- renderGvis({
      df3<<- df3[0,]
      for (college_name in unique(values$df$college)){
        rank <- 0
        college <- college_name
        score <- format(mean(values$df[values$df$college==college_name,]$score), digits=3)
        
        new_row<- data.frame(rank, college, score, stringsAsFactors = FALSE)
        
        df3 <<- rbind(df3, new_row)
        df3 <<- df3[order(as.numeric(df3$score), decreasing=TRUE),]
        df3$rank <<- 1:nrow(df3)
      }
      return(gvisTable(df3[order(df3$score, decreasing=TRUE),]))
    })
    
    dff3<- data.frame()
    output$distPlot3 <- renderdimple({
      dff3<<- dff3[0,]
      for (team_name in unique(values$df$team)){
        rank <- 0
        team <- team_name
        score <- format(mean(values$df[values$df$team==team_name,]$score), digits=3)
        
        new_row<- data.frame(rank, team, score, stringsAsFactors = FALSE)
        
        dff3 <<- rbind(dff3, new_row)
        dff3 <<- dff3[order(as.numeric(dff3$score), decreasing=TRUE),]
        dff3$rank <<- 1:nrow(dff3)
      }
      dimple(dff3,
             yCategory="team",
             yOrderRule="score",
             xMeasure="score")
    })
    
    output$plt1 <- renderGauge({
      gauge(money$a, min = 0, max = 300000, symbol = '원', abbreviate=FALSE, label = paste("모금액"),gaugeSectors(
        success = c(0,300000)))
    })
    
  })
})

shinyApp(ui = ui2, server = server)
```

**Comment by jspiewak** [comment]
Could you remove the `library(rsconnect)` and `rsconnect::setAccountInfo` calls inside of the application and try deploying again?

Unless your application itself is going to be deploying something, this should not be necessary.

**Comment by jiehwan94** [comment]
I removed the library(rsconnect) and rsconnect::setAccountInfo then tried again, but I am getting the same error.

I have chosen UTF-08 encoding by going to File -> Reopen with Encoding -> Choose "UTF-08". I had to do this while I was building my app to avoid issues pertaining to writing Korean words in my code.

Right now, I click "Run App" in RStudio, click "Republish" button located in the top right corner, then click publish.

The following message appears in RStudio console right after:

Preparing to deploy application...DONE
Uploading bundle for application: 163764...DONE
Deploying bundle: 747483 for application: 163764 ...
Waiting for task: 357609429
  building: Processing bundle: 747483
  building: Parsing manifest
  building: Building image: 736896
  building: Installing packages
building: Installing files
building: Pushing image: 736896
deploying: Starting instances
rollforward: Activating new instances
  terminating: Stopping old instances

Then, as the new tab in my web browser is opened with the **ERROR: there is no package called "shinydashboard"** message, the  following message is displayed in RStudio console:

Listening on http://127.0.0.1:4568
Failed to lint file 'app.R'
The linter failed with message:

invalid multibyte string at '<ec><82><ac>?<ad>: <eb>룞紐낆씠<ec>씤<ec>씠 <ec>엳<ec>쓣<ec>떆, 紐⑤몢媛 <ec>궘<ec>젣<eb>릺誘濡<9c> <ec>궘<ec>젣<ed>븯吏 <ec>븡怨좎옄 <ed>븯<eb>뒗 李멸<b0><ec>옄<ec>쓽 <ec>젙蹂대<a5><bc> <eb>떎<ec>떆 '李멸<b0><ec>떊泥<ad><ec>꽌' tab<ec>뿉<ec>꽌 湲곗엯<ed>빐以섏빞 <ed>븿."),width=12)'
Failed to lint file 'app.R'
The linter failed with message:

invalid multibyte string at '<ec><82><ac>?<ad>: <eb>룞紐낆씠<ec>씤<ec>씠 <ec>엳<ec>쓣<ec>떆, 紐⑤몢媛 <ec>궘<ec>젣<eb>릺誘濡<9c> <ec>궘<ec>젣<ed>븯吏 <ec>븡怨좎옄 <ed>븯<eb>뒗 李멸<b0><ec>옄<ec>쓽 <ec>젙蹂대<a5><bc> <eb>떎<ec>떆 '李멸<b0><ec>떊泥<ad><ec>꽌' tab<ec>뿉<ec>꽌 湲곗엯<ed>빐以섏빞 <ed>븿."),width=12)'
Warning in gregexpr("../", content, fixed = TRUE) :
  input string 27 is invalid in this locale
Warning in gregexpr("../", content, fixed = TRUE) :
  input string 28 is invalid in this locale
Warning in gregexpr("../", content, fixed = TRUE) :
  input string 29 is invalid in this locale
Warning in gregexpr("../", content, fixed = TRUE) :
  input string 40 is invalid in this locale
Warning in gregexpr("../", content, fixed = TRUE) :
  input string 44 is invalid in this locale

**Comment by jspiewak** [comment]
The linter failing could definitely cause an incomplete determination of the dependencies of the application. One of the `rsconnect` package authors will have to step in to help figure out why that is occurring.

**Comment by jiehwan94** [comment]
@jspiewak  Do you happen to know other ways to publish my app on server besides using shinyapps.io?

**Comment by jiehwan94** [comment]
Btw, I can deploy the demo app which does NOT use **library(shinydashboard)** [here](https://shiny.rstudio.com/articles/shinyapps.html).

**Comment by jspiewak** [comment]
I took your `app.R` and tried deploying myself, and it is failing to build `dimple`, seemingly because it does not declare its dependency upon `htmlwidgets`. Even adding a `library(htmlwidgets)` didn't help. Commenting out usage of `dimple` allowed me to deploy the application, which launched.

**Comment by RedOakMark** [comment]
I'd suggest the following:

1. Split your files into server.R and ui.R and then
2. Add library(shinydashboard) to your ui.R file, as well as the server.R file

Even though I have a libraries.R file that I source in the server.R file, once I added the required packages to ui.R, shinyapps.io was able to load my ShinyDashboard application.

Hope this helps.

**Comment by xyulie** [comment]
> I'd suggest the following:
> 
> 1. Split your files into server.R and ui.R and then
> 2. Add library(shinydashboard) to the top of your ui.R file, as well as the server.R file
> 
> Even though I have a libraries.R file that I source in the server.R file, once I added the required packages to ui.R, shinyapps.io was able to load my ShinyDashboard application.
> 
> Hope this helps.

THANK YOU VERY MUCH!!!
my app is finally online now after 7h of debugging 👍

**Comment by gorkang** [comment]
Just for future reference, this issue also occurs when the RStudio project has a DESCRIPTION file that do not contain the offending package in the Imports section: stackoverflow.com/a/61325306/1873521
