### ISSUE TITLE
Cannot publish shiny application 

### ISSUE THREAD

**Issue by wooopenr** [rstudio/rsconnect#168]
I am running on Linux red hat with R 3.2.2 + rstudio + reconnect

Hello, I was trying publish my shiny application, app.R, which was created by clicking on file -> new file -> "shiny web app" from rstudio-server to rstudio-connect. 
 
We already have lot of packages installed under specific directory (/dir/path/where/we/have/packages/installed) for users on server since internet connection not allowed to outside world. 

I was wonder how can I share those installed packages with rstudio-server and rstudio-connect so that when users tries to publish documents, rstudio-connect application doesn't have to look for packages at may be "cran.rstudio.com to install packages. is this possible? 

"rstudio-connect" (package management) admin docs not helping much and they are not clearly defined. 

Can you help me with this?
 Thanks!

**Comment by jmcphers** [comment]
This forum is for bugs in the rsconnect package itself. As an RStudio Connect customer you're entitled to support, so start with an email to support@rstudio.com. You can also try our community forum, https://community.rstudio.com/.
