### ISSUE TITLE
Is rsconnect compatible with PKI 0.1-5?

### ISSUE THREAD

**Issue by yihengli** [rstudio/rsconnect#170]
ENV:
mac: 10.12.4
R: 3.4.0

```R
install.packages('PKI',,'http://www.rforge.net/')
install.packages('rsconnect')
library(rsconnect)

rsconnect::setAccountInfo(...)
deployApp(...)

Preparing to deploy application...DONE
Uploading bundle for application: 150364...
Error: Unable to retrieve package records for the following packages:
- 'PKI'
```

Just wondering if it's because rsconnect is currently not compatible with the PKI version.

I used the latest PKI because I cannot directly `install.packages('PKI')` due to openssl issues.

**Comment by jmcphers** [comment]
We now use openssl, thanks to @jeroen. See https://github.com/rstudio/rsconnect/pull/116.
