### ISSUE TITLE
Custom package in private repository not publishing

### ISSUE THREAD

**Issue by jeffkeller87** [rstudio/rsconnect#173]
I followed [these instructions](https://rstudio.github.io/packrat/custom-repos.html) to create a private package repository `myCRAN` that contains a single custom package `myPackage`. Then, I followed [these instructions](https://support.rstudio.com/hc/en-us/articles/226871467-Package-management-in-RStudio-Connect) in an attempt to get source code published to RStudio Connect properly.

After modifying my `.Rprofile` to include

```
options(repos = c(CRAN = "https://cran.rstudio.com/",
                  myCRAN = "http://my.ip.address/myCRAN/"))
```

I am successfully able to call `install.packages("myPackage")` even though `myPackage` is not available on CRAN.

However, when publishing to my RStudio Connect server, I receive the following error:

```
Error: Unable to retrieve package records for the following packages:
- 'myPackage'
```

Being able to publish source code to RStudio Connect is the one barrier preventing adoption at my organization. Any help is greatly appreciated!

**Comment by kevinushey** [comment]
Hi Jeff,

Can you confirm whether you added the `Repository: myCRAN` field to the package's DESCRIPTION file? It should exist as part of the source tarball that you've placed on your custom CRAN-like repository.

**Comment by jeffkeller87** [comment]
Wow, that... solved it. Where can I learn more about the `Repository:` parameter for package `DESCRIPTION` files? I've never heard of it and see no mention of it in [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file).

**Comment by kevinushey** [comment]
It's discussed briefly in the document at https://rstudio.github.io/packrat/custom-repos.html, but you're right that we don't do a great job of documenting this explicitly anywhere. The landscape is a bit confusing but I'll try to explain what's going on.

Normally, packages retrieved from the default CRAN mirrors have the field

    Repository: CRAN

field appended to their DESCRIPTION file. Packrat (the engine used to collect + reinstall R package dependencies) uses that field as a marker whether a particular package should be eligible for retrieval from a CRAN-like repository -- that is, any repository declared in the `repos` R option.

When a locally-developed package is installed from sources, that field is typically not present. In such a case, Packrat assumes that the package was not retrieved from a CRAN-like repository, and so should not attempt to restore that package from CRAN. That typically leads to the error you're seeing -- Packrat is now unable to discover where that package came from, and so installation would fail during deployment.

We've discussed a bit whether we should relax this requirement and allow packages installed from sources to be retrieved from CRAN regardless (when the same version of that package is available), but haven't yet decided
