### ISSUE TITLE
curl option failing to find file/directory

### ISSUE THREAD

**Issue by jspiewak** [rstudio/rsconnect#174]
R 3.4, rsconnect 0.8, Mac

```
> options(rsconnect.http = "curl")
> rsconnect::deployApp(appName="allonsNewPool", account='jspiewak')
Preparing to deploy application...
Error in file(outputFile, "rb") : cannot open the connection
In addition: Warning message:
In file(outputFile, "rb") :
  cannot open file '/var/folders/ls/cwyxr83n79161sgg0y7vq2k40000gn/T//RtmpSvguNA/file106137c71793': No such file or directory
```

Double checking, that directory actually *does* exist (both with and without the extra slash):

```
% ls /var/folders/ls/cwyxr83n79161sgg0y7vq2k40000gn/T//RtmpSvguNA/file106137c71793
/var/folders/ls/cwyxr83n79161sgg0y7vq2k40000gn/T//RtmpSvguNA/file106137c71793
% ls /var/folders/ls/cwyxr83n79161sgg0y7vq2k40000gn/T/RtmpSvguNA/file106137c71793
/var/folders/ls/cwyxr83n79161sgg0y7vq2k40000gn/T/RtmpSvguNA/file106137c71793
```

**Comment by kevinushey** [comment]
For reference, I believe the error is being emitted from here:

https://github.com/rstudio/rsconnect/blob/fc39351a9198b5dca1fd410240de78c392976983/R/http.R#L245

And this is the command that should be generating the file:

https://github.com/rstudio/rsconnect/blob/fc39351a9198b5dca1fd410240de78c392976983/R/http.R#L220-L227

This is pretty bizarre -- when I enable the debugger and step through the code, I see the output file generated; if I don't, then the file is not seen. The command looks like this:

> "curl -i -X GET  --header \"Date: Wed, 17 May 2017 17:32:52 GMT\" --header \"X-Auth-Token: <...>\" --header \"X-Auth-Signature: <...>" --header \"X-Content-Checksum: <...>\" --header Expect: --user-agent rsconnect/0.8 --silent --show-error -o '/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T//RtmpNXLc2w/file1239c47862c88' https://beta.rstudioconnect.com/__api__/applications?filter=account_id:40&filter=name:untitled&count=100&offset=0"

It's almost as though `curl` is returning immediately, even before the actual download / file write has finished?

**Comment by kevinushey** [comment]
Hmm, the issue seems to have resolved after updating the `rsconnect` package (at least, on my side).

**Comment by kevinushey** [comment]
Adding a `Sys.sleep()` after the `curl` call does seem to magically fix this, so perhaps that's needed there. However, I'm now seeing the response from Connect not having a 'Content-Length' field. Here are the headers:

```
 [1] "HTTP/1.1 200 OK"
 [2] "Cache-Control: no-cache, no-store, must-revalidate"
 [3] "Content-Type: application/json; charset=utf-8"
 [4] "Expires: 0"
 [5] "Pragma: no-cache"
 [6] "Server: RStudio Connect v1.5.0-5"
 [7] "Set-Cookie: ...
 [8] "Strict-Transport-Security: max-age=2592000"
 [9] "X-Content-Type-Options: nosniff"
[10] "X-Frame-Options: DENY"
[11] "Date: Wed, 17 May 2017 17:50:28 GMT"
[12] "Transfer-Encoding: chunked"

<... json content ...>
```

What would cause the lack of a `Content-Length` header here?

**Comment by jspiewak** [comment]
@rstudio/connect any idea about Kevin's question about `Content-Length`?

@kevinushey you may also want to test against shinyapps.io

**Comment by trestletech** [comment]
Confirmed that we're lacking this header on this one endpoint, though we have it on others. Weird.

Opened https://github.com/rstudio/connect/issues/6497

**Comment by aronatkins** [comment]
There is no `Content-Length` header because Connect is JSON-serializing its results directly onto the HTTP connection and the HTTP library has decided that the first blob of output is not the complete result. Therefore, it has fallen back to using `Transfer-Encoding: chunked`.

**Comment by aronatkins** [comment]
@trestletech This is not endpoint specific but size-of-output specific. We do not serialize the entire response in memory.

**Comment by aronatkins** [comment]
@kevinushey There is no guarantee that Connect will include a `Content-Length` header, but I feel like that is not relevant. From my testing, `curl` is fine with this; it writes its result to the indicated output file and that output file is available immediately.

Here is a simple test I've been using from the command-line (outside of R):
```
rm /tmp/testlist ; curl -i -X GET --header Expect: --user-agent rsconnect/0.8 --silent --show-error -u [local-credentials] http://localhost:3939/__api__/applications -o /tmp/testlist ; stat /tmp/testlist
```

**Comment by aronatkins** [comment]
@kevinushey Also note that the original source of @jspiewak's troubles were against shinyapps.io, not Connect.

**Comment by kevinushey** [comment]
The code that handles the HTTP response seems to expect the content length header to be present:

https://github.com/rstudio/rsconnect/blob/f5bea1cfb2ba9cf903f8a7dae450151979d1aafe/R/http.R#L41-L62

So either `rsconnect` needs to learn how to handle chunked HTTP responses, or somehow that endpoint has to be configured to deliver unchunked responses.

Or we just inform users on macOS that `"curl"` is unsupported.

**Comment by trestletech** [comment]
While it's philosophically pure for us to stream this data, it doesn't seem like it would be terribly resource intensive to just retain that data in memory and then write the response once we have the whole thing prepared for backwards compatibility.

Moving forward, it would be nice if rsconnect were able to remove its dependency on content length. It looks like it's just using it for that binary read call.

**Comment by jspiewak** [comment]
Connect & Content-Length aside, for the moment, is adding a `sleep` a reasonable fix and does the fix then work against shinyapps.io?

**Comment by kippandrew** [comment]
FWIW, We're also seeing a Content-Length header issue here:

```
> options(rsconnect.http = "curl") 
> library(rsconnect) 
> deployApp() 
Preparing to deploy application...DONE 
Uploading bundle for application: 38496... 
Error in readBin(conn, what = "raw", n = contentLength) : 
invalid 'n' argument
```

**Comment by jspiewak** [comment]
@kippandrew what version of `rsconnect` is that?

**Comment by kippandrew** [comment]
HEAD on master.

**Comment by jspiewak** [comment]
So is that upload going direct to S3? Which would be different than either shinyapps.io or Connect, in terms of response, and completely out of our control to have supply Content-Length if it is missing.

**Comment by kippandrew** [comment]
Correct. This could be considered a separate bug, but its probably related so I mentioned it here. `RCurl` (???!??!) doesn't support uploading files larger then 2GB, so we tried using `curl`, but that is failing because we don't seem to be getting a Content-Length back.

**Comment by jspiewak** [comment]
Agreed. I opened this bug when @ssinnott and I were testing > 2GB against S3 and saw this problem. I then re-tested without his `rsconnect` change to be sure of the issue.

So the upshot is that `rsconnect` does need to handle the absence of Content-Length.

**Comment by kippandrew** [comment]
I wonder why you're getting a different error then this user...

**Comment by jspiewak** [comment]
What platform was the user trying to upload from?

**Comment by kippandrew** [comment]
Windows 7.

**Comment by jspiewak** [comment]
Given what @kevinushey said about the alternative being that `curl` not be available on Mac, then that is likely the difference in behavior.

**Comment by kippandrew** [comment]
Probably. But its also probably the same underlying bug.

**Comment by trestletech** [comment]
@kevinushey this thread took a detour but I needed curl to work locally on my mac and confirmed that adding a Sys.sleep() in between the reading and writing of the curl file makes curl work again.

I also added an is.null check on contentLength thinking that might be necessary; not sure if it is.

**Comment by ssinnott** [comment]
@kevinushey this is working now for the user that reported this. I'm not sure if this issue detoured into other work. So close if you are satisfied.

**Comment by kevinushey** [comment]
Great! @trestletech can you confirm whether this works in your case as well?

**Comment by trestletech** [comment]
Just did a test deploy to RSC with http set to CURL from my mac and things look good!
