### ISSUE TITLE
Error building a package from Github

### ISSUE THREAD

**Issue by skranz** [rstudio/rsconnect#176]
I try to install a Shiny app on shinyapps.io which uses several packages from Github. Unfortunately, the build fails for install the Github package "shinyEvents", with the non-informative error message:
```
Error: Unhandled Exception: Child Task 400255602 failed: Error building image: Error building shinyEvents (2.2). Build exited with non-zero status: 1
```
(more detailed output below). Local installation of shinyEvents via devtools::install_github (version 1.12) works fine without problems. I have written shinyEvents myself, and could also try to remove the problem, but given the uninformative error message, I have no clue what could be the reason. Maybe it is not due to shinyEvents but generally a problem for Github packages, since shinyEvents is the first of several Github packages that are tried to install? Or is there are problem because there are too many packages, since the task log seems to end abruptly? The same problem appears on several other computers, since maybe around half a year. Earlier, installation on shinyapps.io worked without problems.

```
> deployApp(appName="RTutorTseTse")
Preparing to deploy application...DONE
Uploading bundle for application: 183033...DONE
Deploying bundle: 839076 for application: 183033 ...
Waiting for task: 400255598
  building: Processing bundle: 839076
  building: Parsing manifest
  building: Building image: 831172
  building: Fetching packages
  building: Building package: shinyEvents
################################ Begin Task Log ################################ 
[2017-05-24T12:13:00.421359039+0000] Installing R package: whisker (0.3-2)
* installing to library ‘/usr/local/lib/R/site-library’
* installing *binary* package ‘whisker’ ...
* DONE (whisker)

[many more CRAN packages installed, output ommited]

[2017-05-24T12:13:08.825001698+0000] Installing R package: memoise (1.1.0)
* installing to library ‘/usr/local/lib/R/site-library’
* installing *bina################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 400255602 failed: Error building image: Error building shinyEvents (2.2). Build exited with non-zero status: 1
```

**Comment by jspiewak** [comment]
The full log of failing to build `shinyEvents` is:

```
[2017-05-24T12:13:12.973323650+0000] Building R package: shinyEvents (2.2)
/mnt/packages/build /mnt
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘shinyEvents’ ...
** R
** inst
** preparing package for lazy loading
Error in library(shinyAce) : there is no package called ‘shinyAce’
Error : unable to load R code in package ‘shinyEvents’
ERROR: lazy loading failed for package ‘shinyEvents’
* removing ‘/usr/local/lib/R/site-library/shinyEvents’
```

Looks like `shinyEvents` has a dependency upon `shinyAce` that is not declared in its `DESCRIPTION` file.

**Comment by skranz** [comment]
Great, thanks a lot for the info. I adapted the shinyEvents package and uploading to shinyapps.io now worked. 

Is there perhaps a way to generally make the full install logs available? I think this would generally be quite helpful for debugging purposes.

**Comment by billmabe** [comment]
+1: "Is there perhaps a way to generally make the full install logs available? I think this would generally be quite helpful for debugging purposes."

Any work on this? Thanks!

**Comment by SangdonLim** [comment]
For anyone struggling to figure out something like this, use `rsconnect::taskLog(taskId)` to retrieve the build logs for the task. For the case above, `taskId` is displayed on the 5th line of the text box. You can also use `rsconnect::tasks()` to retrieve the list of recent serverside tasks.
