### ISSUE TITLE
RCurl doesn't respect system certificate store

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#178]
We ship our own set of CA certs with rsconnect, and [use them when publishing with RCurl](
https://github.com/rstudio/rsconnect/blob/4a342a429cc7fdcb585a26186d5d013b35ce9f6e/R/http.R#L291). This is necessary because not all systems have the root CA needed to trust `shinyapps.io`; specifying our own set of certificates ensures that publishing to our cloud services will always work.

However, this option doesn't add to the system list of certificates -- it replaces it, as documented in [CURLOPT_CAINFO](https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html). Consequently, if customers want to supply a cert to be used with rsconnect--for instance, a self-signed certificate for a local RStudio Connect server--it isn't possible to do so elegantly; instead, it is necessary to individually update the PEM files per user, per R version, [as documented on our support page](https://support.rstudio.com/hc/en-us/articles/115006524187).

We should respect both the system cert store *and* our own internal set of certs, so that customers can add their own certificates. Alternately, if this is infeasible, we should use an R option or environment variable to allow customers to add a cert store to our list.

**Comment by JsizzleR** [comment]
Adding two recent tickets forwarded to the support page for trusting their self-signed cert:

https://rstudioide.zendesk.com/agent/tickets/21647
https://rstudioide.zendesk.com/agent/tickets/21484

**Comment by slopp** [comment]
In addition, feedback from Micron that it is annoying to have the rsconnect package over-ride the certs on update or reinstall. So it may be helpful to also consider storing certs in the deployment record instead of in the package. For shinyapps.io deployments, the cert could be copied from the package.

**Comment by jmcphers** [comment]
Yes, I'm imagining that we would want to support something per server to minimize the amount of certificate trust. For example:

- a server's SSL certificate could be stored with its name and URL in the config directory
- a command similar to addServer could be used to add a certificate to a server
- the RStudio IDE could have an "Edit Certificates..." button in the Publish Options which made it as painless as possible to add a self-signed cert to use when publishing to an account

However all of this requires us augmenting the system certificate store as discussed above (we'll probably have to do this by creating a temporary, concatenated PEM that combines the system store with whatever additional certs are required per account).

**Comment by jmcphers** [comment]
Work on this has started:

https://github.com/rstudio/rsconnect/tree/feature/server-certificates

**Comment by slopp** [comment]
@jmcphers Micron asked about this today, still WIP ?

**Comment by jmcphers** [comment]
Still WIP. The branch does work now, but hasn't been thoroughly tested.
