### ISSUE TITLE
could not find function "startsWith"

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#180]
With latest development version (0.8.1), and R version 3.1.2, deploy causes this error:

```
Uploading bundle for application: 14223...Error in `[.data.frame`(cookies, startsWith(requestURL$path, cookies$path),  : 
  could not find function "startsWith"
```

The error makes sense with that version of R (since according to: https://cran.r-project.org/doc/manuals/r-release/NEWS.html  
`startsWith` function was added in R 3.3.0. )

Will 3.3.0 be the minimum R version?

**Comment by jmcphers** [comment]
I think this was unintentional. @trestletech?
