### ISSUE TITLE
http::readHttpResponse doesn't work with responses without a content-length header

### ISSUE THREAD

**Issue by ssinnott** [rstudio/rsconnect#183]
The http::readHttpResponse method doesn't work when using "Transfer-Encoding: chunked" and no "Content-length" header. The response that come back from AWS when uploading item's to buckets is missing the content length header,

[1] "x-amz-request-id: [stuff]"
[1] "x-amz-id-2: [other stuff]"
[1] "Content-Type: application/xml"
[1] "Transfer-Encoding: chunked"
[1] "Date: Mon, 05 Jun 2017 21:39:47 GMT"
[1] "Connection: close"
[1] "Server: AmazonS3"

The exception message is,

```
 Error in readBin(conn, what = "raw", n = contentLength) : 
  invalid 'n' argument 
```

It's being sent from here,

https://github.com/rstudio/rsconnect/blob/fc39351a9198b5dca1fd410240de78c392976983/R/http.R#L62

When the value for content-length is NULL,

https://github.com/rstudio/rsconnect/blob/fc39351a9198b5dca1fd410240de78c392976983/R/http.R#L42

The same underlying issue was mentioned in https://github.com/rstudio/rsconnect/issues/174 in relation to connect. There's a zendesk ticket concerning a user experiencing similar issues (https://rstudioide.zendesk.com/agent/tickets/20785).

**Comment by ssinnott** [comment]
End user has confirmed it's now working. Fixed with merge https://github.com/rstudio/rsconnect/commit/887c22054e43432fa87665152398ccea1c1d2773

**Comment by jmcphers** [comment]
Thanks @ssinnott!
