### ISSUE TITLE
Output object can't share the same name (with different capitalization) with file in app folder 

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rsconnect#201]
This issue is related to https://github.com/rstudio/rsconnect/blob/5565386d2de92f50cc3c8b4a56f0146d88609ec0/R/linters.R#L136.

Here is a MWE Shiny app:

```r
library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(),
    mainPanel( 
      textOutput(outputId = "description") 
    )
  )
)

server <- function(input, output) {
  output$description <- renderText({ "hello" })
}

shinyApp(ui = ui, server = server)
```

In the same folder as this `app.R` file is also a `DESCRIPTION` file, where the name of the file is in capital letters.

The app runs fine locally, however when deploying to shinyapps.io I get the warning `"Filepaths are case-sensitive on deployment server"`. And it points to the line with `      textOutput(outputId = "description")`.

Changing the name of the output to something other than description, or writing it in all capital letters to match the filename gets rid of the issue, but neither of these seem ideal.

**Comment by rmccombie** [comment]
Additional vote: https://rstudioide.zendesk.com/agent/tickets/47848

**Comment by kevinushey** [comment]
Perhaps a simple fix would be to only include strings that include at least one slash in the linter?

For future reference, the lint rule is here: https://github.com/rstudio/rsconnect/blob/40c162bf3c4cd9b10deed82e1df9ec1b0c107c1f/R/linters.R#L40-L123

**Comment by hadley** [comment]
Closely related to #611

**Comment by hadley** [comment]
And now tracking there.
