### ISSUE TITLE
rsconnect 0.8.5: cannot deployApp due to an error in serverInfo

### ISSUE THREAD

**Issue by yihengli** [rstudio/rsconnect#202]
## Error Messge:
``` r
Error in serverInfo(server) : 
  name must be a single element character vector
```

## Code:
``` r
library(rsconnect)
rsconnect::setAccountInfo(name='name', token='token', secret='secret')
deployApp('path',appName = 'name',account = 'account')
```

## Comment:
This error only occurs in 0.8.5, tested in 0.8 and 0.7 and there were working without any problems.

## Environment:
- Mac OS 10.12.6
- R version 3.3.2
- PKI 0.1 - 3

**Comment by jmcphers** [comment]
Thanks for reporting! Unfortunately we couldn't reproduce this. A little more information might help:

1) Did the app being deployed have an `rsconnect` folder? (and if so, could you attach its contents?)

2) Does this happen for a brand new app? (i.e. one that doesn't have an `rsconnect` folder)?

**Comment by yihengli** [comment]
Hi @jmcphers Thanks for your quick turnaround. 
1. Yes, I tested some apps that have `rsconnect` folder
2. Yes, I also tested a brand new app to an unused app-name

I had several more tests, it seems like what triggered the issue is `appName` in `deployApp`
If I removed this param, 0.8.5 worked. What strange is that the same `appName` worked without issues in any versions before.

**Comment by jmcphers** [comment]
Thank you, that's very helpful. I've just pushed a candidate fix (not on master yet). In the meantime, you should be able to work around the problem by supplying a `server` as part of your `deployApp` command (let us know if that doesn't get you running!)
