### ISSUE TITLE
Connect does not support RPostgreSQL

### ISSUE THREAD

**Issue by MiksLynx** [rstudio/rsconnect#205]
Hi, I was not able to deploy Markdown document containing connection to Postgres database.
Here is the output from logs that I got

2017/09/18 15:19:25.583284932 Error: Command failed (1)
2017/09/18 15:19:25.583292341 
2017/09/18 15:19:25.583307528 Failed to run system command:
2017/09/18 15:19:25.583308370 
2017/09/18 15:19:25.583312452 	'/usr/lib64/R/bin/R' --vanilla CMD INSTALL '/tmp/RtmpbEgXUQ/RPostgreSQL' --library='/opt/rstudio-connect/mnt/app/packrat/lib/x86_64-redhat-linux-gnu/3.3.2' --install-tests --no-docs --no-multiarch --no-demo 
2017/09/18 15:19:25.583319499 
2017/09/18 15:19:25.583323815 The command failed with output:
2017/09/18 15:19:25.583324376 * installing *source* package 'RPostgreSQL' ...
2017/09/18 15:19:25.583328725 ** package 'RPostgreSQL' successfully unpacked and MD5 sums checked
2017/09/18 15:19:25.583329706 checking for gcc... gcc
2017/09/18 15:19:25.583333596 checking for C compiler default output file name... a.out
2017/09/18 15:19:25.583334530 checking whether the C compiler works... yes
2017/09/18 15:19:25.583338573 checking whether we are cross compiling... no
2017/09/18 15:19:25.583339307 checking for suffix of executables... 
2017/09/18 15:19:25.583343179 checking for suffix of object files... o
2017/09/18 15:19:25.583343815 checking whether we are using the GNU C compiler... yes
2017/09/18 15:19:25.583347482 checking whether gcc accepts -g... yes
2017/09/18 15:19:25.583348146 checking for gcc option to accept ISO C89... none needed
2017/09/18 15:19:25.583353415 checking build system type... x86_64-unknown-linux-gnu
2017/09/18 15:19:25.583354057 checking host system type... x86_64-unknown-linux-gnu
2017/09/18 15:19:25.583357884 checking target system type... x86_64-unknown-linux-gnu
2017/09/18 15:19:25.583358566 checking for pg_config... no
2017/09/18 15:19:25.583362303 configure: checking for PostgreSQL header files
2017/09/18 15:19:25.583362915 configure: Checking include /usr/include.
2017/09/18 15:19:25.583366635 configure: Checking include /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include.
2017/09/18 15:19:25.583371195 configure: Checking include /usr/include/pgsql.
2017/09/18 15:19:25.583375179 configure: Checking include /usr/include/postgresql.
2017/09/18 15:19:25.583375756 configure: Checking include /usr/local/include.
2017/09/18 15:19:25.583379481 configure: Checking include /usr/local/include/pgsql.
2017/09/18 15:19:25.583380210 configure: Checking include /usr/local/include/postgresql.
2017/09/18 15:19:25.583385250 configure: Checking include /usr/local/pgsql/include.
2017/09/18 15:19:25.583385887 configure: Checking include /usr/local/postgresql/include.
2017/09/18 15:19:25.583393772 configure: Checking include /opt/include.
2017/09/18 15:19:25.583394457 configure: Checking include /opt/include/pgsql.
2017/09/18 15:19:25.583398211 configure: Checking include /opt/include/postgresql.
2017/09/18 15:19:25.583398844 configure: Checking include /opt/local/include.
2017/09/18 15:19:25.583402490 configure: Checking include /opt/local/include/postgresql.
2017/09/18 15:19:25.583403206 configure: Checking include /sw/include/postgresql.
2017/09/18 15:19:25.583408358 configure: Checking lib /usr/lib.
2017/09/18 15:19:25.583409061 configure: Checking lib /usr/lib/pgsql.
2017/09/18 15:19:25.583413962 configure: Checking lib /usr/lib/postgresql.
2017/09/18 15:19:25.583415165 configure: Checking lib /usr/local/lib.
2017/09/18 15:19:25.583418779 configure: Checking lib /usr/local/lib/pgsql.
2017/09/18 15:19:25.583419417 configure: Checking lib /usr/local/lib/postgresql.
2017/09/18 15:19:25.583422919 configure: Checking lib /usr/local/pgsql/lib.
2017/09/18 15:19:25.583423535 configure: Checking lib /usr/local/postgresql/lib.
2017/09/18 15:19:25.583427165 configure: Checking lib /opt/lib.
2017/09/18 15:19:25.583431017 configure: Checking lib /opt/lib/pgsql.
2017/09/18 15:19:25.583434729 configure: Checking lib /opt/lib/postgresql.
2017/09/18 15:19:25.583435299 configure: Checking lib /opt/local/lib.
2017/09/18 15:19:25.583438907 configure: Checking lib /opt/local/lib/postgresql.
2017/09/18 15:19:25.583439491 configure: Checking lib /sw/lib.
2017/09/18 15:19:25.583443067 configure: Using internal package libpq-fe.h
2017/09/18 15:19:25.583443620 checking for "src/libpq/libpq-fe.h"... yes
2017/09/18 15:19:25.583447449 configure: creating ./config.status
2017/09/18 15:19:25.583448057 config.status: creating src/Makevars
2017/09/18 15:19:25.583451573 ** libs
2017/09/18 15:19:25.583452342 gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -Isrc/libpq -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RS-DBI.c -o RS-DBI.o
2017/09/18 15:19:25.583460404 gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -Isrc/libpq -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RS-PQescape.c -o RS-PQescape.o
2017/09/18 15:19:25.583461099 gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -Isrc/libpq -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RS-PostgreSQL.c -o RS-PostgreSQL.o
2017/09/18 15:19:25.583464765 gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -Isrc/libpq -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RS-pgsql-copy.c -o RS-pgsql-copy.o
2017/09/18 15:19:25.583465363 In file included from RS-PQescape.c:7:0:
2017/09/18 15:19:25.583468920 RS-PostgreSQL.h:23:26: fatal error: libpq-fe.h: No such file or directory
2017/09/18 15:19:25.583469515  #    include "libpq-fe.h"
2017/09/18 15:19:25.583473222                           ^
2017/09/18 15:19:25.583473823 compilation terminated.
2017/09/18 15:19:25.583477459 In file included from RS-PostgreSQL.c:17:0:
2017/09/18 15:19:25.583478065 RS-PostgreSQL.h:23:26: fatal error: libpq-fe.h: No such file or directory
2017/09/18 15:19:25.583481780  #    include "libpq-fe.h"
2017/09/18 15:19:25.583482321                           ^
2017/09/18 15:19:25.583485798 compilation terminated.
2017/09/18 15:19:25.583486363 In file included from RS-pgsql-copy.c:7:0:
2017/09/18 15:19:25.583489883 RS-PostgreSQL.h:23:26: fatal error: libpq-fe.h: No such file or directory
2017/09/18 15:19:25.583490481  #    include "libpq-fe.h"
2017/09/18 15:19:25.583494059                           ^
2017/09/18 15:19:25.583494613 compilation terminated.
2017/09/18 15:19:25.583499779 make: *** [RS-PQescape.o] Error 1
2017/09/18 15:19:25.583500502 make: *** Waiting for unfinished jobs....
2017/09/18 15:19:25.583504275 make: *** [RS-PostgreSQL.o] Error 1
2017/09/18 15:19:25.583504818 make: *** [RS-pgsql-copy.o] Error 1
2017/09/18 15:19:25.583510290 ERROR: compilation failed for package 'RPostgreSQL'
2017/09/18 15:19:25.583510924 * removing '/opt/rstudio-connect/mnt/app/packrat/lib/x86_64-redhat-linux-gnu/3.3.2/RPostgreSQL'
2017/09/18 15:19:25.583516330 
2017/09/18 15:19:25.583516921 Unable to fully restore the R packages associated with this deployment.
2017/09/18 15:19:25.583520426 Please review the preceding messages to determine which package
2017/09/18 15:19:25.583521005 encountered installation difficulty and the cause of the failure.
2017/09/18 15:19:25.583524642 
2017/09/18 15:19:25.583525180 Some typical reasons for package installation failures:
2017/09/18 15:19:25.583528915   * A system library needed by the R package is not installed.
2017/09/18 15:19:25.583529496     Some of the most common package dependencies are cataloged at:
2017/09/18 15:19:25.583533041     https://github.com/rstudio/shinyapps-package-dependencies
2017/09/18 15:19:25.583533663 
2017/09/18 15:19:25.583537244   * The R package requires a newer version of R.
2017/09/18 15:19:25.583541606 
2017/09/18 15:19:25.583547485   * The C/C++ compiler is outdated. This is often true for packages
2017/09/18 15:19:25.583548089     needing C++11 features.
2017/09/18 15:19:25.583554235 
2017/09/18 15:19:25.583554816   * The R package is Windows-only or otherwise unavailable for this
2017/09/18 15:19:25.583559013     operating system.
2017/09/18 15:19:25.583559576 
2017/09/18 15:19:25.583563050   * The package is housed in a private repository that requires
2017/09/18 15:19:25.583563617     authentication to access. For more details on this, see:
2017/09/18 15:19:25.583567301     http://docs.rstudio.com/connect/admin/process-management.html#private-packages
2017/09/18 15:19:25.583567971 
2017/09/18 15:19:25.583571497 The package description and documentation will list system requirements
2017/09/18 15:19:25.583572084 and restrictions.
2017/09/18 15:19:25.583576003 
2017/09/18 15:19:25.583576564 Please contact your RStudio Connect administrator for further help
2017/09/18 15:19:25.583581496 resolving this issue.
2017/09/18 15:19:25.765921671 Warning message:
2017/09/18 15:19:25.768905241 In packrat::restore(overwrite.dirty = TRUE, prompt = FALSE, restart = FALSE) :
2017/09/18 15:19:25.768910881   The most recent snapshot was generated using R version 3.3.3

I took a look at the package description and it is stated that:

> In order to build and install this package from source, 'PostgreSQL' itself must be present your system to provide 'PostgreSQL' functionality via its libraries and header files.

I suspect that this is the cause of issue.
Is this problem fixable or is it planned to add support for database drivers out of the box?

P.S. Sorry for bad formatting but making log file appear as code does not make it better :(

**Comment by MiksLynx** [comment]
I installed pg drivers and restarted server. That solved the issue.

**Comment by phoenixAja** [comment]
Hi I am having the same issue as you. Did you install the postgres drivers on the server housing r studio connect?

**Comment by MiksLynx** [comment]
Yes, install this driver https://odbc.postgresql.org/ on the server and restart it.

**Comment by XiaoruiZhu** [comment]
can also do 
`sudo apt update`
`sudo apt install postgresql postgresql-contrib`
