### ISSUE TITLE
deploy error: Error: unexpected '=' in "{

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rsconnect#209]
Using RStudio Version 1.1.331, when I click on the deploy button (to shinyapps), I get the following error:
```
Error: unexpected '=' in "{ options(repos = c(CRAN = 'https://cran.rstudio.com/', jr-packages ="
Execution halted
```
If I change
```
R> options("repos")
$repos
                                 CRAN                           jr-packages 
          "https://cran.rstudio.com/" "https://jr-packages.github.io/drat/" 
```
to
```
R> options("repos")
$repos
                       CRAN 
"https://cran.rstudio.com/" 
```
deploy now works.

Note, using

```{r}
rsconnect::deployApp(account = "jumpingrivers", appName = "mcapp", server = "shinyapps.io")
```
works regardless of the repo value

**Comment by kevinushey** [comment]
Thanks; I've filed this issue on the IDE side.

In your case, is it sufficient to just rename the repository name (to e.g. `jrpackages`)?

**Comment by csgillespie** [comment]
`jrpackages` and `jr_packages` both work. 

But `jr-packages` breaks the IDE.

**Comment by jmcphers** [comment]
Fixed in RStudio with https://github.com/rstudio/rstudio/issues/4324.
