### ISSUE TITLE
server records are per-host not per-host:port

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#211]
If two instances of Connect are accessible through the same server but different port, the server entry does not see those instances as distinct.

@dethmasque

**Comment by hadley** [comment]
6 years later, do you think this is still important?

**Comment by aronatkins** [comment]
It's an irritation, but probably only for the Connect development team. We occasionally test against hosts like:

* https://server:port/
* https://server:altport/basepath/

Depending on the test environment being tested, this may be the same underlying Connect instance, so this irritation doesn't really affect us.

Most of our development has shifted to using different hostnames for different instances, avoiding this problem.

This problem can also be avoided by using `rsconnect::addConnectServer` to give a specific name to an entry; I seem to remember that the problem only happens when using the "automatic" naming.

A similar, but different real-world use case is when a single proxy is used to front traffic to two Connect instances:

* https://proxy-host/staging-connect/
* https://proxy-host/production-connect/

I think this proxy case is more important than this same-host-different-port problem.
