### ISSUE TITLE
deployApp() doesn't work when directory name contains trailing slash

### ISSUE THREAD

**Issue by daattali** [rstudio/rsconnect#213]
On Windows using rsconnect 0.8.5

I tried deploying an app to shinyapps.io using `deployApp()` and passing the directory name as the first argument. Because I used tab-completion for the directory name, it appended a slash to the directory name. I get an error

'<path>\ does not exist'

I have to manually remove the slash from the end so get it working

**Comment by hadley** [comment]
We now call `normalizePath()` so I suspect this has been fixed. Please let me know if hasn't, and I'll reopen.
