### ISSUE TITLE
deployApp and appDependencies failing with non-informative error message

### ISSUE THREAD

**Issue by jspiewak** [rstudio/rsconnect#215]
A [customer is reporting](https://groups.google.com/d/msg/shinyapps-users/0t5u6ryPC40/4epHsPaqCQAJ) that rsconnect::deployApp() and
rsconnect::appDependencies() are failing with the message "Error in vapply(packages, function(pkg) { : values must be length 1, but FUN(X[[29]]) result is length 0".

**Comment by jmcphers** [comment]
We don't have a repro, or any other reports in > 2 years, so closing this one.
