### ISSUE TITLE
Emit `X-Auth-Token` HTTP header in every request to RStudio Connect

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#216]
Currently, we include the `X-Auth-Token` HTTP header on authenticated requests to RStudio Connect. 

On some configurations, however, a proxy may use the `X-Auth-Token` header in order to determine whether a request needs to be authenticated by the proxy. Making a request that omits the header in the presence of such a proxy will result in the request being redirected to e.g. a login page. This causes our unauthenticated requests (such as those to `server_settings`) to fail.

To make it easier to configure proxies, we should include `X-Auth-Token` every HTTP request we make to RStudio Connect servers, even those which are unauthenticated; we can use a dummy value such as `X-Auth-Token: none` to indicate that no auth token is present.

**Comment by scottmmjackson** [comment]
#217 fixed this.
