### ISSUE TITLE
Should we use `RCurl::base64Encode` vs. `base64enc::base64encode`?

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/rsconnect#219]
See: https://github.com/rstudio/rsconnect/blob/master/R/rsa.R#L10 and others

Both packages are available for use in `rsconnect`, because `base64enc` is a transitive dependency of `PKI`.

Should we be using the `base64enc` package for encoding things in base64? 

My instinct is that a single application ought not to use multiple implementations of the same algorithm if at all possible.

@duncantl notes in `omegahat/RCurl` -> `RCurl/base64.R`:

```
# There is some support for this in caTools but 
# that didn't install on some of my machines 
# and so we add it here since it is already available
# from libcurl and so is a natural facility in RCurl.
# I don't like duplicating functionality in other packages
# and discourage it. 
```

Ironically, this means that `generateToken()` calls `PKI.save.key` which calls `base64enc::base64encode` here: https://github.com/s-u/PKI/blob/bd7da17f207cd8a436811664e15a8cabe613cfe2/R/rsa.R#L86

And then immediately calls `RCurl::base64Encode` itself. It seems like we ought to be leaning on the same base64 encoder all the way down. However, if this code isn't robustly unit tested, maybe implementing those tests should be the first step before migrating encoders.

**Comment by jmcphers** [comment]
This is moot since we don't use RCurl any more. :-)
