### ISSUE TITLE
Deleting an application in shinyapps.io causes a 404 when re-deploying

### ISSUE THREAD

**Issue by jspiewak** [rstudio/rsconnect#226]
Once an application has been deployed, the dcf files stores the application id which is used for subsequent interactions. If the application is deleted via browser interaction, further rsconnect calls result in a 404 error because the application is no longer server side. The current work around is to manually delete the dcf file, usually after [having had to ask](https://groups.google.com/d/msg/shinyapps-users/tFCUEBj8hzg/sFZOmwloAwAJ) for [help in a forum](https://groups.google.com/d/msg/shinyapps-users/R6NMc9Ymf5E/IbTXjwlxBAAJ).

Consider handling 404 errors explicitly with a more informative message or actually removing the dcf file itself.

**Comment by jmcphers** [comment]
@adamconroy This might be an easy addition to metadata sync (i.e. whatever code you write which detects deleted apps and deletes their local records could be invoked prior to publish, too)

**Comment by jmcphers** [comment]
See also feedback in https://github.com/rstudio/rsconnect/issues/331.

**Comment by hadley** [comment]
Note to self:

```R
# look in stash for other changes

getApplicationForDeployment <- function(client, target) {
  tryCatch(
    client$getApplication(target$appId),
    rsconnect_http_404 = function(err) {
      applicationDeleted(client, target)
    }
  )
}

applicationDeleted = function(client, target, recordPath)
  header <- "Failed to find existing application on server; it's probably been deleted."
  not_interactive <- "Use {.fn forgetDeployment} to remove outdated record and try again."
  prompt <- "What do you want to do?"
  choices <- c(
    "Give up and try again later",
    "Delete existing deployment & create a new app"
  )

  cli_menu(header, prompt, choices, not_interactive = not_interactive, quit = 1)
  # Must be option 2
  
  path <- deploymentConfigFile(recordPath, target$appName, target$account, target$server)
  unlink(path)

  accountDetails <- accountInfo(target$account, target$server)
  client$createApplication(
    target$appName,
    target$appTitle,
    "shiny",
    accountDetails$accountId
  )
}
```
