### ISSUE TITLE
Support for R-Forge

### ISSUE THREAD

**Issue by marcianito** [rstudio/rsconnect#228]
As stated in several versions of shinyapps.io user guide, R packages hosted on R-Forge are so far not supported but are planned to be in the future.
I just wanted to get an idea of when this "future" might be? Are there more concrete plans and / or a schedule for that now? I checked the google usergroup but also no update their. Since I don't have a google account y just posed my question here..

Hoping to get positive news!
I can't deploy my app right now due to this dependency issue :(

Greetz!

**Comment by kippandrew** [comment]
Might give this a try:

https://github.com/rstudio/shinyapps-package-dependencies/issues/42

**Comment by marcianito** [comment]
@kippandrew Thanks for the tip! It looked a little better but in the end didn't work due to the similar error concerning package source.

**Comment by kippandrew** [comment]
Can you send along the packageDescription() for the package that failed?

**Comment by jmcphers** [comment]
Haven't heard back in a couple years so closing.
