### ISSUE TITLE
parseCookie needs to support cookie names that include dashes

### ISSUE THREAD

**Issue by slopp** [rstudio/rsconnect#229]
RSC Customer is having an issue with deployment in an HA context. Their cookie header is of the form:

"some-cookie-name=the.encrypted.ip; path=/; Httponly; Secure"

This header is not correctly parsed : https://github.com/rstudio/rsconnect/blob/12527eeb42bf3ed8ed35db17f9847d74f094898f/R/http.R#L108

**Comment by scottmmjackson** [comment]
I'll redo this regex to match the [cookie spec](https://curl.haxx.se/rfc/cookie_spec.html)

As stated by the spec, valid characters in a cookie are defined by the exclusion of certain characters. Technically cookie keys and values can have the `=` character in them, but from what I've heard it's usually safe to parse the first `=` as the delimiter.
