### ISSUE TITLE
deployApp fails and deletes "shinyapps" directory when application already deployed to shinyapps.io

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#23]
- Create a Shiny application and deploy to shinyapps.io (using "shinyapps" package)
- In my case the following directory and file is created:

```
shinyapps/fereshteh/rsconnect-bug-3-5.dcf
```
- Use a command like the following to deploy the app to a local Connect server:

```
rsconnect::deployApp(account="admin", server="localhost")
```
- This fails with error:

```
Uploading application bundle...
Error in digest::digest(file.path(appDir, file), algo = "md5", file = TRUE) : 
  The file does not exist: /var/folders/s_/8yg11xvd4037hgynq01b3hb80000gn/T//Rtmp0cfb1P/file9cd0ad6b965/shinyapps/fereshteh/rsconnect-bug-3-5.dcf
```
- Also, the shinyapps file listed above is now removed, and the following is created:

```
rsconnect/shinyapps.io/fereshteh/rsconnect-bug-3-5.dcf
```

I think some of this is expected, as we want to transition from "shinyapps" package to "rsconnect" package. But still it does not seem it is doing the right thing.
- Re-deploy using the same command will be successful.

**Comment by jmcphers** [comment]
Closing now that we've completed our shinyapps migration.
