### ISSUE TITLE
`deployAPI()` timeout error

### ISSUE THREAD

**Issue by rosseji** [rstudio/rsconnect#232]
```
Error: Unhandled Exception: Child Task 501986201 error: Unhandled Exception: Timeout waiting for '_check_container_alive' after 0:00:30
```
Same error when deploying and API via `deployAPI()` as #204. Isn't that an error suggesting its not a supported type?

@trestletech Any ideas?

Had success [previously](https://stackoverflow.com/questions/47878677/deploying-plumber-api-via-rsconnect-handler-not-found).

Occurs when deploying with:
- `R` 3.4.2,
- 3.4.3,
- `rsconnect` 8.5,
-  8.7.

``` r
sessionInfo()
#> R version 3.4.2 (2017-09-28)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Sierra 10.12.6
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] rsconnect_0.8.5  plumber_0.4.4 forcats_0.2.0   stringr_1.2.0   dplyr_0.7.4     purrr_0.2.4     
#> readr_1.1.1  tidyr_0.7.2     tibble_1.3.4    ggplot2_2.2.1   tidyverse_1.2.1
#>
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.4.2  backports_1.1.2 magrittr_1.5    rprojroot_1.3-1
#>  [5] tools_3.4.2     htmltools_0.3.6 yaml_2.1.16     Rcpp_0.12.14   
#>  [9] stringi_1.1.6   rmarkdown_1.8   knitr_1.17      stringr_1.2.0  
#> [13] digest_0.6.13   evaluate_0.10.1
```

``` r
sessionInfo()
#> R version 3.4.3 (2017-11-30)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Sierra 10.12.6
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] rsconnect_0.8.7 plumber_0.4.4   forcats_0.2.0   stringr_1.2.0   dplyr_0.7.4     purrr_0.2.4     #> readr_1.1.1     tidyr_0.7.2     tibble_1.4.1    ggplot2_2.2.1  
#> [11] tidyverse_1.2.1 devtools_1.13.4
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.4.3  backports_1.1.2 magrittr_1.5    rprojroot_1.3-1
#>  [5] tools_3.4.3     htmltools_0.3.6 yaml_2.1.16     Rcpp_0.12.14   
#>  [9] stringi_1.1.6   rmarkdown_1.8   knitr_1.17      stringr_1.2.0  
#> [13] digest_0.6.13   evaluate_0.10.1
```

**Comment by trestletech** [comment]
Do you have a lot of complex start up code outside of any endpoints in your API? You'll see that error if your API takes too long to become responsive. 

We're making this property configurable per app in the next RSC release in January. See `[Scheduler].InitTimeout` if you want to give your processes longer to startup. This section of the docs would be worth a read if that is what's going on here. http://docs.rstudio.com/connect/admin/appendix-configuration.html#appendix-configuration-scheduler

**Comment by jspiewak** [comment]
shinyapps.io does not currently support having API applications deployed to it.

**Comment by trestletech** [comment]
I believe he's on Connect, @jspiewak

**Comment by jspiewak** [comment]
@trestletech I was going by the first line of the issue with the error, which looks like shinyapps.io

**Comment by trestletech** [comment]
Oh, you're right. My bad.

**Comment by rosseji** [comment]
Thanks for the help. What is the intended destination for the `deployAPI()` function.

I have got it to work before, @trestletech  helped me with some issues, and it worked fine (Screen shot of deploy that wasn't finding the plumbed functions):
<img width="1440" alt="qa39g" src="https://user-images.githubusercontent.com/21113591/34447499-a47be392-ed38-11e7-8411-cabd5a3f9313.png">

**Comment by jspiewak** [comment]
Current supported destination of deployAPI is a Connect server.
deployAPI will deploy to shinyapps.io, but it is unsupported and may work to a greater or lesser degree than is desirable until full support is rolled out.

**Comment by jmcphers** [comment]
@jspiewak Should we specifically wall off deploying APIs to shinyapps.io for now?

**Comment by jmcphers** [comment]
We'll track that work in https://github.com/rstudio/rsconnect/issues/204.
