### ISSUE TITLE
Have option in deployApp so automatically updates application instead of asking

### ISSUE THREAD

**Issue by tingleyd** [rstudio/rsconnect#235]
I have a long list of apps that I loop over to deploy. However, each time it asks me 

Update application currently deployed at
*? [Y/n]

Where * is the location of my shinyapps.io.

Could there be an option where it would automatically select Y? Otherwise I have to do this 1 by 1 for over 100 shinyapps sites. 

thanks,

**Comment by jmcphers** [comment]
Implemented in https://github.com/rstudio/rsconnect/pull/236.

**Comment by alapo** [comment]
I know this was implemented in `deployApp`, would be great if it could also be done for `deployDoc`

**Comment by aronatkins** [comment]
@alapo - the `forceUpdate` argument is accepted by `deployDoc`.
