### ISSUE TITLE
allow LDAP groups to be used for content in RSC

### ISSUE THREAD

**Issue by reikoch** [rstudio/rsconnect#237]
It would be great if 
- sets of content objects

could be 
- access controlled via LDAP groups if available.

Managing sensitive content in intranets would become much easier for content administrators.

**Comment by trestletech** [comment]
HI. This repo is just used to manage the `rsconnect` package itself. It sounds like perhaps this is a feature request for RStudio Connect? If that's correct, do you mind sending in the request to `support@rstudio.com` and we'll be sure to log the feature request in the appropriate places?

Thanks!
