### ISSUE TITLE
Deploy with a vanity path (Rstudio connect)

### ISSUE THREAD

**Issue by pommedeterresautee** [rstudio/rsconnect#239]
I plan to push a landpage with links to some of our apps.
The only way to have an idea to what a link point to is to use a vanity path.
Is it possible to deploy with this information setup?
Or does it always require a manual intervention?

**Comment by trestletech** [comment]
Hi.  FYI, as an RStudio Connect customer I'd encourage you to send in requests to support@rstudio.com where we have folks devoted specifically to answering these questions. GitHub responses may be slower at times.

But this one's a quick answer, unfortunately: no we don't currently support that. We're looking at surfacing the API that Connect uses to be able to manage content and will consider supplementing the options that we expose via rsconnect in the coming months. But at this point it does require manual intervention.

**Comment by pommedeterresautee** [comment]
Thank you for these info, just to understand, I may ask for new features to the support?

**Comment by trestletech** [comment]
Yup! They have the appropriate channels to log requests and get them in front of the right folks there.
