### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by UOTLeop** [rstudio/rsconnect#243]
When I run the application on the local machine, the project works perfectly. However, when I try to deploy it to the shiny app.io. I just get the error message shown in the title without further explanation.
I can make sure that all the packages have been updated and there is no View function in my project. Could you please give me a hint for how to resolve this?

**Comment by jmcphers** [comment]
We think this issue is resolved in the latest version of the package (this was a common problem with certain proxies/empty responses). Let us know if you're still seeing it!
