### ISSUE TITLE
Incorrectly checks xpath and returns an error when publishing

### ISSUE THREAD

**Issue by bw4sz** [rstudio/rsconnect#244]
The local path checker is a bit overzealous and mistakes parsing of xml as the user trying to read in data. For example
I am interacting with a web API. I then need to do some parsing of the xml. 

```
 r<-wcPOST()
  start_epoch <- as.numeric(now() - lubridate::days(days_lag))
  
  #Get program number
  xpath <- paste("//data/deployment/argos/last_uplink_date", 
                 "[number() > number(", start_epoch, ")]/../program_number", sep = "")
  program_number <- XML::xpathSApply(XML::xmlParse(content(r,"text")), xpath, XML::xmlValue)
 ```
yields

<img width="1019" alt="screen shot 2018-02-12 at 10 25 23 am" src="https://user-images.githubusercontent.com/1208492/36113338-55c23316-0fe1-11e8-9c66-5a3c8558b2c1.png">

This all works great locally and hosted. Note there is no interaction with the local file system. But when I go to publish I get. "Paths should be to files within the project directory". I can force a 'yes' to override the check, but it could be improved.

Thanks.

**Comment by hadley** [comment]
Closely related to #611

**Comment by hadley** [comment]
Filter if the file exists.
