### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by hballinas** [rstudio/rsconnect#245]
Is there a way to use favicons in Shinyapps.io?  How?

**Comment by kippandrew** [comment]
Unfortunately favicons are not supported on shinyapps.io at this time. This is not the first time this has come up, so I will note your request on our internal backlog for tracking purposes.

**Comment by Tixierae** [comment]
any update on that?

**Comment by jumattern** [comment]
Yes please - we need favicons as well as secure URLs for custom domains!

**Comment by JosiahParry** [comment]
Adding another request for favicon support on ShinyApps.io

**Comment by howardbaek** [comment]
Hello, I was wondering if the request for favicon support on shinyapps.io has been processed yet?

**Comment by kendavidn** [comment]
Favicon support would be much appreciated! Hurts to have to ship an app without a favicon.

**Comment by heds1** [comment]
Adding my support for implementing favicons in shinyapps.io.

**Comment by md416** [comment]
FAVICONS?

**Comment by Christianlee19** [comment]
update?
