### ISSUE TITLE
Error when trying to use `showLogs()`: name must be a single element character vector

### ISSUE THREAD

**Issue by daattali** [rstudio/rsconnect#248]
I was trying to find examples of `showLogs()` to see logs of a broken app on shinyappsio and couldn't find any, and I seem to be doing something wrong.

I keep getting this error:

```
Error in serverInfo(server) : 
  name must be a single element character vector
```

This is the code I use:

```
rsconnect::showLogs(appPath = folder, appName = appname, account = myaccountname)
```

I tried different combinations of appPath/appName, perhaps setting one but not the other. I keep getting that error message.

---

```
> devtools::session_info()
Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.414)           
 language (EN)                        
 collate  English_Canada.1252         
 tz       America/New_York            
 date     2018-02-18                  

Packages ------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.3   2017-12-06 local         
 compiler    3.4.3   2017-12-06 local         
 datasets  * 3.4.3   2017-12-06 local         
 devtools    1.13.4  2017-11-09 CRAN (R 3.4.3)
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)
 graphics  * 3.4.3   2017-12-06 local         
 grDevices * 3.4.3   2017-12-06 local         
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.3)
 methods   * 3.4.3   2017-12-06 local         
 rsconnect   0.8.5   2017-08-23 CRAN (R 3.4.3)
 stats     * 3.4.3   2017-12-06 local         
 tools       3.4.3   2017-12-06 local         
 utils     * 3.4.3   2017-12-06 local         
 withr       2.1.1   2017-12-19 CRAN (R 3.4.3)
 yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)
```

**Comment by jspiewak** [comment]
What happens when you just call `showLogs()` with no parameters?
What are the contents of the `rsconnect` subdirectory of your application's root directory?

**Comment by daattali** [comment]
I apologize - running it now does seem to work when I specify `account` and `appPath`. I'm not sure what's different now than when I tried running before, I must have done something wrong, but it is working.

```
rsconnect::showLogs(account = accountname, appPath = path)
```

does work. I still get the same error if I try to add `appName` as well on top of the other two parameters (with `appName` being identical to `appPath` because I was running this command from the parent directory of where the app is) so I'm not too sure how to use `appName` and what that vague error means, but that's ok - `showLogs()` does work!
