### ISSUE TITLE
Single Rmd documents are not deployed correctly if not called index.Rmd

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#25]
Version 0.3.76
Deploying a test1.Rmd file in a directory of its own to Connect server causes error:

```
rmarkdown version: 0.5.3.1
knitr version: 1.8
Error in tools::file_path_as_absolute(input) : 
  file 'index.Rmd' does not exist
Calls: local ... eval -> <Anonymous> -> setwd -> dirname -> <Anonymous>
Execution halted
```

This happens even if I specify 'appPrimaryRmd="test1.Rmd"' in the deployApp command.

Note: If we have multiple Rmd files in the directory, and none are called "index.Rmd", deploy works fine and Connect shows a list of files.

**Comment by jmcphers** [comment]
I couldn't repro this. Could you provide a little more info?

1. Was this deployment made via the IDE, or the console?  If the latter, what R command did you use?
2. Can you paste the full deployment log from the console?

**Comment by fereshtehRS** [comment]
This could be a Connect issue, but since it was working for me with rsconnect 0.3.70, I thought the changes in rsconnect could have caused it.

From RStudio Console, using this command:
```
rsconnect::deployApp(server="localhost", account="fereshteh", appName="single-rmd-shiny-document", appPrimaryRmd="test1.Rmd")
```

Log:
```
Preparing to deploy application...DONE
Uploading application bundle...DONE
Deploying application: 12...
Deploying to R version '3.1.2' (Local version is '3.1.2')
Loading required package: packrat
Installing R6 (2.0.1) ... OK (symlinked cache)
Installing RJSONIO (1.3-0) ... OK (symlinked cache)
Installing Rcpp (0.11.3) ... OK (symlinked cache)
Installing bitops (1.0-6) ... OK (symlinked cache)
Installing digest (0.6.8) ... OK (symlinked cache)
Installing formatR (1.0) ... OK (symlinked cache)
Installing highr (0.4) ... OK (symlinked cache)
Installing mime (0.2) ... OK (symlinked cache)
Installing packrat (0.4.3) ... OK (symlinked cache)
Installing stringr (0.6.2) ... OK (symlinked cache)
Installing xtable (1.7-4) ... OK (symlinked cache)
Installing yaml (2.1.13) ... OK (symlinked cache)
Installing httpuv (1.3.2) ... OK (built source)
Installing caTools (1.17.1) ... OK (symlinked cache)
Installing htmltools (0.2.6) ... OK (symlinked cache)
Installing markdown (0.7.4) ... OK (symlinked cache)
Installing evaluate (0.5.5) ... OK (symlinked cache)
Installing shiny (0.11.1) ... OK (symlinked cache)
Installing knitr (1.8) ... OK (symlinked cache)
Installing rmarkdown (0.5.3.1) ... OK (symlinked cache)
Building report...
Using Packrat dir  /connect/apps/packrat/lib/x86_64-pc-linux-gnu/3.1.2 
R version: 3.1.2
rmarkdown version: 0.5.3.1
knitr version: 1.8
Error in tools::file_path_as_absolute(input) : 
  file 'index.Rmd' does not exist
Calls: local ... eval -> <Anonymous> -> setwd -> dirname -> <Anonymous>
Execution halted
Application deployment failed with error: exit status 1
```

manifest.json file has this line:
```
"primary_rmd" : "test1.Rmd"
```

I just noticed something else, not sure if it has any impact. The log above shows version of rmarkdown as 0.5.3.1 (the latest).
But Connect server after the error similar to above error, also shows this:
```
R version: 3.1.2
rmarkdown version: 0.5.1
knitr version: 1.8
Using Packrat dir  /connect/apps/packrat/lib/x86_64-pc-linux-gnu/3.1.2 
Error in tools::file_path_as_absolute(input) : 
  file 'index.Rmd' does not exist
Calls: local ... eval -> <Anonymous> -> setwd -> dirname -> <Anonymous>
Execution halted
```

and version of rmarkdown here is different.

**Comment by jmcphers** [comment]
Deployment and execution work fine on shinyapps--the error you're seeing is coming from connect and is probably a bug there. I presume by the `Building report` that this is a static Rmd?

**Comment by jcheng5** [comment]
For static Rmd, this is expected at this time--we have a Pivotal tracker item for this that isn't started yet.

If it worked before, maybe it was an early enough build that we were treating it as a Shiny Rmd?

**Comment by aronatkins** [comment]
This has been fixed; we support files of arbitrary names.
