### ISSUE TITLE
question on deploying

### ISSUE THREAD

**Issue by jwijffels** [rstudio/rsconnect#254]
If I have a RStudio Connect dev environment where some shiny/markdown/... apps are published. Is there a way to get the bundle of that app as an administrator such that the admin can publish this bundle to a another production server?

**Comment by aronatkins** [comment]
Bundle downloads are available through the "Source Versions" menu but the administrator must be a collaborator.

**Comment by jwijffels** [comment]
Thanks!

**Comment by slopp** [comment]
@jwijffels today it is not possible to directly redeploy a downloaded bundle, see: https://support.rstudio.com/hc/en-us/articles/115003639788-Bundle-Downloads

However, we do have an experimental utility to help with transferring content from one RSC server to another. Take a look at: https://github.com/slopp/connectApiUtils

**Comment by jwijffels** [comment]
Thanks for the links! Will have a look to the details of this implementation.
