### ISSUE TITLE
Feature Request: Static content - package repository

### ISSUE THREAD

**Issue by shapenaji** [rstudio/rsconnect#255]
per this:
https://support.rstudio.com/hc/en-us/articles/360001157793-Static-Content-on-RStudio-Connect

It now appears to be possible to serve arbitrary static content.

It would be nice to have support for deploying internal packages. Currently, we maintain our own package repo and serve it via nginx on a separate server. But if users could deploy an updated version of a package directly to rstudio connect from their IDE (EDIT: and we had some extra support to manage that repo) that would save a lot of time and energy.

Could probably also do this by deploying a plumber API that would manage the repo. But this seems like the connect team's design space.

**Comment by slopp** [comment]
Unfortunately there is quite a bit more work in hosting a CRAN compliant repository, so it is unlikely that Connect will support hosting R packages in a repository format. However, we are working on a new product, RStudio Package Manager, explicitly designed for this purpose! The tool is currently available as an alpha.

<img width="1510" alt="screen shot 2018-03-01 at 9 26 57 am" src="https://user-images.githubusercontent.com/15901072/36856241-c0c65684-1d32-11e8-97f5-cedb9d8a151e.png">



To get more information:

- Docs: http://docs.rstudio.com/rspm/admin
- Evaluation: https://rstudio.com/products/package-manager/evaluation
- Hosted Demo: http://demo.rstudiopm.com

If you'd like more information or want to try out the alpha and give us feedback, please shoot me an email: sean@rstudio.com

**Comment by jmcphers** [comment]
This problem is indeed fully addressed by the package manager!
