### ISSUE TITLE
Does not appear to be bundling app correctly

### ISSUE THREAD

**Issue by noamross** [rstudio/rsconnect#26]
I am attempting to deploy an app to shinyapps.io. I have tried this through both the IDE and with `deployApp()`. In both cases I get the same error.

```
Preparing to deploy application...DONE
Uploading application bundle...DONE
Deploying application: 34992...
Waiting for task: 17743086
  building: Parsing manifest
  building: Fetching packages
  building: Building package: V8
################################## Begin Log ################################## 
Error: You must register an account using setAccountInfo prior to proceeding.
In addition: Warning messages:
1: In FUN(c("rmarkdown", "rchie", "driver", "gspreadr", "magrittr",  :
  Package 'rchie' not available in repository or locally
2: In FUN(c("rmarkdown", "rchie", "driver", "gspreadr", "magrittr",  :
  Package 'driver' not available in repository or locally
3: In FUN(c("rmarkdown", "rchie", "driver", "gspreadr", "magrittr",  :
  Package 'gspreadr' not available in repository or locally
Execution halted
```

My account is registered and `accountInfo()` yields the correct information, including tokens and secrets.

Also, these are all github packages.  I have installed them through `devtools_install()` github and their DESCRIPTION files all have the appropriate github info.

When I look in my app directory, I find an `rsconnect` folder, but it is empty.

My app/package is at https://github.com/ropensci/rchie/tree/master/inst/shinyapp

**Comment by noamross** [comment]
I note that when I log in to my console, the app is there but undeployed.  If I attempt to rebuild it, it says there is no app bundle.

**Comment by jmcphers** [comment]
Thanks, we'll try to reproduce this. Where's the driver package on github?

**Comment by noamross** [comment]
```
install_github('noamross/rchie')
install_github('noamross/driver[@markdown-convert]')
install_github('jennybc/gspreadr')
```

`driver`'s actual home is `Ironholds/driver`, but I he hasn't accepted my PR yet. :)

**Comment by noamross** [comment]
I also note that this won't actually work in the end, anyway, because `rchie` depends on `V8`, which is on CRAN but has a system dependency of `libv8`, not available on the shinyapps.io instances.

**Comment by tareefk** [comment]
Noam, 
If you wouldn't mind putting in a pull request here:  https://github.com/rstudio/shinyapps-package-dependencies 
for the Ubuntu system dependencies that are needed by the packages that you are interested in getting installed.

**Comment by noamross** [comment]
Already done!
https://github.com/rstudio/shinyapps-package-dependencies/pull/13
