### ISSUE TITLE
Provide more informative error if the server argument is incorrectly specified to deployTFModel() and family

### ISSUE THREAD

**Issue by andrie** [rstudio/rsconnect#264]
When trying to deploy an TensorFlow model with an incorrectly specified `server` argument, I get an uninformative error message.

```r
rsconnect::deployTFModel(
  "saved_simple_iris",
  account = "andrie",
  server = "http://foo.compute.amazonaws.com"
)
```

I get:

```
Error: You must register an account using setAccountInfo prior to proceeding.
```

This is not informative, since the `server` argument should not contain the `http://` prefix

I think the desired behaviour is:

* Inspect the `server` argument
* Throw an informative message if the argument contains an `http://` or `https://` prefix.
* Also check for the `:3939` suffix, if that matters

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rsconnect/issues/107.
