### ISSUE TITLE
Expose more arguments in documentation of the "deploy" family of functions

### ISSUE THREAD

**Issue by andrie** [rstudio/rsconnect#265]
Some of the "deploy" family of functions have this signature:

```r
function(modelDir, ...)
```

where the dots are passed to `deployApp()`.

Some of these arguments are essential, so I think it makes sense to be more explicit. For example:

```r
function(modelDir, server, ...)
```

The `server` argument must always be supplied, so it will make the documentation easier to follow if the mandatory arguments are documented on every function in this family.

**Comment by jmcphers** [comment]
It shouldn't be required in all situations; if you have previously published `modelDir` to exactly one location, it's generally assumed that you're publishing there again (and you shouldn't need to specify any destination details at all). Is that not the behavior you're seeing?

**Comment by andrie** [comment]
Oh, I didn't make it that far.  I'm commenting on my experience as a first-time user, which was confusing.  I could only use this function because I found an example at https://tensorflow.rstudio.com/tools/tfdeploy/articles/introduction.html. I would not have been able to guess from the function documentation which argument to provide.
