### ISSUE TITLE
Allow deployment using API keys

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#269]
Right now, deploying content from RStudio to RStudio Connect requires setting up a token and associating it with a public/private key pair. It's secure, but it requires a lot of back-and-forth and several steps, including a sign-in to Connect from a browser window in the IDE which is surprisingly difficult in some customer installations.

This is a proposal to make it possible to set up Connect accounts which do not use public/private key signatures but instead use API keys (a concept Connect already supports). These are less secure all around but much more convenient to use, and we already use something very similar for authenticating to shinyapps.io. The proposed changes are as follows:

1. `connectUser` gains a new parameter, `apiKey`. If this parameter is specified, the API key is saved to the user's account information in lieu of a token and private key (hereafter TPK).
2. When signing HTTP requests, the HTTP methods will use the API key in lieu of the TPK if the account being used to deploy has an API key.
3. The `deployApp` method (and perhaps others that take an `account`) will accept an API key for its existing `account` parameter. If this parameter is formatted as an API key, then the API key will be used for deployment. This will make it possible to perform deployments without prior account setup.

When this work is complete, it is anticipated that some additional work will be needed in Connect to expose the account API keys, and in RStudio to make it easy to add an account using an API key as the authenticating mechanism in lieu of the TPK.

**Comment by colearendt** [comment]
This looks good.  Just for clarification:

- Connect exposes account API keys with a friendly UI (these are needed for authenticating to Plumber and Tensorflow APIs deployed on Connect)
- Should I add a related issue to the github.com/rstudio/rstudio repo for the UI improvements wrt adding an API key?
- I presume the API key will be saved in the `rsconnect:::accountsConfigDir()`?

**Comment by jmcphers** [comment]
> Should I add a related issue to the https://www.github.com/rstudio/rstudio/ repo for the UI improvements wrt adding an API key?

You're welcome to, or I will once the rsconnect changes are done.

> I presume the API key will be saved in the rsconnect:::accountsConfigDir()?

Yes!

**Comment by jmcphers** [comment]
This is implemented now.

**Comment by jeffkeller87** [comment]
Specifically, as a new function `connectApiUser` rather than as additional arguments to `connectUser` as was suggested earlier in this thread.

**Comment by muschellij2** [comment]
Is it possible to get the authorization header from the API key for `httr` from this?  Currently, I'm simply doing:
```r
rs_auth = function(api_key = NULL) {
  auth_hdr = NULL
  if (is.null(api_key)) {
    api_key = Sys.getenv("CONNECT_API_KEY")
  }
  if (nzchar(api_key) && !is.null(api_key)) {
    auth_hdr = httr::add_headers(
      Authorization = paste0("Key ", api_key))
  }
  auth_hdr
}
```
