### ISSUE TITLE
Simplify download-edit-redeploy workflow

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/rsconnect#270]
Right now, it's possible to download a bundle, edit it, and redeploy it to the same endpoint using the following steps:

1. Download the bundle using the Source Versions dialog and untar locally.
1. Edit and redeploy using:

```r
rsconnect::deployApp("content/path", server = "host", account = "username", appId = 1234)
```

Where `1234` is the ID of the downloaded app.

Things that make this less than awesome:

- Finding the app id is confusing. A downloaded bundle reads `app-<appId>-<bundleId>.tar.gz`. There is no cue distinguishing app ID from bundle ID other than position. 
    - The app ID is not included in the manifest; arguably it should not be, because the manifest identifies the content of the bundle and not the location where it is deployed.
- This workflow goes to a core collaboration use case that's likely to be repeated many times by many people with varying levels of familiarity with R, RStudio, Shiny/RMarkdown, and RStudio Connect. 
    - There might have to be IDE changes to get this to work as pleasantly as we'd like.

**Comment by scottmmjackson** [comment]
I'm not sure it does. FWIW I think we've come to a workaround, at least- documenting that collaboration requires duplicating the `rsconnect` folder from the first deployment.

**Comment by aronatkins** [comment]
Agree that Connect is not a source-control system. There is still a case for simpler "publish to existing content" when you don't have the original `rsconnect` deployment records.

**Comment by hadley** [comment]
We may also want to reconsider this logic: https://github.com/rstudio/rsconnect/blame/800a9eb27102812f6fb8e5e2878c7286b57c1f7f/R/deployApp.R#L338-L340. I'm pretty sure we want to always save the deployment record, even if you're updating someone else's content.

**Comment by hadley** [comment]
Probably makes sense to tackle at the same time as #677

**Comment by hadley** [comment]
And it occurs to me that the default `appName` should probably use `appPrimaryDoc` if set.  Currently if you're publishing a bunch of individual documents from a common directory, they'll all have the same default `appName`.
