### ISSUE TITLE
Replace RJSONIO with jsonlite

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#277]
Via `debian-r@lists.debian.org`: 

> in your package rsconnect you are using RJSONIO which has a non-free license(BSD + evil clause, see here[1]).  I discussed this previously with the author of googleVis who has managed to replace RJSONIO by jsonlite[2].

**Comment by jmcphers** [comment]
Note that the problem is not with 3-clause BSD itself but with the text "this software must be used for good, not evil" in the source code for the JSON parser. 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=712159#22

**Comment by scottmmjackson** [comment]
@hadley has brought this up as well.

I agree that we should migrate at some point.

**Comment by jeroen** [comment]
LMK if you need any help. The jsonlite versions of `toJSON` and `fromJSON` may have slightly different behavior than RJSONIO, but for simple lists they should be easy to replace.

Shiny uses these defaults: https://github.com/rstudio/shiny/blob/3bdd4af75c97074de9dab7765ffe8d91a9694aef/R/shiny.R#L129-L143

**Comment by jmcphers** [comment]
I got started on this here:

https://github.com/rstudio/rsconnect/commit/0ead3aca8f62f7709c6775dc3f98d5bf1f14b965

Everything went pretty smoothly; the main difference I encountered was that jsonlite won't serialize anything that has a class applied unless it explicitly has an S3 `asJSON` method, so I needed to `unclass` in a few spots so jsonlite would serialize the raw object.

The change works locally but results in bundles that don't publish to RStudio Connect for an unspecified reason (HTTP/500). I'll have to investigate before I can merge.

**Comment by kevinushey** [comment]
https://github.com/rstudio/shiny/issues/572 might be helpful to review as it discusses some of the default behaviors, their motivations and how they can be tweaked.

In particular @jeroen gives an RJSONIO -> jsonlite compatibility function as:

```R
# Compatibility mode
toJSON_compat <- function(x, ...){
  jsonlite::toJSON(x, dataframe="columns", null="null", na="null", auto_unbox=TRUE, ...)
}
```

Things may well have changed since 2014, though!

**Comment by jmcphers** [comment]
@kevinushey That helped quite a lot, thanks!
