### ISSUE TITLE
Error: Unable to retrieve package records for the following packages: - "grDevices", "graphics", "grid", "methods", "stats", "tools", "utils"

### ISSUE THREAD

**Issue by tbsund** [rstudio/rsconnect#278]
I am getting this error when I try to deploy my shiny app to shinyapps.io:

Error: Unable to retrieve package records for the following packages:
- "grDevices", "graphics", "grid", "methods", "stats", "tools", "utils"

These are all base packages so I can't use install.packages() for them, and the only libraries that are loaded in my shiny app are readxl, ggplot2, and reshape2 which are all CRAN packages.

**Comment by jspiewak** [comment]
Could you please include the full output of the deployment?
What is the output of `rsconnect::appDependencies()`?

**Comment by tbsund** [comment]
Here is the output of the deployment:

> rsconnect::deployApp('C:/Users/tsunderl/Desktop/folder')
Preparing to deploy application...DONE
Uploading bundle for application: 352639...Error: Unable to retrieve package records for the following packages:
- "grDevices", "graphics", "grid", "methods", "stats", "tools", "utils"
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Failed to infer source for package 'BH'; using latest available version on CRAN instead
2: In FUN(X[[i]], ...) : 
3: In FUN(X[[i]], ...) : 
4: In FUN(X[[i]], ...) : 
5: In FUN(X[[i]], ...) : 
6: In FUN(X[[i]], ...) : 
7: In FUN(X[[i]], ...) : 
8: In FUN(X[[i]], ...) : 

And here is the output of appDependencies:

> rsconnect::appDependencies('C:/Users/tsunderl/Desktop/folder')
Error: Unable to retrieve package records for the following packages:
- "grDevices", "graphics", "grid", "methods", "stats", "tools", "utils"
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Failed to infer source for package 'BH'; using latest available version on CRAN instead
2: In FUN(X[[i]], ...) : 
3: In FUN(X[[i]], ...) : 
4: In FUN(X[[i]], ...) : 
5: In FUN(X[[i]], ...) : 
6: In FUN(X[[i]], ...) : 
7: In FUN(X[[i]], ...) : 
8: In FUN(X[[i]], ...) : 


Thanks!!

**Comment by jspiewak** [comment]
And what files are in `'C:/Users/tsunderl/Desktop/folder'`?

**Comment by tbsund** [comment]
My program, app.R, is the only file in the folder

**Comment by jspiewak** [comment]
@jmcphers any suggestions for tracking this down further?

**Comment by kevinushey** [comment]
@tbsund, what is the output of:

```r
ip <- as.data.frame(installed.packages(), stringsAsFactors = FALSE)
ip[ip$Priority %in% "base", ]
```

**Comment by tbsund** [comment]
> ip <- as.data.frame(installed.packages(), stringsAsFactors = FALSE)
> ip[ip$Priority %in% "base", ]
 [1] Package               LibPath               Version               Priority              Depends               Imports              
 [7] LinkingTo             Suggests              Enhances              License               License_is_FOSS       License_restricts_use
[13] OS_type               Archs                 MD5sum                NeedsCompilation      Built                
<0 rows> (or 0-length row.names)

**Comment by kevinushey** [comment]
How did you install R? For some reason, R does not believe any of the installed packages have `"base"` priority. On my machine (with a CRAN binary of R on macOS) I see:

```
> ip <- as.data.frame(installed.packages(), stringsAsFactors = FALSE)
> ip[ip$Priority %in% "base", ]
            Package                                                        LibPath Version Priority Depends                    Imports LinkingTo                                 Suggests        Enhances         License License_is_FOSS
base           base /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                       <NA>      <NA>                                  methods            <NA> Part of R 3.5.0            <NA>
compiler   compiler /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                       <NA>      <NA>                                     <NA>            <NA> Part of R 3.5.0            <NA>
datasets   datasets /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                       <NA>      <NA>                                     <NA>            <NA> Part of R 3.5.0            <NA>
graphics   graphics /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                  grDevices      <NA>                                     <NA>            <NA> Part of R 3.5.0            <NA>
grDevices grDevices /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                       <NA>      <NA>                               KernSmooth            <NA> Part of R 3.5.0            <NA>
grid           grid /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>           grDevices, utils      <NA>                                  lattice            <NA> Part of R 3.5.0            <NA>
methods     methods /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>               utils, stats      <NA>                                codetools            <NA> Part of R 3.5.0            <NA>
parallel   parallel /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>            tools, compiler      <NA>                                  methods snow, nws, Rmpi Part of R 3.5.0            <NA>
splines     splines /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>            graphics, stats      <NA>                          Matrix, methods            <NA> Part of R 3.5.0            <NA>
stats         stats /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA> utils, grDevices, graphics      <NA> MASS, Matrix, SuppDists, methods, stats4            <NA> Part of R 3.5.0            <NA>
stats4       stats4 /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>   graphics, methods, stats      <NA>                                     <NA>            <NA> Part of R 3.5.0            <NA>
tcltk         tcltk /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                      utils      <NA>                                     <NA>            <NA> Part of R 3.5.0            <NA>
tools         tools /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                       <NA>      <NA>           codetools, methods, xml2, curl            <NA> Part of R 3.5.0            <NA>
utils         utils /Library/Frameworks/R.framework/Versions/3.5/Resources/library   3.5.0     base    <NA>                       <NA>      <NA>                methods, xml2, commonmark            <NA> Part of R 3.5.0            <NA>
          License_restricts_use OS_type MD5sum NeedsCompilation Built
base                       <NA>    <NA>   <NA>             <NA> 3.5.0
compiler                   <NA>    <NA>   <NA>             <NA> 3.5.0
datasets                   <NA>    <NA>   <NA>             <NA> 3.5.0
graphics                   <NA>    <NA>   <NA>              yes 3.5.0
grDevices                  <NA>    <NA>   <NA>              yes 3.5.0
grid                       <NA>    <NA>   <NA>              yes 3.5.0
methods                    <NA>    <NA>   <NA>              yes 3.5.0
parallel                   <NA>    <NA>   <NA>              yes 3.5.0
splines                    <NA>    <NA>   <NA>              yes 3.5.0
stats                      <NA>    <NA>   <NA>              yes 3.5.0
stats4                     <NA>    <NA>   <NA>             <NA> 3.5.0
tcltk                      <NA>    <NA>   <NA>              yes 3.5.0
tools                      <NA>    <NA>   <NA>              yes 3.5.0
utils                      <NA>    <NA>   <NA>              yes 3.5.0
```

**Comment by kevinushey** [comment]
This sounds very similar to https://github.com/rstudio/packrat/issues/381. Are you using Anaconda R? From what I can tell, they're shipping a broken version of R in some of their distributions.

**Comment by kevinushey** [comment]
I'd also be curious to see what the output of:

```r
tools:::.get_standard_package_names()
```

is. This sounds suspiciously similar to https://github.com/rstudio/packrat/issues/381.

**Comment by tbsund** [comment]
I downloaded it from the CRAN website. It is my work computer, so there's a chance it's a permissions issue. I'm the only R user in my office, so if you think the permissions is the issue, do you have any advice I could relay to IT to get it fixed? Everything, including my shiny app works fine on my computer, it is only deploying it that is an issue.

Her is that output:

> tools:::.get_standard_package_names()
$`base`
 [1] "base"      "tools"     "utils"     "grDevices" "graphics"  "stats"     "datasets"  "methods"   "grid"      "splines"   "stats4"   
[12] "tcltk"     "compiler"  "parallel" 

$recommended
 [1] "MASS"       "lattice"    "Matrix"     "nlme"       "survival"   "boot"       "cluster"    "codetools"  "foreign"    "KernSmooth"
[11] "rpart"      "class"      "nnet"       "spatial"    "mgcv"

**Comment by kevinushey** [comment]
Strange -- can you share the whole output of:

```r
install.packages()
```

The only thing I can initially guess is that R somehow lacks permissions to read some of the package metadata required when querying `install.packages()`...

**Comment by tbsund** [comment]
Are either of these what you meant? I feel like neither are very informative...

> install.packages()
Error in install.packages : argument "pkgs" is missing, with no default
> install.packages
function (...) 
.rs.callAs(name, hook, original, ...)
<environment: 0x00000000082a5c70>

**Comment by kevinushey** [comment]
Sorry, I meant `installed.packages()` -- I since edited the post to update but not fast enough!

**Comment by kevinushey** [comment]
That makes even less sense! What is the output of:

```r
.libPaths()
```

on your machine? Are you actually able to load any of those packages? Does `library(stats)` succeed for you?

**Comment by tbsund** [comment]
I edited the output a little just because I don't know much about stuff and didn't know if the network name is sensitive.

> .libPaths()
[1] "\\\\network.corp/Personal$/tsunderl/My Documents/R/win-library/3.5"
[2] "\\\\network.corp/Personal$/tsunderl/My Documents/R/R-3.5.0/library"

and library(stats) did not give any error messages, so I assume it succeeds!

**Comment by kevinushey** [comment]
Interesting. I can only guess that `installed.packages()` is failing to query the set of installed packages because your R libraries are located on a networked drive.

We could potentially work around this in Packrat.

**Comment by tbsund** [comment]
Okay! How?

Btw, thanks for all your help! :)

**Comment by kevinushey** [comment]
This will require some work on the Packrat side, so unfortunately there's nothing to be done on your side until we get those fixes in.

Can you by any chance provide the output of:

```r
list.files(.libPaths()[1])
```

**Comment by tbsund** [comment]
> list.files(.libPaths()[1])
 [1] "assertthat"      "base64enc"       "bitops"          "cellranger"      "cli"             "colorspace"      "crayon"         
 [8] "dichromat"       "digest"          "file1ed43486f49" "file614128c20b7" "filea04566c4702" "filed8c64675d8"  "ggplot2"        
[15] "glue"            "gtable"          "htmltools"       "httpuv"          "jsonlite"        "labeling"        "later"          
[22] "lattice"         "lazyeval"        "lme4"            "magrittr"        "MASS"            "Matrix"          "mime"           
[29] "minqa"           "munsell"         "nlme"            "nloptr"          "packrat"         "pillar"          "PKI"            
[36] "plyr"            "promises"        "R6"              "RColorBrewer"    "Rcpp"            "RcppEigen"       "RCurl"          
[43] "readxl"          "rematch"         "reshape2"        "RJSONIO"         "rlang"           "rsconnect"       "rstudioapi"     
[50] "scales"          "shiny"           "sourcetools"     "stringi"         "stringr"         "tibble"          "utf8"           
[57] "viridisLite"     "xtable"          "yaml"

**Comment by kevinushey** [comment]
Great! With that I should be able to get a workaround into Packrat.

**Comment by kevinushey** [comment]
I have a candidate fix in Packrat now. Can you try installing the development version with:

```r
if (!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("rstudio/packrat")
```

and let me know if you have any better luck with deployment?

**Comment by tbsund** [comment]
It worked!!! It made me load a billion libraries, but once I did it worked. THANK YOU!!

**Comment by kevinushey** [comment]
Awesome! I'm glad to hear it :-)

**Comment by TMax66** [comment]
HI, all 
meet an analogue problem when try to deploy my app
I get this message: 

```
Preparing to deploy application...DONE
Uploading bundle for application: 369321...Errore: 
* Application depends on package "MASS" but it is not installed.
   Please resolve before continuing.
```
any suggestion??
Massimo
Thanks

**Comment by kevinushey** [comment]
Can you confirm that an attempt to load the `MASS` package succeeds? E.g.

```
library(MASS)
```

In addition, what is the output of `find.package("MASS")`?

Does installing the latest version from CRAN with `install.packages("MASS")` help at all?

**Comment by TMax66** [comment]
Hi Kevin,
yes I I tried them all..no success!

**Comment by TMax66** [comment]
HI Kevin
I tried to  install again MASSand it seems that it works now....

thanks
Max

**Comment by jmcphers** [comment]
Fixed on the packrat side; no work to do in rsconnect.
