### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/rsconnect#280]
On the page http://docs.rstudio.com/connect/1.6.0/user/api-keys.html, it says:
"To access content with an API Key you must provide a HTTP header whose key is Authentication and value is Key THE_API_KEY."

However, the key "Authentication" does not work - instead it should be "Authorization" as noted in the curl statements further down the page.

**Comment by colearendt** [comment]
Thanks for the find / report!  I have moved this to the appropriate location for tracking and resolution, since this issue is with the RStudio Connect product guide and not with the `rsconnect` R package.  Much appreciated!

**Comment by aronatkins** [comment]
Closing this issue; the documentation fix will be in the next RStudio Connect release.
