### ISSUE TITLE
rsconnect does not recognize Connect server behind proxy without trailing `/`

### ISSUE THREAD

**Issue by colearendt** [rstudio/rsconnect#281]
At present, RStudio Connect is listening at `http://colorado.rstudio.com:3939`.  It is proxied at `http://colorado.rstudio.com/rsc` and redirects appropriately, by my testing.

Publishing to `http://colorado.rstudio.com/rsc/` works, but `http://colorado.rstudio.com/rsc` does not.  Is that rigor that we support, or is this something that should be fixed?

Ideally, we would be able to follow redirects from `http://colorado.rstudio.com/rsc` and arrive at the appropriate URL for publishing.

**Comment by jspiewak** [comment]
Isn't the nginx proxy sitting in front of Connect under your configuration control:

```
(lucid) serenity:~/work/rstudio/lucid -> curl -I http://colorado.rstudio.com/rsc
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Tue, 26 Jun 2018 16:58:39 GMT
Content-Type: text/html
Content-Length: 185
Location: http://colorado.rstudio.com/rsc/
Connection: keep-alive

(lucid) serenity:~/work/rstudio/lucid -> curl -I http://colorado.rstudio.com/rsc/
HTTP/1.1 307 Temporary Redirect
Server: nginx/1.12.2
Date: Tue, 26 Jun 2018 16:58:41 GMT
Content-Type: text/plain; charset=utf-8
Location: http://colorado.rstudio.com/rsc/connect/
Connection: keep-alive
Set-Cookie: rscid=MTUzMDAzMjMyMXxEdi1CQkFFQ180SUFBUkFCRUFBQV80TF9nZ0FEQm5OMGNtbHVad3dHQUFSSFZVbEVCbk4wY21sdVp3d21BQ1EyWmpkaE1ESmhaQzB4WXpWakxUUTROamt0WW1RMlppMHhaR05tTjJObU16RmxaV0VHYzNSeWFXNW5EQWtBQjJOeVpXRjBaV1FGYVc1ME5qUUVCZ0Q4dG1UaGdnWnpkSEpwYm1jTUNRQUhjbVZtY21WemFBVnBiblEyTkFRR0FQeTJaT0dDfD0VNKyME2ZL0D4kC9XEFTrb4G4edD5YEJx0WUVAx6wl; Path=/; Expires=Thu, 26 Jul 2018 16:58:41 GMT; Max-Age=2592000; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

**Comment by trestletech** [comment]
Yeah, I believe they could fix this by reconfiguring their proxy. But it still is interesting to note that for some reason we don't support this. I assume it's the multiple redirects that's the problem, but maybe it's 307 vs 301 or some other difference?

**Comment by colearendt** [comment]
That was partially my question - I definitely can configure the proxy - just wanted to see if this was functionality that could be improved at all or if it's all on the proxy configuration side.

**Comment by aronatkins** [comment]
Note that `/rsc/connect/` is actually the Connect dashboard URL, so the double redirect is fine.

http://colorado.rstudio.com/rsc/__api__/server_settings proves that `/rsc/` is the correct prefix.

**Comment by colearendt** [comment]
Not sure what you meant - I guess Connect prefers `/rsc/`?  Server config: 
```
[Server]
SenderEmail = noreply@rstudioconnect.com
Address = http://colorado.rstudio.com/rsc
RVersionScanning = false
```

**Comment by colearendt** [comment]
So... this was throwing an error about "not being able to find the Connect server"... but now it's not... 

Now I'm questioning my sanity.  Apologies for the waste of time 🤦‍♂️
