### ISSUE TITLE
I can't connect Account in Shiny, there is error

### ISSUE THREAD

**Issue by CHUN-INHYUK** [rstudio/rsconnect#284]
![default](https://user-images.githubusercontent.com/42229781/43884659-39dbc10c-9ba6-11e8-818d-9cfb022ddcc2.png)
When i clicked Publish to Server, and entered my Tokens, and clicked the Connect Account button, 
There was Error with "The command failed. you can set up an account manually by using rsconnect::setAccountInfo; ...."

So I did in R console, 
reconnect::setAccountInfo  

There is Error with
-----------------------------
*   Trying 34.199.157.130...
*   Trying 52.206.19.186...
* connect to 34.199.157.130 port 443 failed: Timed out
*   Trying 52.206.19.186...
* connect to 52.206.19.186 port 443 failed: Timed out
*   Trying 107.23.160.51...
* connect to 52.206.19.186 port 443 failed: Timed out
*   Trying 107.23.160.51...
* connect to 107.23.160.51 port 443 failed: Timed out
* Failed to connect to api.shinyapps.io port 443: Timed out
* Closing connection 0
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to api.shinyapps.io port 443: Timed out
Timing stopped at: 0 0.01 42.75
----------------------------------

I tried behind code
-----------------------------------------------
options(rsconnect.http.trace = TRUE)
options(rsconnect.http.verbose = TRUE)
options(rsconnect.http.trace.json = TRUE)
------------------------------------------------
but that wasn't effective

How can I? 
Please help me.

**Comment by jspiewak** [comment]
Do you have a firewall that is restricting access?

**Comment by CHUN-INHYUK** [comment]
Yes, and what can I?
What proxly could I unlock the restricting access?

**Comment by jspiewak** [comment]
If you are behind a firewall that is restricting your access, then you will need to work with whomever manages it to ensure that you can connect to both the shinyapps.io servers as well as Amazon's S3 service to which bundles are uploaded.

**Comment by jmcphers** [comment]
I don't think there's a bug in the package to fix here, so I'm closing this for now. If you're still blocked, try asking on https://community.rstudio.com/c/shiny.
