### ISSUE TITLE
I can't connect Account in shinyApps.io

### ISSUE THREAD

**Issue by CHUN-INHYUK** [rstudio/rsconnect#285]
![default](https://user-images.githubusercontent.com/42229781/43885553-bfa837e6-9ba8-11e8-8a90-f1006baf18ac.png)

 When i clicked Publish to Server, and entered my Tokens, and clicked the Connect Account button,
 There was Error with "The command failed. you can set up an account manually by using rsconnect::setAccountInfo; ...."

So I did in R console,
 reconnect::setAccountInfo

There is Error with
•Trying 34.199.157.130...
•Trying 52.206.19.186...
•connect to 34.199.157.130 port 443 failed: Timed out
•Trying 52.206.19.186...
•connect to 52.206.19.186 port 443 failed: Timed out
•Trying 107.23.160.51...
•connect to 52.206.19.186 port 443 failed: Timed out
•Trying 107.23.160.51...
•connect to 107.23.160.51 port 443 failed: Timed out
•Failed to connect to api.shinyapps.io port 443: Timed out
•Closing connection 0
 Error in function (type, msg, asError = TRUE) :
 Failed to connect to api.shinyapps.io port 443: Timed out
 Timing stopped at: 0 0.01 42.75

I tried behind code

options(rsconnect.http.trace = TRUE)
 options(rsconnect.http.verbose = TRUE)
 options(rsconnect.http.trace.json = TRUE)

but that wasn't effective

How can I?
 Please help me.

**Comment by jspiewak** [comment]
Duplicates #284

**Comment by nimeshpowalekar** [comment]
![shinyio connect error](https://user-images.githubusercontent.com/46514376/50879055-82967f00-13ff-11e9-9776-9c6170d06a82.png)

When i clicked Publish to Server, and entered my Tokens, and clicked the Connect Account button,
There was Error with "The command failed. you can set up an account manually by using rsconnect::setAccountInfo; ...."

So I did in R console,
reconnect::setAccountInfo

There is Error with
•Trying 34.199.157.130...
•Trying 52.206.19.186...
•connect to 34.199.157.130 port 443 failed: Timed out
•Trying 52.206.19.186...
•connect to 52.206.19.186 port 443 failed: Timed out
•Trying 107.23.160.51...
•connect to 52.206.19.186 port 443 failed: Timed out
•Trying 107.23.160.51...
•connect to 107.23.160.51 port 443 failed: Timed out
•Failed to connect to api.shinyapps.io port 443: Timed out
•Closing connection 0
Error in function (type, msg, asError = TRUE) :
Failed to connect to api.shinyapps.io port 443: Timed out
Timing stopped at: 0 0.01 42.75

I tried behind code

options(rsconnect.http.trace = TRUE)
options(rsconnect.http.verbose = TRUE)
options(rsconnect.http.trace.json = TRUE)

but that wasn't effective

How can I connect?
Please help me.

**Comment by jspiewak** [comment]
@nimeshpowalekar see the conversation in #284 and post to Community if you are still having trouble once you know more about a potential proxy between your computer and shinyapps.io
