### ISSUE TITLE
rsconnect::deploySite does not take title

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#296]
The `deploySite` function takes `siteName` that falls-back to the name from the site generator then passed as `appName` to `deployApp` where it may fall-back to the basename of the containing directory. It does not accept a free-form title (`siteTitle`, perhaps) that is subsequently passed to the `appTitle` argument of `deployApp`.

**Comment by jmcphers** [comment]
This isn't the only issue wherein we wanted to adjust the `deployApp` call made by `deploySite`. I've just added a passthrough for all parameters that aren't explicitly taken by `deploySite`, so you can now specify `appTitle` directly. 

https://github.com/rstudio/rsconnect/commit/9e5d01b685385570777e97c1999fae3412e16d92
