### ISSUE TITLE
Docker Deployment Pipeline

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/rsconnect#298]
I am looking to set up a deployment pipeline in which i used docker containers to restore a versioned app's environemnt via packrat and rocker and run the deployApp command to a specified rsconnect server within our network. (We dont have access to travis or jenkins or anything like that).

From my understanding to authenticate a machine you need to go through the rstudio process with popup to login to rsconnect via the browser. Although the server that i am running the docker containers on would be able to do that the docker containers themselves would not (nor would we want them too each time). 

I would've thought that i could have achieved this via a token secret pair but this does not look to be possible via #269 (yet). Are there any alternative courses of action i could take here to authenticate the docker containers?

**Comment by jmcphers** [comment]
In your case it's very possible to use the token secret pair, and not a great advantage in using API keys. Just set up a token secret pair once (as you would an API key), then copy the account information (which includes the token private key) into your Docker containers.

You can find the token secrets (and other account data) in the directory named by:

    > rsconnect:::accountsConfigDir()

Copying this folder into your container should do the trick.

If you have further questions, I'd suggest our community forum (this issue reporter is for bugs in the rsconnect package). 

https://community.rstudio.com/
