### ISSUE TITLE
log app-mode

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#30]
It would be nice to log the inferred app-mode when deploying. Right now, we always log:

```
Preparing to deploy application...DONE
```

Maybe this could distinguish between the different types:

```
Preparing to deploy a static RMarkdown document...DONE
Preparing to deploy a Shiny RMarkdown document...DONE
Preparing to deploy a Shiny application...DONE
Preparing to deploy static content...DONE
```

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rsconnect/commit/9e5d01b685385570777e97c1999fae3412e16d92.
