### ISSUE TITLE
Not able to set the proxyauth option when using rcurl.

### ISSUE THREAD

**Issue by ssinnott** [rstudio/rsconnect#315]
One our our customers is trying to use rsconnect through a NTLM proxy. There is option that needs to be passed into rcurl when it's evoked in order to tell rcurl that it needs to authenticate through the proxy. This setting can be toggled on an existing `rcurl` instance by doing something like the following,

`RCurl::curlSetOpt(.opts = list(proxyauth = RCurl::AUTH_NTLM), curl=rcurl)`

The issue is that there is no way to inject this particular option into a rsconnect call because it generates a new set of options for each call and requires additional options to be passed in as individual parameters on the function.

https://github.com/rstudio/rsconnect/blob/3fe3b4ba1f0ab4dca1d83619e0527bd7cfc5b40e/R/http.R#L511

Handling this in some more general way seem advisable. Right now there seem to be 172 parameters that could be set (`RCurl::listCurlOptions()`) so the current approach doesn't seem to scale well. 

A better approach might be to have a global option (maybe `rsconnect.rcurl.options`) that caller could set to add whatever parameters they needed to the call.

**Comment by cderv** [comment]
I think you can already do it using `RCurlOptions` option from RCurl. Something like :

```r
options(RCurlOptions = list(proxyauth = RCurl::AUTH_NTLM))
```

There is mention of that in [RCurl FAQ](http://www.omegahat.net/RCurl/FAQ.html)
> Note that users (not recommended for programmers) can set the R option named RCurlOptions via R's option() function. The value should be a list of named curl options. This is used in each RCurl request merging these values with those specified in the call. This allows one to provide default values. 

And an example in this 📦 
https://github.com/rstudio/rsconnect/blob/3fe3b4ba1f0ab4dca1d83619e0527bd7cfc5b40e/R/proxies.R#L29-L31
See
