### ISSUE TITLE
Switch from RCurl to curl

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#325]
rsconnect currently uses the RCurl package most of the time to perform HTTP operations. 

https://cran.r-project.org/web/packages/RCurl/index.html

We should consider switching to curl, which is what most of the tidyverse uses. 

https://cran.r-project.org/web/packages/curl/index.html

**Comment by jeroen** [comment]
This is quite important. The `RCurl` is unmaintained and on Windows it uses a very very old version of openssl which only supports legacy versions of TLS (https).

For this reason `rsconnect` users on Windows be unable to connect with Connect servers that use the latest HTTPS standards. Replacing `RCurl` with the `curl` package will resolve your HTTPS problems and probably fix many other random networking issues as well.

**Comment by jmcphers** [comment]
I've started working on this on a branch.

**Comment by jjallaire** [comment]
In case it wasn't obvious, you can add support for curl (and make it the
default) while still keeping the old code around just in case any users
rely on it. The package has multiple transports (curl binary, internal,
RCurl) so you can just add another transport and make it the default:
https://github.com/rstudio/rsconnect/blob/master/R/http.R

**Comment by jmcphers** [comment]
In recent versions of rsconnect, RCurl is no longer the default on Windows because of the issues @jeroen mentions above. We currently default to the `curl` command line utility on Windows instead (Windows 10 ships a competent one). 

https://github.com/rstudio/rsconnect/commit/ae203f870f241e7b1e5de35230b635be754785ee#diff-031bbb2044688f5cb946c89f3a3dbd15

Consequently I was planning on dropping RCurl entirely -- we'd still have the `rcurl` transport, but it would mean "the curl R package" rather than "the RCurl package". Anyone opposed?

**Comment by jjallaire** [comment]
Fine by me

**Comment by jeroen** [comment]
Be careful that shelling out is often unreliable. For example if there is some networking error (which is not unusual), the `curl` command line returns non-zero and may print something to the terminal, but the exception does not get propagated back to R. This makes it difficult for the user to understand or debug what is the problem.
