### ISSUE TITLE
Error: reticulate is in use, but python was not specified

### ISSUE THREAD

**Issue by yueqiw** [rstudio/rsconnect#330]
Hi,

I'm deploying an app and did not use reticulate, but got the following error. 
```
Error: * reticulate is in use, but python was not specified
Execution halted
```
And when I set the `RETICULATE_PYTHON` variable in `.Renvinron`, I got another error when deploying the app: 
```
Error: Unhandled Exception: Child Task 578481004 failed: Error parsing manifest: 
Schema validation failed: Additional properties are not allowed (u'python' was unexpected) at
```
Maybe one of the package in the app has dependency on reticulate, but I'm not really using any function that calls reticulate or Python. Is there a way to bypass it? Or how to resolve the "Schema validation failed" error?

**Comment by cderv** [comment]
For reference, the issue has also been report here
https://community.rstudio.com/t/error-deploying-app-from-rstudio-cloud-to-shinyapps-io-error-reticulate-is-in-use-but-python-was-not-specified/

> Maybe one of the package in the app has dependency on reticulate

I think you can get which dependencies are detected using [`rsconnect::appDependencies()`](https://www.rdocumentation.org/packages/rsconnect/versions/0.8.13/topics/appDependencies). You'll see that way if you have a dependency on reticulate.

**Comment by yueqiw** [comment]
@cderv Thanks!

I checked the dependencies and the package with reticulate dependency is needed for the app, although I'm not using any function that calls reticulate. So I cannot remove that package. 

How to resolve the issue and get the app deployed? Specifying python path to `deployApp()` gives the above error: `Error parsing manifest: Schema validation failed: Additional properties are not allowed (u'python' was unexpected)`.

**Comment by yueqiw** [comment]
It's been a week and I still couldn't get the App uploaded. Any help would be appreciated. @mmarchetti 

Below is the full error message 
case 1: when using the default python path: `Error detecting python for reticulate`
```
> deployApp(appName = "test_browser_2")
Preparing to deploy application...DONE
Uploading bundle for application: 652973...Error: 
* Error detecting python for reticulate: lexical error: invalid char in
   json text.  NA (right here) ------^
In addition: Warning message:
In system2(command = python, args = args, stdout = TRUE, stderr = NULL,  :
  running command ''/home/yueqi/anaconda/bin/python' '/home/yueqi/R/x86_64-pc-linux-gnu-library/3.5/rsconnect/resources/environment.py' '/tmp/RtmpOa4RJ8/file3e7f2bfa16bd' 2>/dev/null' had status 132

> deployApp(appName = "test_browser_4", python="/home/yueqi/anaconda/bin/python")
Preparing to deploy application...DONE
Uploading bundle for application: 652975...Error: 
* Error detecting python for reticulate: lexical error: invalid char in
   json text.  NA (right here) ------^
In addition: Warning message:
In system2(command = python, args = args, stdout = TRUE, stderr = NULL,  :
  running command ''/home/yueqi/anaconda/bin/python' '/home/yueqi/R/x86_64-pc-linux-gnu-library/3.5/rsconnect/resources/environment.py' '/tmp/RtmpOa4RJ8/file3e7f3eb7b2d6' 2>/dev/null' had status 132
```

case 2: when using other python environments
```
> deployApp(appName = "test_browser_3", python="/home/yueqi/anaconda/envs/py36/bin/python3")
Preparing to deploy application...DONE
Uploading bundle for application: 652974...DONE
Deploying bundle: 1821616 for application: 652974 ...
Waiting for task: 580001735
  building: Processing bundle: 1821616
  error: Parsing manifest
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 580001738 failed: Error parsing manifest: Schema validation failed: Additional properties are not allowed (u'python' was unexpected) at 

deployApp(appName = "test_browser_6", python="/home/yueqi/anaconda/envs/py2712/bin/python")
Preparing to deploy application...DONE
Uploading bundle for application: 652977...DONE
Deploying bundle: 1821621 for application: 652977 ...
Waiting for task: 580002123
  building: Processing bundle: 1821621
  error: Parsing manifest
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 580002124 failed: Error parsing manifest: Schema validation failed: Additional properties are not allowed (u'python' was unexpected) at 
```

**Comment by mmarchetti** [comment]
Hi @yueqiw, there is a PR in flight to fix this (#332). It needs small fix and review which should wrap up soon. In the meantime, downgrading to the previous rsconnect release should allow you to work around this. Sorry for the inconvenience.

**Comment by yueqiw** [comment]
@mmarchetti Thanks! Looking forward to the new fix. 

I tried downgrading rsconnect and removing reticulate dependency. The app can be built and uploaded to shinyapps.io but another problem occurred launching the app. 

The web page wouldn't load and I got the following error log: 
```
2019-01-21T22:08:41.018368+00:00 shinyapps[658090]: The Python installation in the environment was expected to have version  but is reporting version  ; the Python installation for version  may have changed. RStudio Connect needs to be restarted. Please contact the server administrator.
2019-01-21T22:08:41.022489+00:00 shinyapps[658090]: Warning message:
2019-01-21T22:08:41.022554+00:00 shinyapps[658090]: In system2(command = binary, args = args, stdout = TRUE, stderr = NULL,  :
2019-01-21T22:08:41.022558+00:00 shinyapps[658090]:   running command ''python/bin/python' "-E" "-c" "import sys; v = sys.version_info; print('%d.%d.%d' % (v[0], v[1], v[2]))" 2>/dev/null' had status 2
```

I think this might be related to shinyapps.io server. I have contacted shinyapps.io support regarding this.

**Comment by dylanjm** [comment]
I am experiencing the same problem. It doesn't look like that PR has been accepted yet.

**Comment by yueqiw** [comment]
Just an update the problem has been resolved using an older version of rsconnect and with the help of rstudio support.

**Comment by harshitmanek** [comment]
I am experiencing the same problem as before, even with the older version of rsconnect. 
`> deployApp(appName = "test_browser_4", python="/usr/bin/python3.6")
Preparing to deploy application...DONE
Uploading bundle for application: 652975...Error: 
* Error detecting python for reticulate: lexical error: invalid char in
   json text.  NA (right here) ------^`
Please fix this.

**Comment by mmarchetti** [comment]
Can you run the python script that rsconnect is using to inspect the environment? It is in rsconnect's `resources` directory. You can get its path with `file.path(.libPaths(), "rsconnect", "resources", "environment.py")`

`/usr/bin/python3.6 environment.py`

**Comment by harshitmanek** [comment]
Here you go! I am sharing the screenshot.
![screenshot from 2019-03-01 13-13-31](https://user-images.githubusercontent.com/5724492/53623817-33f9aa00-3c24-11e9-8ef5-8f9096f0b8b1.png)

**Comment by mmarchetti** [comment]
Were you able to use those paths to locate where rsconnect is installed? Once you do, please run the environment.py script using the python version you have configured. The output may contain an error message.

**Comment by ChristelSwift** [comment]
i'm experiencing the same "reticulate is in use, but python was not specified" problem when trying to deploy an app that relies on keras.  Is using an old rsconnect still the only workaround?

**Comment by rajasekh** [comment]
I am getting this error while deploying to shinyapps.io with reticulate
Error: Unhandled Exception: Child Task 604409002 failed: Error parsing manifest: Schema validation failed: Additional properties are not allowed (u'python' was unexpected) at

**Comment by tyluRp** [comment]
My specific experience was:

```
Error: Unhandled Exception: Child Task 606091138 failed: Error parsing manifest: Schema validation failed: Additional properties are not allowed (u'python' was unexpected) at 
Execution halted
```

Using R 3.5.3 with `rsconnect` 0.8.13. When upgrading to 0.8.14, the problem magically went away.

**Comment by eupimenta** [comment]
Try to

> library(reconnect)

**Comment by andrie** [comment]
This seems to have been fixed in the PR #332 as reported by @mmarchetti.  

I have just installed the latest master from github (using `remoted::install_github(...)`) and this resolved the issue for me.

**Comment by bengraft** [comment]
@andrie 
did you mean `remotes::install_github("rstudio/rsconnect", ref='737cd48')` ?

I'm also having this issue currently. 
Thank you for the help!

**Comment by andrie** [comment]
@bengraft , yes, that looks right (although I haven't checked the ref).  Sorry for the typo.
