### ISSUE TITLE
"Object does not exist" - rsconnect should deal with its metadata being out of sync with the server state more gracefully

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/rsconnect#331]
When a piece of content has local `rsconnect` metadata that is stale (either because the content has been deleted on the connect server or the connect server has been rolled back / wiped), rsconnect surfaces the error from attempting to get metadata from that (nonexistent) piece of content on the server. Notably: "Object does not exist."

The only way to fix this currently is to blow away the `rsconnect` metadata directory next to the content. This is not great.

What we should do instead might be:

- Lean on the force publishing option that already exists to force publishing over a non-existent piece of content.
- In force publish mode, warn the user that the content disagrees with the server, plus the vitals (stale content id, etc.) so if needed an admin can cross-reference the audit logs.
- In interactive mode, warn the user same as above and ask if they'd like to continue anyway.
- In unsupervised, non-force-publish mode: error instead of warning as above.

**Comment by jmcphers** [comment]
This is currently tracked in https://github.com/rstudio/rsconnect/issues/226.
