### ISSUE TITLE
Supporting for bitbucket (hg) repository / local repository

### ISSUE THREAD

**Issue by DiklaGelbard** [rstudio/rsconnect#333]
Hi, 
I am working with several packages from a bitbucket [repository](https://tanaylab.bitbucket.io/metacell-r/index.html) and I cannot publish my Shiny application which depends on these packages. 
First I ran the command: `options(repos=c(tg='https://tanaylab.bitbucket.io/repo',BiocManager::repositories())`
I re-installed the packages with `install.packages()`
Only then, I ran `packrat::init()`
Upon completion of the initialization I get the following warning messages:
 ````
1: In FUN(X[[i]], ...) :
  Package 'metacell 0.3.32' was installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores
2: In FUN(X[[i]], ...) :
  Package 'tgconfig 0.0.21' was installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores
 ````
When I tried to publish the app it failed and I got this error:
 ````
Error: Unhandled Exception: Child Task 580834913 failed: Error building image: Error fetching tgconfig (0.0.21) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: tgconfig (0.0.21)
 ````

Can you help me figure out how to solve this problem?

**Comment by jmcphers** [comment]
Shinyapps.io does not currently support Bitbucket repositories. More from the user guide (see Package Sources):

https://docs.rstudio.com/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud
