### ISSUE TITLE
writeManifest does not save the requirements.txt

### ISSUE THREAD

**Issue by colearendt** [rstudio/rsconnect#334]
When executing `rsconnect::writeManifest` for reticulated content that does not have a `requirements.txt` already, it seems to generate a `requirements.txt` that has the python dependencies in it (I can see the file in the file hash).

However, it does not save the `requirements.txt`, requiring me to go create one for the deployment to succeed. We should definitely _not_ overwrite / change a `requirements.txt` that already exists, but if one does not, I think it would be a fitting solution to retain the `requirements.txt` as a file that the `manifest.json` is dependent on for deployment.

This hearkens back to when the `packrat.lock` file was required in the bundle, as well, which is a requirement that was recently removed. I think the better long-term strategy is for the `requirements.txt` file to not be required (have all necessary state stored in the `manifest.json`)... but until then, I think it is worth persisting the `requirements.txt` file.

**Comment by jmcphers** [comment]
@mmarchetti What do you think?

**Comment by mmarchetti** [comment]
This is addressed in #381: https://github.com/rstudio/rsconnect/pull/381/files#diff-8c005ce5512281b7c08181fa872000a7R319

**Comment by jmcphers** [comment]
Great, thanks!
