### ISSUE TITLE
No License in this GitHub Repository

### ISSUE THREAD

**Issue by shea-parkes** [rstudio/rsconnect#338]
The CRAN page lists this package as GPL-2: 
https://cran.r-project.org/package=rsconnect
https://cran.r-project.org/web/packages/rsconnect/index.html

But there is no license file in this repository.  I think it would be best practice to include an explicit license file here.  Or are there parts of this solution not released to cran?  Or other considerations I am missing?  Thanks.

**Comment by scottmmjackson** [comment]
CRAN reads the `DESCRIPTION` file, which lists the license as GPL-2.

There's likely a copy of the license somewhere in here but not having a LICENSE file seems like an easily-fixed oversight. Thanks for the report!

**Comment by trestletech** [comment]
This is actually a common R package pattern. CRAN requires a particular format for licenses which is admittedly non-conventional. CRAN discourages enumerating the full license text, unfortunately.

It it possible to slip it in under `inst/`, but it looks like we're following the common R practices here IMHO.

**Comment by trestletech** [comment]
Maybe that's changed. ggplot2 is allowed to get away with including a real license. https://github.com/tidyverse/ggplot2/blob/master/LICENSE

**Comment by shea-parkes** [comment]
Thanks for pointing out the line in the `DESCRIPTION` file.  I'm fine with that documenting the license in this repository.

For background: I looked for a `LICENSE` file, and then I looked for a note/link in the `README.md`.

Feel free to close this if you like.  I'll leave it open for now just because it sounds like you were undecided on whether you wanted to add a `LICENSE` file.
