### ISSUE TITLE
Custom repos solution to private packages

### ISSUE THREAD

**Issue by alptaciroglu** [rstudio/rsconnect#340]
I was trying to publish my shiny application with rsconnect. My application has the package in the link : https://github.com/cytoscape/cyjShiny. 

I tried creating a custom repository and deploying via that solution, as in the link:
https://rstudio.github.io/packrat/custom-repos.html

Now, I broke my repos in R, getting an error ---> Error: Unhandled Exception: Child Task 587424425 failed: Error parsing manifest: Unknown repository for package source: 'myrepo' 

When I type: 
> options('repos')
$repos
                         CRAN 
"https://cloud.r-project.org" 

Anyone can offer a solution to how to deploy my app with that particular package and how to restore my repos? Thanks

EDIT2: I solved the broken repos issue after reinstalling R with all packages, but I still cannot do the rsconnect::deployApp with github package. I am not using RStudio but can try if it is the only option

Edit: I am running Ubuntu 18.04 

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.4                         
year           2018                        
month          03                          
day            15                          
svn rev        74408                       
language       R                           
version.string R version 3.4.4 (2018-03-15)
nickname       Someone to Lean On

**Comment by aronatkins** [comment]
Hi, @alptaciroglu - How are you installing the `cyjShiny` package? Are you using `devtools::install_github`? That's a public GitHub repository and `rsconnect` should be able to identify the package location without trouble.

```r
devtools::install_github("cytoscape/cyjShiny")
```

I recommend using the private repository only if you are unable to use GitHub directly. 

Your `repos` option is showing only the CRAN repository. That explains why you are receiving the "Unknown repository" error.

You need to tell R about both your CRAN repository and the custom repository.

```r
option(repos = list(CRAN = "https://cloud.r-project.org", myrepo = "https://custom-repository"))
```

In addition, the custom repository URL needs to be a public Internet URL so the shinyapps.io service can download the package from that repository.

**Comment by lmeninato** [comment]
> In addition, the custom repository URL needs to be a public Internet URL so the shinyapps.io service can download the package from that repository.

Is this true for the rsconnect server as well? We are looking for a solution for our team to be able to have shiny apps that call functions from private packages. We generally do `devtools::install_git()` and install packages from our gitlab server. I'm surprised that rsconnect can't install packages from the packrat library of a shiny application. Is there anything we can do beyond setting up an internal CRAN mirror and installing our private packages to that CRAN?

**Comment by jmcphers** [comment]
Yes, check out `SourcePackageDir` which will allow you to pre-load packages onto the server:

> A directory containing source bundles for packages that are unavailable on either CRAN or a public GitHub repository.

https://docs.rstudio.com/connect/admin/appendix-configuration.html#appendix-configuration-server
