### ISSUE TITLE
Public function to determine files for bundle

### ISSUE THREAD

**Issue by slopp** [rstudio/rsconnect#342]
Today our programmatic deployment workflow hinges on a handoff between an R user and a "deployment engineer":

1. R users commits code to Git
2. R user runs `rsconnect::writeManifest` to generate a manifest that describes dependencies, that manifest is committed alongside the code
-- HANDOFF --
3. Deployment engineer tars files from the repo and the manifest into a bundle
4. The deployment engineer calls some API endpoints to deploy the content

One weak spot in this handoff is identifying which files should be included in the tar file in step 3. 

In push-button publishing, a handful of helpful functions and linters identify these files for an R user. If these functions were made public, we could think about how R users can communicate the results of those functions to deployment engineers.

cc: @aronatkins  @nwstephens  @kellobri

**Comment by jmcphers** [comment]
Does this cover any new ground compared to https://github.com/rstudio/rsconnect/issues/268? (seems entirely overlapping but perhaps I'm missing something!)

**Comment by jmcphers** [comment]
FWIW all this logic *does* live in the package; it's just not exported. Try `rsconnect:::listBundleFiles()`.

**Comment by hadley** [comment]
Closing since `listBundleFiles()` is now exported.
