### ISSUE TITLE
Cannot create packrat data from manifest.json

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/rsconnect#344]
When I deploy a simple API with the 'connectapi' package, I get an error:
"Cannot create packrat data from manifest.json: Cannot transform manifest into packrat.lock: package xxx does not define Repository"

I am writing the manifest.json file with the writeManifest() function and hosting an RStudio Package Manager (RSPM).

Any idea why i get the error? 
An example of the content of my manifest.json file for the R6 package is included below.

```
"R6": {
    "Source": "RSPM",
    **"Repository": null,**
    "description": {
        "Package": "R6",
        "Title": "Encapsulated Classes with Reference Semantics",
        "Version": "2.4.0",
        "Authors@R": "person(\"Winston\", \"Chang\", role = c(\"aut\", \"cre\"), email = \"winston@stdout.org\")",
        "Description": "Creates classes with reference semantics, similar to R's built-in\n    reference classes. Compared to reference classes, R6 classes are simpler\n    and lighter-weight, and they are not built on S4 classes so they do not\n    require the methods package. These classes allow public and private\n    members, and they support inheritance, even when the classes are defined in\n    different packages.",
        "Depends": "R (>= 3.0)",
        "Suggests": "knitr, microbenchmark, pryr, testthat, ggplot2, scales",
        "License": "MIT + file LICENSE",
        "URL": "https://r6.r-lib.org, https://github.com/r-lib/R6/",
        "LazyData": "true",
        "BugReports": "https://github.com/r-lib/R6/issues",
        "RoxygenNote": "6.1.1",
        "NeedsCompilation": "no",
        "Packaged": "2019-02-14 18:34:54 UTC; winston",
        "Author": "Winston Chang [aut, cre]",
        "Maintainer": "Winston Chang <winston@stdout.org>",
        **"Repository": "RSPM"**,
        "Date/Publication": "2019-02-14 19:42:14 UTC",
        "Built": "R 3.5.1; ; 2019-03-01 08:49:55 UTC; unix"
    }
}
```

**Comment by aronatkins** [comment]
Could you tell us your `repos` setting you were using when the manifest was generated?
```r
getOption("repos")
```

The "null" repository is likely because the `repos` option has the RSPM server configured as the `CRAN` value; `rsconnect` could fail to find the correct repository when the "Repository" information in the package DESCRIPTION did not match the name in the `repos` option.

The newest version of `rsconnect` should do better with these situations. Could you try installing `rsconnect` from GitHub and regenerate your manifest with `rsconnect::writeManifest`?

```r
devtools::install_github("rstudio/rsconnect")
```

**Comment by jmcphers** [comment]
@mac-pfa we're closing since we haven't heard back in many months; feel free to reopen if you're still seeing this with the latest rsconnect.

**Comment by aiminy** [comment]
I have same issue, how to solve this?

**Comment by aronatkins** [comment]
@aiminy - Please open a new issue with additional details describing your situation. The error message was produced by Posit Connect when attempting to process your deployment. The error indicated that the rsconnect package was unable to locate an R repository containing that package.

This error was removed from Connect starting with Posit Connect 2023.05.0.
