### ISSUE TITLE
Vanity URL error

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/rsconnect#349]
When setting a "vanity" URL in RStudio Connect, the execution of the application fails if the custom path starts with "connect".

If the custom path is simply "connect", a error message is displayed: 
"Error: Vanity URL may not begin with '/connect/'."

If the custom path includes other text, like "connect_my_custom_path", then the execution of the application fails with no error message.

**Comment by trestletech** [comment]
Hi, @mac-pfa . Thanks for reporting this.

I'll open a ticket on our end so we can start looking at it, but do you mind shooting an email to support@rstudio.com with this information? That'll be the easiest way for us to follow up on RStudio Connect issues. This repo is just used for tracking issues on the `rsconnect` package itself. Thanks!
