### ISSUE TITLE
failing deployments still open app url and output error in an arbitrary location

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#35]
This is probably a mixed rsconnect/IDE issue...

I have a deployment that is failing for good reason - the target system is missing some OS dependencies.

The `Deploy` window has the message (in red):

```
Application deployment failed with error: exit status 1
```

That message does not appear at the end of the `Deploy` window but in an arbitrary earlier location (probably due to some stream buffering).

Further, I get a success message from the RStudio IDE and am sent to the application URL (this is at the very end of the `Deploy` window):

```
Deployment completed: http://HOST:PORT/USER/APPNAME/
```

The application URL justifiably 404s because the deployment failed.

I am surprised that:

1. The "deployment failed" message is not at the end of the `Deploy` buffer.
1. We open a browser and navigate to the application URL.
1. The `Deploy` buffer does not stay in focus (due to the error).

**Comment by jjallaire** [comment]
The deployment failed message is indeed probably in the middle due to stream buffering. @jmcphers There is a setting we can use when we launch a child process to merge stdout and stderr -- that might leave the failure message at the bottom (but it wouldn't be red unless we added a special case in the deployment output handler to make it so).

I think #2 and #3 are likely to be resolved concurrently once we figure out why RStudio erroneously believes the deployment succeeded.

**Comment by aronatkins** [comment]
If I perform `rsconnect::deployApp` from the RStudio console (not using any of the IDE hooks), the "deployment failed" message is at the end of the output but a browser still opens and navigates to the (invalid) application URL.

**Comment by aronatkins** [comment]
The IDE no longer views erred deploys as successful. The output interleaving still occurs.

The `rsconnect`-inserted "Application deployment failed with error: XXX" message still appears interleaved with output (`stderr`) from the server in the "Deploy" window. The `rsconnect` message is on `stdout`.

When run from the Console IDE window, the `rsconnect` message is the last line of the failing `deployApp` output.

Interesting side-note. The red/black colors for deploy output are reversed in the Console window vs. the Deploy window.

**Comment by aronatkins** [comment]
I should note that even the successful message:
```
Application successfully deployed to APPLICATION_URL
```

is interleaved with other messages.

**Comment by jjallaire** [comment]
@jmcphers Could this be because we are using the `message()` function? That gets reported up to R as "error". In that case perhaps we should switch to plain output?

**Comment by aronatkins** [comment]
@jjallaire We use `displayStatus` which just uses `cat`:
https://github.com/rstudio/rsconnect/blob/2f70e82bf3992e4e5dc4c65a5386c3f58e0d6b3d/R/utils.R#L23-L29

**Comment by jjallaire** [comment]
Then perhaps there is some other output using message? I can't think of any
reason why output would be interleaved other than the previously suggested
stdout/stderr theory....

**Comment by jmcphers** [comment]
I'm 95% confident that (1) is an IDE bug, and since (2) and (3) are resolved I think we should resolve this issue on rsconnect, and open one on the IDE (which I've just done; case 4525).
