### ISSUE TITLE
Error when publishing with diagnostics

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#354]
Via a customer support ticket, a customer who got publishing errors when diagnostics were on:

``` 
Error in rawToChar(fileContents) : 
  embedded nul in string:

----- Error stack trace -----
13: rawToChar(fileContents)
12: paste0("<< ", rawToChar(fileContents), "\n")
11: cat(paste0("<< ", rawToChar(fileContents), "\n"))
10: http(service$protocol, service$host, service$port, method, url, 
        headers, contentType, file, certificate = certificate)
9: httpRequestWithBody(service, authInfo, "POST", path, query, contentType, 
       file, content, headers)
8: POST(service, authInfo, path, contentType = "application/x-gzip", 
       file = bundlePath)
7: grepl(contentType, response$contentType, fixed = TRUE)
6: isContentType(response, "application/json")
5: handleResponse(POST(service, authInfo, path, contentType = "application/x-gzip", 
       file = bundlePath))
4: client$uploadApplication(application$id, bundlePath)
3: force(code)
2: withStatus(paste0("Uploading bundle for ", assetTypeName, ": ",  [...]
```

I couldn't repro myself, but it's clear that what's happening is that the debug code (which tries to show server request/response bodies) is trying to dump the application bundle to the console, which is gzipped and therefore has null bytes. We should make sure this debug code only fires for JSON bodies.

**Comment by jmcphers** [comment]
Haven't figured out what the deal is here; the debug code appears to be correctly guarded to only emit JSON.

**Comment by tburnley** [comment]
I had a similar issue when republishing an existing Rmarkdown report first published by another colleague.  Once I added my username to the "Who can change this document" listing the error was resolved.

**Comment by jmcphers** [comment]
Thanks, but we still haven't repro'ed this so closing unless we get another report or more leads. :-/
