### ISSUE TITLE
Can not publish RMarkdown website

### ISSUE THREAD

**Issue by fzwaeustc** [rstudio/rsconnect#355]
Hi,

I was naively replicating this Rmarkdown example to build a static webiste here: https://rmarkdown.rstudio.com/lesson-13.html

When I'm at the index.Rmd page, and click "publish" to publish to RSconnect, it goes through. But when I check the published "document" on RSconnect, all the subpages don't work except the "index.html"

Is it supposed to be the case? Or it could be a nice feature to add.

Thanks and appreciate,

Peng

**Comment by cderv** [comment]
I suspect only the index.Rmd file was render using the `rmarkdown::render` and publish. 
Can you check in logs or in the RStudio UI when you click on the button if 
* `rmarkdown::render` was used to render only the index file ? 
* `rmarkdown::render_site` was used to render the all directory ? 

`rsconnect` has the `rsconnect::deploySite` function that could be used to deploy such website. This function should be used when you click on publish
![image](https://user-images.githubusercontent.com/6791940/56846318-2ed87480-68ce-11e9-8017-e690391056fe.png)

And you should see the file of the website to publish
![image](https://user-images.githubusercontent.com/6791940/56846323-457ecb80-68ce-11e9-9d79-ca45b75eca4e.png)

Have you seen all this ? 

Hope it helps.

**Comment by fzwaeustc** [comment]
Thanks @cderv . I think it's because I didn't run `rmarkdown::render_site`. 
Now everything is good!
