### ISSUE TITLE
Add a "global" rsconnect preflight script

### ISSUE THREAD

**Issue by colearendt** [rstudio/rsconnect#356]
Many customers have many R installations and many users. Managing a separate preflight script for things like unsetting proxy variables, etc. for each R installation seems excessive when a global option might be possible (e.g. `/etc/rsconnect.global` or something). I'm not sure whether there is precedent for this in the R world, but want to record it as a feature request.

Having a global preflight script would simplify common operations that cross users _and_ R installations _and_ projects. For example, `Sys.unsetenv("http_proxy");`

https://rdrr.io/cran/rsconnect/man/options.html (near the bottom)

**Comment by jmcphers** [comment]
We currently follow R's lead here; the pre-flight script is specific to the R version, just like `Rprofile.site` is. This allows you to use different settings per R installation if necessary:

    $R_HOME/etc/rsconnect.site

Of course, it does mean you have to symlink or something to share settings across multiple installations, just like `Rprofile.site`. Was this inspired by a customer request?

**Comment by colearendt** [comment]
Oops. Sorry for never responding. Yes, this was inspired by a customer who needs this script to make publishing possible at all. They did not request specifically that they wanted such a global file, but I immediately felt the risk associated with having to provide the file to each R installation. Ultimately, they would just need to make this file a part of how they manage / install R. As you said, we are following convention with R here, so if they have a custom Rprofile.site, they would need to follow the same convention and manage with each installation of R.
