### ISSUE TITLE
RMarkdown renders flexdashboard, but rsconnect doesn't

### ISSUE THREAD

**Issue by akgold** [rstudio/rsconnect#357]
`isShinyRmd` function seems to be stricter than however RMarkdown package detects shiny runtime and knows to do `rmarkdown::run` over `rmarkdown::render`. Therefore, it's easy to create a `flexdashboard` that renders fine locally, but will break on deployment to Connect. 
Reprex:
```
``` r
library(magrittr)
c("---", 
  "title: test", 
  "output:", 
  "  flexdashboard::flex_dashboard:", 
  "    runtime: shiny",
  "---") %>% 
  writeLines("./test.Rmd", sep = "\n")

# knits fine in IDE
# breaks on connect deployment
rsconnect:::isShinyRmd("./test.Rmd")
#> [1] FALSE

c("---",
  "title: test", 
  "output:", 
  "  flexdashboard::flex_dashboard:", 
  "runtime: shiny", # Difference is indentation of this line
  "---") %>% 
  writeLines("./test.Rmd", sep = "\n")

# knits fine in IDE
# works in deployment
rsconnect:::isShinyRmd("./test.Rmd")
#> [1] TRUE
```

<sup>Created on 2019-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
```
Possible to make isShinyRmd friendlier? Maybe just a nice warning?

**Comment by akgold** [comment]
A number of customers have run into this issue according to this community thread: https://community.rstudio.com/t/rstudio-connect-interactive-markdown-with-shiny-error-path-for-html-dependency-not-provided/7263/10

**Comment by jmcphers** [comment]
We should be more strict here on the IDE, not looser in the rsconnect package; it is an error to specify `runtime: shiny` beneath `flexdashboard` as it is not an option to `flexdashboard`. I've ported this issue over there: https://github.com/rstudio/rstudio/issues/5743
