### ISSUE TITLE
writeManifest error with renv

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/rsconnect#360]
When calling the "writeManifest" function in a directory with a "renv" folder, i get the following error:
```
Error: Unable to retrieve package records for the following packages:
- 'GLMMGibbs', 'foo', 'pkg', 'testRcppClass', 'testRcppInterfaceExporter', 'testRcppInterfaceUser', 'testRcppModule', 'tree', 'yags'
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

When calling the function in the same directory without the "renv" folder, I don't get the error.
Does the function look for dependencies in the "renv" folder, and would it be possible to ignore this folder?
Or would it be better to supply a list of the files to process instead of the entire "appDir"?

**Comment by colearendt** [comment]
Apologies for the delay here! Would you mind trying again with latest dev `renv`? This is a pain point that we did a little improvement on since this issue was written.

**Comment by mac-pfa** [comment]
It seems to working, thanks!

**Comment by mac-pfa** [comment]
It works in a directory if it does not contain any plumber.R or app.R files.
However, if you add any of these files it still breaks.

In addition, I now receive the following error before it breaks:
"Error in eval(x, envir = envir) : object 'dothis' not found"

**Comment by kevinushey** [comment]
https://github.com/rstudio/packrat/issues/385 sounds potentially related, but a reproducible example would be helpful.

**Comment by mac-pfa** [comment]
Sorry, missed the part about the dev versions!
It is now working with the dev version of the rsconnect package (0.8.15).
It also fixed the issue of having to increase the rsconnect.max.bundle.files option.
