### ISSUE TITLE
Chinese characters in R plots can't display properly.

### ISSUE THREAD

**Issue by supernum163** [rstudio/rsconnect#365]
While hosting a Shiny App, the Chinese characters in plots can't display properly, but in code line comments they are just fine.

See there (https://supernum163.shinyapps.io/testApp/).

![图片](https://user-images.githubusercontent.com/25193929/59654173-a4bed500-91c7-11e9-8cd6-b3a9639d6b2b.png)

**Comment by jmcphers** [comment]
This looks like an issue with shinyapps.io, not the rsconnect package (it's clear that the code itself is making it over just fine!). Try our community forum:

https://community.rstudio.com/c/shiny/shinyappsio

Hope this helps!
