### ISSUE TITLE
ERROR: installing package wiqid

### ISSUE THREAD

**Issue by ghost** [rstudio/rsconnect#366]
Why can't I install wiqid in R-studio on a mac? this is the error I get:
Package Version Priority Depends Imports LinkingTo Suggests Enhances License
     License_is_FOSS License_restricts_use OS_type Archs MD5sum NeedsCompilation File
     Repository

**Comment by cderv** [comment]
Hi, 

how did you try to install the package on your system ? `install.packages("wiquid")` ? 

Also, FWIW, this look like the output of `installed.packages()` when the package is not yet installed. 

``` r
installed.packages("wiqid")
#>      Package LibPath Version Priority Depends Imports LinkingTo Suggests
#>      Enhances License License_is_FOSS License_restricts_use OS_type Archs
#>      MD5sum NeedsCompilation Built
```

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in the rsconnect package itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
