### ISSUE TITLE
cursor in wrong location when asking for overwrite permission

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#37]
This might be part rsconnect, part IDE.

![screen shot 2015-05-28 at 4 45 07 pm](https://cloud.githubusercontent.com/assets/362187/7870690/f0591c82-0558-11e5-9546-9b33ea016c6d.png)

Unfortunately, it didn't appear in this screen-shot, but the cursor was placed after the `Update application currently deployed at` rather than after the `[Y/n]` on the next line.

**Comment by jmcphers** [comment]
This is 100% IDE.
