### ISSUE TITLE
writeManifest problem with RETICULATE_PYTHON variable

### ISSUE THREAD

**Issue by colearendt** [rstudio/rsconnect#374]
It seems that `rsconnect`'s ability to pick up the `RETICULATE_PYTHON` variable is broken in the latest dev version.

Current _documented_ behavior: 
- if `RETICULATE_PYTHON` is set, then include `python` in manifest

Current behavior:
- if `RETICULATE_PYTHON` is set, then `python` is not included in the manifest

Desired behavior:
- if `RETICULATE_PYTHON` is set, include `python` in manifest **_only if_** `reticulate` is in use in the project

```` r
writeLines(c(
  "---",
  "title: test-doc",
  "output: html_document",
  "---",
  "```{r}",
  "library(reticulate)",
  "```"
), "tmp.Rmd")

Sys.setenv("RETICULATE_PYTHON" = "/usr/local/bin/python")

# expected output:
rsconnect::writeManifest(python = "/usr/local/bin/python")
head(readLines("manifest.json"), 20)
#>  [1] "{"                                               
#>  [2] "  \"version\": 1,"                               
#>  [3] "  \"locale\": \"en_US\","                        
#>  [4] "  \"platform\": \"3.4.3\","                      
#>  [5] "  \"metadata\": {"                               
#>  [6] "    \"appmode\": \"rmd-static\","                
#>  [7] "    \"primary_rmd\": \"reprex_reprex.spin.Rmd\","
#>  [8] "    \"primary_html\": null,"                     
#>  [9] "    \"content_category\": null,"                 
#> [10] "    \"has_parameters\": false"                   
#> [11] "  },"                                            
#> [12] "  \"python\": {"                                 
#> [13] "    \"version\": \"2.7.15\","                    
#> [14] "    \"package_manager\": {"                      
#> [15] "      \"name\": \"pip\","                        
#> [16] "      \"version\": \"18.0\","                    
#> [17] "      \"package_file\": \"requirements.txt\""    
#> [18] "    }"                                           
#> [19] "  },"                                            
#> [20] "  \"packages\": {"

# current output:
rsconnect::writeManifest()
head(readLines("manifest.json"), 20)
#>  [1] "{"                                                               
#>  [2] "  \"version\": 1,"                                               
#>  [3] "  \"locale\": \"en_US\","                                        
#>  [4] "  \"platform\": \"3.4.3\","                                      
#>  [5] "  \"metadata\": {"                                               
#>  [6] "    \"appmode\": \"rmd-static\","                                
#>  [7] "    \"primary_rmd\": \"reprex_reprex.spin.Rmd\","                
#>  [8] "    \"primary_html\": null,"                                     
#>  [9] "    \"content_category\": null,"                                 
#> [10] "    \"has_parameters\": false"                                   
#> [11] "  },"                                                            
#> [12] "  \"packages\": {"                                               
#> [13] "    \"Matrix\": {"                                               
#> [14] "      \"Source\": \"RSPM\","                                     
#> [15] "      \"Repository\": \"http://demo.rstudiopm.com/cran/latest\","
#> [16] "      \"GithubRepo\": null,"                                     
#> [17] "      \"GithubUsername\": null,"                                 
#> [18] "      \"GithubRef\": null,"                                      
#> [19] "      \"GithubSha1\": null,"                                     
#> [20] "      \"description\": {"
````

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Again, while you're in here, if it is possible to make the _behavior_ such that removing `library("reticulate")` removes the `python:` section, that would be great! Of course, that _is_ a change in behavior, so other parties may need to be a part of that discussion if it is something we decide to do.

**Comment by mmarchetti** [comment]
The `RETICULATE_PYTHON` check was moved into `deployApp` so it's no longer happening in `writeManifest`. This was done so that python could be off by default for shinyapps.io. @colearendt does `writeManifest` need the same behavior of suppressing python for shinyapps.io?

**Comment by colearendt** [comment]
Very interesting! I don't think `writeManifest` is useful at all for shinyapps.io (unless this function is called somewhere in the shinyapps.io preparation process). My concern here was mostly around programmatic deployment of python-based content to RSC. I think we have a bit of a broken workflow there, both because of the weirdness around requirements.txt and the behavior here with `RETICULATE_PYTHON`.

**Comment by mmarchetti** [comment]
`writeManifest` is not called at all within rsconnect; it's user-invoked to construct an appropriate manifest for use with programmatic deployments (e.g. git). It should be relatively simple to fix this. In the meantime, a workaround could be to pass an explicit `python` parameter to `writeManifest`, perhaps using `Sys.getenv("RETICULATE_PYTHON")`.

**Comment by colearendt** [comment]
Ok that's good to know! Awesome! Yes, the explicit `python` parameter works for `writeManifest`. I think the important thing to figure out is what the _desired_ behavior is. IMO it should be: `RETICULATE_PYTHON` set plus `reticulate` used = python deployment, OR `python` parameter set = python deployment.

**Comment by mmarchetti** [comment]
From a pass through the code, the current behavior when creating the manifest via deployApp is:
* If target is shinyapps, python is forced to NULL and no python section is injected. This behavior can be changed via the `rsconnect.python.enabled` option. This case won't apply to `writeManifest`.
* Otherwise (Connect), we use the specified python argument. If it's NULL, we check `RETICULATE_PYTHON`. If one of those yields a python installation, we inject a dependency on reticulate and include a python section in the manifest. We do this to handle Rmd files that contain a `{python}` block, without requiring an R block that imports reticulate.

**Comment by colearendt** [comment]
Ohh interesting!! I had not thought of the `{python}` case. Is there any other way to discern that?

I guess the problem I'm facing is on RSP / multi-tenant environments. In this case, the user may not know where the Python installations are, but they want to use `reticulate`. There are dangers of munging the PATH, so I like the idea of setting `RETICULATE_PYTHON` globally to a default R version. However, then every Connect deployment has Python included.

Perhaps the long term solution is tooling within the IDE to select Python version, which the admin can then configure.

**Comment by mmarchetti** [comment]
`{python}` blocks should be detectable, but to do that cleanly may require changes to packrat, rmarkdown, and/or knitr. We maybe able to put together something simpler in rsconnect to avoid unnecessarily injecting a reticulate dependency and python in the manifest.

**Comment by slopp** [comment]
@scottmmjackson  this came up again on a call today. Not to jump the priority list, but I wanted to be sure the problem statement was clear. 

The user, in this case, had reticulate_python set in their .Rprofile in their home directory, so it was being set for every project. They were working on a R only project and then when they tried to deploy, RSC too aggressively detected python and tried to set it, leading to a deployment failure (because RSC wasn't configured for Python). 

Does this make sense with your understanding of the issue so far?

**Comment by slopp** [comment]
Specifically, @mmarchetti  I am worried that: 
> RETICULATE_PYTHON. If one of those yields a python installation, we inject a dependency on reticulate and include a python section in the manifest. We do this to handle Rmd files that contain a {python} block, without requiring an R block that imports reticulate.

This will exasperate the problem this user faced.

**Comment by mmarchetti** [comment]
Proposed behavior (for both `deployApp` and `writeManifest`:
* A Python binary can be specified by passing the `python` parameter, or by setting `RETICULATE_PYTHON` (same as current behavior).
* Rmd files in the bundle are scanned for python blocks; if any are found, a dependency on `reticulate` is injected.
* If `reticulate` is a dependency (explicitly or implicitly via the point above), AND python is specified, then a python section is included in the manifest.
  - Note that if you use reticulate and don't provide python, the deployment will likely fail. (Unless reticulate was an optional dependency and wasn't actually used).
* For `deployApp` only: if the deployment target is shinyapps, python is forced to NULL preventing a python section from appearing in the manifest (unless a config option is set). This is current behavior.
  - Note that `writeManifest` knows nothing about shinyapps, and will include python in the manifest following the rules above.

**Comment by colearendt** [comment]
Just to be clear on the second point. If `reticulate` is _not_ a dependency (explicitly or implicitly), the python section will _not_ be included?

**Comment by mmarchetti** [comment]
Precisely. Seem like the right thing to do?

**Comment by colearendt** [comment]
I think so! It addresses my concerns and (so far as I can tell) @slopp 's.

**Comment by kevinushey** [comment]
To confirm, is reticulate also detected and used if it's detected as a dependency of some other required package (e.g. tensorflow)? Presumedly that's part of the "normal" dependency discovery workflow and this is mainly for applications that use reticulate / Python without a more explicit declaration that they do so?

**Comment by mmarchetti** [comment]
Yes - the existing dependency code produces and reads a packrat lockfile, so it captures indirect dependencies too.

This change has 2 components:

1. Stop injecting a dependency on reticulate just because `RETICULATE_PYTHON` is set. This adds python to a lot of manifests that don't need it.
1. Start injecting a dependency on reticulate if there appears to be a python block in the Rmd file. This could also be accomplished by adding an R block containing `library(reticulate)` but it would be nice to be able to author a python-only Rmd file without it.

**Comment by kgartland-rstudio** [comment]
Verified.

RETICULATE_PYTHON is set:
* Test: python block in Rmd
** Results: python in manifest

* Test: library(reticulate) in code
** Results: python in manifest

* Test: no python block in Rmd
** Results: no python

* Test: no library(reticulate) in code
** Results: no python

RETICULATE_PYTHON is _not_ set:
* Test: python block in Rmd
** Results: no python

* Test: library(reticulate) in code
** Results: no python

* Test: no python block in Rmd
** Results: no python

* Test: no library(reticulate) in code
** Results: no python

**Comment by colearendt** [comment]
If we number these 1-8,

My understanding of this issue was to primarily target numbers 3 and 4, ensuring that they were set to "no python"

Numbers 5 and 6 surprise me, but perhaps there is a reason why.

**Comment by colearendt** [comment]
Discussed offline - 5 and 6 are driven primarily b/c we don't know what python to use (and using system python is unreliable). Best approach is probably to _at least_ warn the user that they need to set RETICULATE_PYTHON in order to get deployment to use python.

**Comment by slodge** [comment]
Sorry to comment on an old closed thread... 

but we recently (well today) saw an issue where we'd used `reticulate::use_python()` to configure the python version - this method: https://github.com/rstudio/reticulate/blob/master/R/use_python.R - this is *not* supported in `writeManifest()` - just writing this here so it comes up in search (to save others time)
