### ISSUE TITLE
showLogs() error with streaming = FALSE

### ISSUE THREAD

**Issue by OuNao** [rstudio/rsconnect#377]
Hi,

showLogs throws a error with streaming = FALSE.
`Error in client$getLogs(application$id, entries, FALSE) :   unused argument (FALSE)`

I can solve with this code:
```
appPath<-file.path(getwd(),"myapp")
appName<-"myapp"
target <- rsconnect:::deploymentTarget(appPath, appName, NULL, NULL, NULL)
accountDetails <- rsconnect:::accountInfo(target$account)
client <- rsconnect:::lucidClient(rsconnect:::shinyappsServerInfo()$url, accountDetails)
application <- rsconnect:::getAppByName(client, accountDetails, target$appName)
logs <- client$getLogs(application$id, 50)
cat(logs)
```

client$getLogs has only 2 params...

Regards,

**Comment by modernresearch** [comment]
I had this problem too. I submitted a pull request to fix.

**Comment by jmcphers** [comment]
Fixed by https://github.com/rstudio/rsconnect/pull/387 from @modernresearch
