### ISSUE TITLE
Add option for deployApp to error out if return is FALSE

### ISSUE THREAD

**Issue by rharlow86** [rstudio/rsconnect#391]
We use deployApp in ci/cd pipelines on gitlab to deploy applications to RConnect. Currently, if there is an error during deployment on the deployment server, the job still runs to completion and "succeeds" in the pipeline because an error is not thrown. Would you be amenable to adding a package option e.g. rsconnect.error.on.fail = TRUE that would see if the return of deployApp is FALSE and then optionally error out? Happy to provide a pull request if that helps.

**Comment by jmcphers** [comment]
There's already `on.failure` that will let you run arbitrary code if the deployment fails. Will that suit your needs?

https://github.com/rstudio/rsconnect/blob/d5b1ff37e50d7bc0916efabeca71b98a8700ef4b/R/deployApp.R#L111

**Comment by rharlow86** [comment]
ok thanks!

**Comment by rharlow86** [comment]
Actually, do you know when this parameter goes to CRAN? Looks like this is a relatively new feature

**Comment by jmcphers** [comment]
Correct, this isn't on CRAN yet. We're cleaning up for a CRAN submission within the next few weeks.

**Comment by rharlow86** [comment]
ok awesome thanks
