### ISSUE TITLE
Retain publishing information even when failed

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#40]
I publish an application to some server and give it a name (different than that default). That deployment happens to fail.

When I next try to deploy that application, none of my entered data is available. I need to reenter whatever manual configuration I performed.

**Comment by jmcphers** [comment]
> none of my entered data is available.

What data/configuration was particularly cumbersome to re-enter? (this might need to be retained by the IDE)

**Comment by hadley** [comment]
Superseded by #677
