### ISSUE TITLE
improve browser linter

### ISSUE THREAD

**Issue by r2evans** [rstudio/rsconnect#400]
I suggest the regex used in `hasBrowserCalls` can be a little too permissive:

https://github.com/rstudio/rsconnect/blob/0aafa8855bdd04db4640fd091575778146992b00/R/lint-utils.R#L6-L10

In an internal project, it falsely matched a function I wrote (`fake_browser`) that is not an interactive-only thing. I suggest the regex be tightened, perhaps just a word boundary: `"\\bbrowser\\([^)]*\\)"`.

Do you think this would be too-restrictive as a general case?

(In case it helps: win10, R-3.5.3, rsconnect-0.8.16, deploying to RSC-1.8.0

**Comment by kevinushey** [comment]
Your change sounds correct to me. Would you be willing to file a pull request?

**Comment by r2evans** [comment]
do you want an entry in `NEWS.md` as well?
