### ISSUE TITLE
No option to set visibility (private/public) when deploying to shinyapps.io

### ISSUE THREAD

**Issue by ronomal** [rstudio/rsconnect#403]
I think it would be really useful to have an option in rsconnect::deployApp() that enabled setting of public/private visibility. At the moment publishing to shinyapps.io defaults to public and if you want it to be private you have to then remember to set it in the dashboard manually afterwards while your application is already open to the public. Found 2015 post on the subject by @tareefk [here](https://groups.google.com/forum/#!topic/shinyapps-users/--CE88p_IxU) (shinyapps.io google group).

**Comment by gtm19** [comment]
My current workaround to this is to upload an empty Shiny app to shinyapps.io, set the app to Private in the shinyapps.io console, then deploy my _actual_ app to shinyapps.io.

In my deploy script, I have the following code which aborts if I have forgotten to set my visibility to Private - so I can't accidentally deploy what should be a Private app as Public:

```R
  # get the properties of the app
  props <- rsconnect::showProperties(appName = app_name)

  # stop if the app is not private
  if(props["application.visibility", 1] != "private"){
    stop(glue::glue("{app_name} is not private on shinyapps.io. Aborting."))
  }
```

**Comment by systats** [comment]
This can lead to serious privacy violations, and worst case people will lose their job over this. Thanks gtm19 for sharing your workaround, but there has to be a less redundant and efficient way to deploy private apps. Especially for paid plans. Thanks for all the good work you are doing!

**Comment by ronomal** [comment]
Just giving this a nudge. It has been a year. I would be happy to do the work but would need some guidance, is it possible to set this through the existing API?

**Comment by durey** [comment]
Still no news about this? It would be REALLY appreciated to have this feature available.

**Comment by mjng93** [comment]
Adding my voice to this. This would be immensely helpful in streamlining dashboard deployment to production as well as patching security gaps.

**Comment by aronatkins** [comment]
Would folks mind trying the latest version of `rsconnect` from GitHub?

```r
remotes::install_github("rstudio/rsconnect")
```

You should now be able to deploy private applications by adding an `appVisibility` argument to `rsconnect::deployApp`:

```r
rsconnect::deployApp(..., appVisibility = "private")
```

**Comment by durey** [comment]
For sure! I will try it right now!!!! <3

**Comment by landisrm** [comment]
This is great, many thanks for this improvement.

**Comment by durey** [comment]
@aronatkins , I've just deployed a new private app and even invited the proper users right away and everything worked perfectly, many thanks for this HUGE improvement in security!!! Kudos!

**Comment by ronomal** [comment]
This is brilliant, thanks @aronatkins!

**Comment by aronatkins** [comment]
The true kudos are to @mbaynton; I only clicked the merge button! We're happy to have helped.

**Comment by durey** [comment]
Wait a moment, @aronatkins , I've deployed a brand new dashboard with `appVisibility = "private"` and everything works fine. But if I redeploy it without setting anything (not using the new `appVisbility` parameter), the dashboard is turned back to public! 

That behaviour changes the previous one, when current set visibility was kept on redeployments.

**Comment by aronatkins** [comment]
Thanks for finding that, @durey; we'll address immediately.

**Comment by aronatkins** [comment]
@durey - should be addressed, now. The `appVisibility` argument now takes a `NULL` value by default and no modification to visibility is made when it that default `NULL` value is used.

**Comment by mjng93** [comment]
This is amazing, thank you so much! On a related note, is there anyway in the code to set a list of authorized users via e-mail?

**Comment by ronomal** [comment]
> This is amazing, thank you so much! On a related note, is there anyway in the code to set a list of authorized users (instead of going into shiny GUI and listing out)?

Yes, check out `rsconnect::addAuthorizedUser()`.
