### ISSUE TITLE
Deploy default Shiny app to Connect server -- there is no package called 'reticulate'

### ISSUE THREAD

**Issue by mpfp** [rstudio/rsconnect#416]
Hi, 

I'm trying to deploy a 'learnr' tutorial to a Connect server and get this error message:
`[Connect] 2020/03/17 15:04:27.314950119 Error in library("reticulate") : there is no package called ‘reticulate’`.  Here is the complete output.

```
Preparing to deploy application...DONE
Uploading bundle for application: 14...DONE
Deploying bundle: 26 for application: 14 ...
[Connect] Building Shiny application...
[Connect] Bundle requested R version 3.6.3; using /usr/lib/R/bin/R which has version 3.6.3
[Connect] 2020/03/17 15:04:27.314950119 Error in library("reticulate") : there is no package called ‘reticulate’
[Connect] 2020/03/17 15:04:27.315097249 Execution halted
[Connect] Build error: exit status 1
Application deployment failed with error: exit status 1
```

To simplify, I created a default Shiny app (the old faithful one) and tried deploying.  I get the same message.  

I have also tried explicitly loading reticulate with `library(reticulate)`.  That doesn't fix the issue either.

Any ideas?

**Comment by slopp** [comment]
Sorry for the trouble here. 

If you are deploying to RStudio Connect, we'd recommend opening a support ticket by emailing support@rstudio.com with the relevant deployment logs, we'll be able to take a more detailed look from there and can ensure we have an appropriate response time for you.
