### ISSUE TITLE
Bundle files outside of app directory

### ISSUE THREAD

**Issue by Express50** [rstudio/rsconnect#418]
I'm trying to publish an app to shinyapps.io with the following folder structure:

```
- src/
   - app/
      - app.R
      - server.R
      - ui.R
   - model/
      - <additional R code>
```

The model folder should be bundled together with the app folder when publishing, but I couldn't find a way to do this (using `appFiles` or `appFileManifest`). The only option I see at the moment is to move the model folder under app, but I would prefer to keep these folders separate.

Is there a way to support my current folder structure? Thanks!

**Comment by jmcphers** [comment]
Unfortunately not; only a single directory can be published. This simplifies many aspects of the publishing process, so it's not likely we'll change it.
