### ISSUE TITLE
How to include Rmd but not evaluate Rmd

### ISSUE THREAD

**Issue by lz100** [rstudio/rsconnect#424]
I have some functions in the app to edit an Rmd file, so I upload a template with other things in my app. rsconnect evaluates the Rmd file when I deploy the app. I just want it to be a resource file not part of my code. Is there a way to upload the Rmd but not evaluate anything inside?

**Comment by slopp** [comment]
Where are you uploading to? RStudio Connect?

The R Markdown document may be partially executed to identify package dependencies - are you seeing execution at deploy time or after the content is on the server?

Probably the best way forward here is to email support@rstudio.com if you are using Connect or post on community.rstudio.com if this is some other reconnect client.

**Comment by lz100** [comment]
Sorry didn't make it clear. I tried to deploy my shiny app to shiny.io. The Rmd file is part of my shiny inst data, not my code. My codes are stored in ui.R server.R. During deployment, rsconnect tried to execute this Rmd file, but I don't want to execute this file. This file content will be displayed (cat) as text on my app after deployment when certain buttons are clicked. So this file should never be executed whenever during deployment or after.

**Comment by slopp** [comment]
I believe reconnect is partially executing this file to attempt to identify package dependencies that may need to be included (it is incorrectly assuming that the RMD will need to be executed at some point on shinyapps.io). You can explicitly avoid this by specifying what files to use as part of the dependency discovery process by calling `deployDoc(..., appFiles = c(...))` yourself.
