### ISSUE TITLE
Unable to publish R Shiny application on R Studio. Getting error as packages missing, Please resolve before continuing.

### ISSUE THREAD

**Issue by pranav-arora** [rstudio/rsconnect#430]
Inside Deploy Window :

Preparing to deploy application...DONE
Uploading bundle for application: 78...Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package foreign
Error: 
* Application depends on package "V8" but it is not installed. Please
   resolve before continuing.

* Application depends on package "crul" but it is not installed.
   Please resolve before continuing.

* Application depends on package "geojson" but it is not installed.
   Please resolve before continuing.

* Application depends on package "geojsonio" but it is not installed.
   Please resolve before continuing.

* Application depends on package "httpcode" but it is not installed.
   Please resolve before continuing.

* Application depends on package "jqr" but it is not installed. Please
   resolve before continuing.

* Application depends on package "maptools" but it is not installed.
   Please resolve before continuing.

* Application depends on package "protolite" but it is not installed.
   Please resolve before continuing.

* Application depends on package "rgeos" but it is not installed.
   Please resolve before continuing.

* Application depends on package "triebeard" 
In addition: There were 29 warnings (use warnings() to see them)
Execution halted

packages being used in the app : 

library(shiny)
library(data.table)
library(shinyjs)
library(shinydashboard)
library(shinycssloaders)
library(shinythemes)
library(shinyWidgets)
library(tools)
library(stringr)
library(stringi)
library(DT)
library(shinyalert)
library(plotly)
library(rhandsontable)
library(lubridate)
library(shinyBS)
library(rlist)
library(GGally)
library(FinCal)
library(shinytoastr)
library(apexcharter)
library(combinat)
library(rjson)
library(fasttime)
library(leaflet)
require(visNetwork)
library(scales)
library(shinybusy)
library(sf)

Any guidance on how to resolve this would be a great help!
Thanks

**Comment by jmcphers** [comment]
This is for reporting bugs in the rsconnect package itself. Please direct requests for assistance with publishing to our community forum:

https://community.rstudio.com/
