### ISSUE TITLE
Problems with files with non-ASCII characters

### ISSUE THREAD

**Issue by colearendt** [rstudio/rsconnect#433]
We have had a report from a customer (ticket 48151) that publishing a bundle that has a non-US-ASCII character in one of the files (it was in the header of a column) will break publishing in a hard-to-detect and hard-to-debug way.

**Comment by emcrisan** [comment]
In this case, the publish button in the IDE failed but the user was able to publish using the `rsconnect::deployApp()` command

The deployment error was: 
`Error in curl::curl_fetch_memory(url, handle = handle) : 
Could not resolve host`

**Comment by colearendt** [comment]
Ahh interesting! I wonder if this is an issue in the IDE then.

**Comment by jmcphers** [comment]
Yep, this is an IDE issue. Could you attach a reproducible example and file an IDE ticket?
