### ISSUE TITLE
Incompatible with older packrat

### ISSUE THREAD

**Issue by rstub** [rstudio/rsconnect#434]
According to the `DESCRIPTION` it should be possible to use current `rsconnect` together with `packrat` 0.4.8-1. However, using this combination for a deployment with a non CRAN package leads to the error 

> Error: Unable to retrieve package records for the following packages:
> - 'non_CRAN_package'

This goes away when `packrat` is updated to the most recent version. See internal support ticket 48697.

**Comment by jmcphers** [comment]
@kevinushey Do you know the true Packrat version on which we depend? (should be as simple as updating `DESCRIPTION`)

**Comment by kevinushey** [comment]
I think we can just depend on Packrat 0.5.0 -- that version is now already a couple years old, and appears to be new enough to resolve that user's issue.
