### ISSUE TITLE
Speed improvements in manifest writing/deployment

### ISSUE THREAD

**Issue by slodge** [rstudio/rsconnect#435]
In our environment we're experiencing a lot of user complaints about how slow RStudio Connect is.

Their current issues mainly seem to be linke with "deployment time" - which I think is mainly down to packrat.

We've made some investigations locally and I've made one suggestion for packrat - see https://github.com/rstudio/packrat/pull/603

I'd also be interested in seeing #404 - as this might help us improve deployment times too.

Are there other things we can try in order to improve performance?

**Comment by aronatkins** [comment]
@slodge - With https://github.com/rstudio/packrat/pull/615, packrat does a much better job at avoiding repeatedly processing the same package dependency. Are you able to test performance against the latest GitHub version of packrat?

**Comment by slodge** [comment]
I did a quick test on a sample app in our Azure Devops CI pipeline:

A build/deployment yesterday included
2021-01-26 16:47:24: Writing manifest for dir apps/ForecastDashboard with
primary:
2021-01-26 16:48:46: Writing manifest complete

The same build today with packrat head is....
2021-01-27 17:48:47: Writing manifest for dir apps/ForecastDashboard with
primary:
2021-01-27 17:48:53: Writing manifest complete

So - 82 seconds down to 6

The app deployed fine (and runs)

The deployment is against RStudio Connect(1.8.0.4-21)

I'll do some more testing tomorrow - I need to do a little fiddling to
quickly update all our build pipelines to the same packrat version. All our
apps are similar - shiny+tidyverse+internal packages - so I'd expect them
to be similar in performance. - but I'll see if I can spot any anomalies.

Thanks!

Stuart

**Comment by slodge** [comment]
More experiments today.

Similar sort of scale of results 
e.g. 1m40 down to  9 seconds

No functional change observed.

These builds are done within "clean" Docker container images so feel quite a solid platform.

**Comment by aronatkins** [comment]
@slodge Thanks so much for those experiments! This feels like enough of an improvement that I'm going to close this issue tracking the underlying performance problem with the packrat dependency analysis. Use of renv by rsconnect is tracked separately (including #471).
