### ISSUE TITLE
deployments using older versions of foreign package produce spurious warnings

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rsconnect#436]
When rsconnect checks to see whether a package is available on CRAN, it does so by checking whether the latest-available version of that package is available on CRAN:

https://github.com/rstudio/rsconnect/blob/40c162bf3c4cd9b10deed82e1df9ec1b0c107c1f/R/dependencies.R#L83

However, the default filters (which define an inclusion / exclusion criteria for the packages returned by `available.packages()`) are left on. From `?available.packages`:

> Argument filters can be used to select which of the packages on the repositories are reported. It is called with its default value (NULL) by functions such as install.packages: this value corresponds to getOption("available_packages_filters") and to c("R_version", "OS_type", "subarch", "duplicates") if that is unset or set to NULL.
> 
> The built-in filters are
> 
> "R_version"
> Exclude packages whose R version requirements are not met.
> 
> < ... snip ... >

The current source version of `foreign` requires R 4.0.0:

```
> db <- available.packages(type = "source")
> db["foreign", "Depends"]
[1] "R (>= 4.0.0)"
```

which implies that the aforementioned check would fail to see that `foreign` is a package available on CRAN, if the current version of R were older than 4.0.0.

Since this is ultimately just a warning, we could relax this check by removing the filters used by `available.packages()`.

**Comment by jmcphers** [comment]
Does https://github.com/rstudio/rsconnect/pull/432 address this?

**Comment by kevinushey** [comment]
Yes, I believe so!

**Comment by jmcphers** [comment]
Fixed by #432

**Comment by ronblum** [comment]
@jmcphers and/or @kevinushey I'm trying to reproduce this in the current CRAN version of `rsconnect`. Is the `foreign` package special to publishing to Connect, or is it just an example of a package that I would use in the Rmd?

**Comment by kevinushey** [comment]
This is specifically for any R package for which the latest-available source package requires R (>= 4.0.0); `foreign` is just one example of such a package: https://cran.r-project.org/web/packages/foreign/index.html

XML is another example: https://cran.r-project.org/web/packages/XML/index.html

**Comment by ronblum** [comment]
@kevinushey Thanks! I'll try out these packages with R 3.6.3 first.

**Comment by ronblum** [comment]
Verified by using `foreign` on 3.6.3. Deployment happened cleanly with no errors.

[All thanks to @kevinushey for walking me through the reprex, etc.]
