### ISSUE TITLE
Tar files incompatible with Connect when UIDs are large

### ISSUE THREAD

**Issue by jskress** [rstudio/rsconnect#438]
When `rsconnect` is used to bundle content to upload to Connect and a large UID is in play (larger than 32K), the tar file created cannot be read by Connect.

The `rsconnect` code creates a temporary file to write to and passes this to the R `utils::tar` function (see `R/bundle.R`, line 238).  That function (in the core R library) takes one of two paths.  If the tar file passed is a string it will invoke the OS's `tar` utility.  Otherwise (as in this case), it will build the tar file in the R code.

If you look in `src/library/utils/R/tar.R`, line 479, you'll see where the R code deliberately mangles large UIDs.

One possible workaround would be for `rsconnect` to create the temp file, immediately close it and pass it **by name** to `utils::tar()` but that could have all sorts of interesting and possibly unpleasant side effects.  Would it work on Windows?  It might if installing R also installed a `tar` executable...

**Comment by scottmmjackson** [comment]
`utils::tar` source: https://github.com/wch/r-source/blob/trunk/src/library/utils/R/tar.R#L479

`rsconnect` source where we call `tar()` (also present in `rpubs.R`): https://github.com/rstudio/rsconnect/blob/70ffe8395153f4da7280c4b7225a87c478feac7f/R/bundle.R#L238

NOTE: As MRO is a fork of R, it has the same issue:

https://github.com/microsoft/microsoft-r-open/blob/a466211a517d281b088d3f5db859b4872383e77b/source/src/library/utils/R/tar.R#L479

**Comment by kevinushey** [comment]
Are you seeing this issue specifically on Windows, or on other operating systems as well?

We could just default to using the system's `tar` executable, if available. Windows 10 even provides `tar.exe` now (based off of `bsdtar` IIUC)

**Comment by jskress** [comment]
It's on all platforms.  Because `reconnect` passes a file handle, the R code is used and that (incorrectly) chops large UID values.

**Comment by gaborcsardi** [comment]
```r
  bundlePath <- tempfile("rsconnect-bundle", fileext = ".tar.gz") 
  utils::tar(bundlePath, files = ".", compression = "gzip", tar = "internal") 
```

I think here `bundlePath` is a file name, not a file handle and you specifically request the internal R tar with `tar = "internal"`, no?

This said, external Windows tars often have their own issues, so I am not sure if it is safe to default to that.

**Comment by jskress** [comment]
Ah, my mistake.  You are correct that `rsconnect` is passing in the file name and not a handle.  You are also correct about `internal`; this also triggers the use of R code rather than an external `tar` executable.  So the upshot is that `rsconnect` is still going down the errant path.

Maybe `rsconnect` also needs the silly workaround?  Maybe look for a `tar` executable in the current system path and pass `internal` for `tar` only if one is **not** found?  If one is not found **and** the UID involved is too big, `rsconnect` could also stop with an error saying that under those conditions a usable tar file cannot be built?

**Comment by aronatkins** [comment]
Closing this issue for now. We believe that the truncation was with long user/group names, not with high UID/GID. See https://github.com/rstudio/rsconnect/issues/446.
