### ISSUE TITLE
I cannot connect to shinyapps.io Publishing Account in R Studio. I see an error.

### ISSUE THREAD

**Issue by akhabhishek** [rstudio/rsconnect#440]
I am not able to connect to my Publishing account on R studio. 
1. I go to the path Tools -> Global Options -> Publishing -> Connect
2. I choose ShinyApps.io and I paste the command that I copied from shinyapps.io dashboard (command from STEP 2 – AUTHORIZE ACCOUNT)
3. I click on Connect Account but I see the error seen in the screenshot.
4. I tried connecting from R Studio Console using rsconnect::setAccountInfo(name, token, secret) and I got the error "**Error in rbind(info, getNamespaceInfo(env, "S3methods")) : 
  number of columns of matrices must match (see arg 2)**" 

I checked the thread #284 and tried connecting by disabling Firewall. It did not work.

I have tried looking online for trouble shooting steps but I could not understand what the actual issue is.
Can you please help me?

I am using **R studio Version 1.3.959** and **R version 3.5.2**

[
![RDeploy](https://user-images.githubusercontent.com/63659774/87030071-b58d1f00-c1fe-11ea-90cf-3f57d0025313.png)
](url)

**Comment by kevinushey** [comment]
```
"Error in rbind(info, getNamespaceInfo(env, "S3methods")) :
number of columns of matrices must match (see arg 2)"
```

This usually means you need to reinstall your R packages. See for instance:

https://github.com/tidyverse/tidyverse/issues/179

**Comment by akhabhishek** [comment]
I uninstalled R, R Studio, Rtools and deleted all the old packages. I then reinstalled all these and it worked. Thank you.
