### ISSUE TITLE
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 while using SNPediaR package in R

### ISSUE THREAD

**Issue by maryshick** [rstudio/rsconnect#443]
Hey everyone!

I need to get all SNPs from SNPedia server. The R package 'SNPediaR' allows you to do that. This is what I actually want to download: https://www.snpedia.com/index.php/Category:In_dbSNP.

I tried this function in Rstudio:
      >res <- getCategoryElements(category = ":In_dbSNP")
      >head(res)
this is what it says:
      Error in function (type, msg, asError = TRUE)  
      :error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

If you have any suggestions, please, don't hesitate to write them. I'd appreciate any help!

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in the rsconnect package itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
