### ISSUE TITLE
File Size for Deploying project bundle to shinyapps.io || Rsconnect issue

### ISSUE THREAD

**Issue by aayushdua007** [rstudio/rsconnect#449]
Hi I was looking through an issue which mentioned that if I want to deploy a project with size greater than 1gb, then I could write -  rsconnect.max.bundle.size=3145728000, which will specify the file size limit to 3gb.

Where do I actually write this "options(rsconnect.max.bundle.size=3145728000)" code? I have app.r and .Rprofile files. Any help would be appreciated. Thanks.

I am using Basic plan on shinyapps.io.

**Comment by jmcphers** [comment]
This goes in `.rsconnect_profile`. See `?rsconnect::rsconnectOptions` for details.

**Comment by aayushdua007** [comment]
Thank you for your quick help on this. I also have another issue related to this, where my file number limit for project is exceeding 10000 which is the default limit in rsconnect. I tried researching about it, and found the file size limit can be increased till 5gb for basic plan on shinyapps.io but there is nothing mentioned about upto what limit can be specified in terms of file number. The code for this is:

 rsconnect.max.bundle.files=10000

I dont want to put a much higher number since then it always crashes after taking so long to deploy. Hence it would really help to know upto how much can we increase our file number limit on basic plan in shinyapps.io.

Thanks again.

**Comment by jmcphers** [comment]
That'd be a great question for our community forum: https://community.rstudio.com/c/shiny/shinyappsio/24
