### ISSUE TITLE
Test for license compatibility before deploying

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#453]
via @ajmcoqui in https://app.prodpad.com/ideas/197/canvas:

> When a user tries to deploy a piece of content that is not enabled, the deployment process first checks that the destination server has that feature enabled, and aborts the deployment with an informative message at the beginning of the process (not the end).

This applies to e.g., plumber APIs.

**Comment by aronatkins** [comment]
Connect errs early during deployment when APIs (or other content types) are disabled either by configuration or licensing.

* The RStudio IDE with `rsconnect` creates the bundle and uploads to Connect.
* Connect unpacks the bundle and reads the `manifest.json`.
* Deployment errs.

We do not install packages, execute the content, or take other actions.

The output presented in the RStudio IDE deploy pane:

```
Preparing to deploy api...DONE
Uploading bundle for api: 541...DONE
Deploying bundle: 867 for api: 541 ...
Api deployment failed with error: API applications are not permitted by your license.
```
