### ISSUE TITLE
ERROR: No matching distribution found for dash (from -r python/requirements.txt (line 1))

### ISSUE THREAD

**Issue by cmougan** [rstudio/rsconnect#454]
I am trying to deploy a dash application in an Rconnect server.

The command that I run 
`rsconnect deploy dash --server https://d-publish.space.tadnet.net/ --api-key XXXXXXXXX ./`

I have the requirements.txt file with the required packages. (I am using the demo example provided in Rconnect
`
(base) C:\Users\navarra\Desktop\shin-exp>rsconnect deploy dash --server https://d-publish.space.tadnet.net/ --api-key XXXXXXX ./
Checking arguments...                            [OK]
    Deploying ./ to server "https://d-publish.space.tadnet.net/"
Inspecting Python environment...                 [OK]
Checking server capabilities...                  [OK]
Creating deployment bundle...                    [OK]
Uploading bundle...                              [OK]
Saving deployment data...                        [OK]

Deployment log:
Building Dash application...
Bundle requested Python version 3.8.3; using /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8 which has version 3.8.1
2020/09/11 14:54:18.676302791 arguments: /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8 /opt/rstudio-connect/python/build_environment.py
2020/09/11 14:54:18.676416247
2020/09/11 14:54:19.850185144
2020/09/11 14:54:19.850219788 CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
2020/09/11 14:54:19.850268212 To initialize your shell, run
2020/09/11 14:54:19.850277955
2020/09/11 14:54:19.850288018     $ conda init <SHELL_NAME>
2020/09/11 14:54:19.850288852
2020/09/11 14:54:19.850296682 Currently supported shells are:
2020/09/11 14:54:19.850297378   - bash
2020/09/11 14:54:19.850305461   - fish
2020/09/11 14:54:19.850306173   - tcsh
2020/09/11 14:54:19.850313875   - xonsh
2020/09/11 14:54:19.850314592   - zsh
2020/09/11 14:54:19.850322471   - powershell
2020/09/11 14:54:19.850323180
2020/09/11 14:54:19.850330786 See 'conda init --help' for more information and options.
2020/09/11 14:54:19.850331771
2020/09/11 14:54:19.850339698 IMPORTANT: You may need to close and restart your shell after running 'conda init'.
2020/09/11 14:54:19.850340459
2020/09/11 14:54:19.850348348
2020/09/11 14:54:20.168707638 Running on host: spaxd101.ecbt1.tadnet.net
2020/09/11 14:54:20.168762784 Environment will be built with Python "3.8.1 (default, Jan  8 2020, 22:29:32)  [GCC 7.3.0]" at /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8
2020/09/11 14:54:20.168834180 Running as user: rstudio-connect
2020/09/11 14:54:20.169646662 Creating environment: DapjfCPbZS_XoadVobfS8A
2020/09/11 14:54:21.061780160 created virtual environment CPython3.8.1.final.0-64 in 551ms
2020/09/11 14:54:21.061793682   creator CPython3Posix(dest=/opt/rstudio-connect/mnt/python-environments/pip/3.8.1/DapjfCPbZS_XoadVobfS8A, clear=False, global=True)
2020/09/11 14:54:21.061842154   seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/rstudio-connect/.local/share/virtualenv/seed-app-data/v1.0.1)
2020/09/11 14:54:21.061847197   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
2020/09/11 14:54:23.766340540 ERROR: Could not find a version that satisfies the requirement dash (from -r python/requirements.txt (line 1)) (from versions: none)
2020/09/11 14:54:23.766807478 ERROR: No matching distribution found for dash (from -r python/requirements.txt (line 1))
2020/09/11 14:54:23.857178192 pip install failed with exit code 1
Build error: exit status 1
Error: Task exited with status 1.
`

If I change to whatever in the requirements package, I still get the same errors there.

**Comment by slopp** [comment]
Sorry for the trouble!

Not sure if this is a red herring or related to the error, but it appears you are attempting to use python from within a conda environment, which isn't working. I'd recommend installing Python on the Connect server following these instructions: https://docs.rstudio.com/resources/install-python/

This repository us for the R rsconnect package, [rsconnect-python](https://github.com/rstudio/rsconnect-python) is the tool you're using. Either way, the best way to get help for this type of problem is to email support@rstudio.com.
