### ISSUE TITLE
Shinyapps.io, Python 3.5 no longer mantained

### ISSUE THREAD

**Issue by mfumagalli68** [rstudio/rsconnect#456]
Hi, 

FIrst of all thank for your work.

I have a question regarding Python in shinyapps.io.
I have a customer to whom I'll ship in a couple of weeks an application developed with R an Python, deployed with `rsconnect` on shinyapps.io.
At the moment shinyapps.io has installed python 3.5.

Python 3.5 reached end of his life 13th Sept, 2020.
There's a plan to upgrade Python? At which version?

Thanks.

**Comment by jmcphers** [comment]
Thanks for reaching out! This repo is for issues with the rsconnect package itself. You might try our shinyapps.io forum: https://community.rstudio.com/c/shiny/shinyappsio/24
