### ISSUE TITLE
Allow account configuration without manual confirmation

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#46]
It would be awesome if we had a way of fully linking `rsconnect` to the server without requiring a browser to be launched and a confirmation click.

This would enable a bunch of test automation.

**Comment by fereshtehRS** [comment]
+1

**Comment by jmcphers** [comment]
This will happen when we do the work in https://github.com/rstudio/rsconnect/issues/269 (which will enable linking using API keys).
