### ISSUE TITLE
have trouble in uploading my app to shinyapps.io

### ISSUE THREAD

**Issue by jarvis9765** [rstudio/rsconnect#470]
my head blow up...
I write a simple shinyapp by using DynNom,  everything works fine locally; but when it comes to uploading to the shinyapps.io ,it says that:
An error has occurred
the application failed to start (exited with code 1)
Error in value:[[3L]]（cond）:无法改变工作目录
calls：local...tryCatch<-tryCatchList<-tryCatchOne<-Anonymous
停止执行
and this is my code:

library(shiny)
library(DynNom)
library(survival)
rt=read.table("lung(1).txt",sep="",header=T,row.names=1,check.names=F)
rt$sex<-factor(rt$sex,labels=c("male","female"))
fit1 <-coxph(Surv(time, status) ~age+meal.cal+sex+wt.loss,data = rt)
DynNom(fit1,DNxlab = "Survival probability",
       KMtitle="Kaplan-Meier plot", 
       KMxlab = "Time (Days)", 
       KMylab = "Survival probability")
DNbuilder(fit1)

My dataset(lung(1)) is put in the same file as app.R, this code runs good locally. Hope to get your help!

**Comment by jarvis9765** [comment]
P.S.
无法改变工作目录：means "Unable to change working directory"
停止执行：means “stop execution”

**Comment by kippandrew** [comment]
Please report shinyapps.io issues to the RStudio Community site: https://community.rstudio.com/tag/shinyappsio

You may also open a ticket with support if you have a paid plan for shinyapps.io.

**Comment by jarvis9765** [comment]
Hi&nbsp; Andy, I am a college student in China, and recently I've been working on this :

I write a simple shinyapp by using DynNom, everything works fine locally; but when it comes to uploading to the shinyapps.io ,it says that:

载入需要的程辑包：magrittr&nbsp;

载入程辑包：‘DynNom’&nbsp;

The following objects are masked _by_ ‘.GlobalEnv’: getclass.DN, getpred.DN&nbsp;

Error in value[[3L]](cond) : Can't call `runApp()` from within `runApp()`. If your application code contains `runApp()`, please remove it.&nbsp;

Calls: local ... tryCatch -&gt; tryCatchList -&gt; tryCatchOne -&gt; <Anonymous&gt; 停止执行

and this is my code:

library(shiny)
library(DynNom)
library(survival)
rt=read.table("lung(1).txt",sep="",header=T,row.names=1,check.names=F)
rt$sex<-factor(rt$sex,labels=c("male","female"))
fit1 <-coxph(Surv(time, status) ~age+meal.cal+sex+wt.loss,data = rt)
DynNom(fit1,DNxlab = "Survival probability",
KMtitle="Kaplan-Meier plot",
KMxlab = "Time (Days)",
KMylab = "Survival probability")
DNbuilder(fit1)

My dataset(lung(1)) is put in the same file as app.R, this code runs well locally. Hope to get your help!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rstudio/rsconnect"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 凌晨0:12
收件人:&nbsp;"rstudio/rsconnect"<rsconnect@noreply.github.com&gt;;
抄送:&nbsp;"赵启迪"<1184869766@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rstudio/rsconnect] have trouble in uploading my app to shinyapps.io (#470)





 
Closed #470.
