### ISSUE TITLE
Republish button doesn't appear after deploying an Rmd with deployApp

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rsconnect#474]
`deployApp()` is a valid way of deploying Rmd documents but after deploying an Rmd with `deployApp()`, the deploy button doesn't change from Publish to Republish. It does change if you use `deployDoc()` instead, which presumably means running `deployApp()` with certain arguments specified would work as well. I think it would be good if the button changed regardless of which function is used to deploy the document.

I stumbled upon this as I was using `deployApp()` to deploy an Rmds with runtime `shiny` and `shiny_prerendered`, e.g. learnr tutorial.

**Comment by jmcphers** [comment]
This is by design; if you call `deployApp` you are deploying a directory, and there is no way for the IDE to know which doc you deployed. If you specify the Rmd in the `appPrimaryDoc` argument to `deployApp`, you should see the IDE adapting as you expect.

What do your `deployApp` commands look like? (Maybe we could infer `appPrimaryDoc`?)

**Comment by mine-cetinkaya-rundel** [comment]
I generally have one Rmd document (learnr tutorial) per folder, and my `deployApp()` command looks like the following:

```r
  deployApp(
    appDir = PATH/TO/FOLDER,
    appTitle = "APP TITLE",
    account = "ACCOUNT_NAME",
    forceUpdate = TRUE,
    launch.browser = FALSE
  )
```

I suppose, without being very intentional about it, I was relying on `deployApp()` to infer `appPrimaryDoc` and it gets it right since there is always one Rmd in the folder.

**Comment by hadley** [comment]
The distinction between publishing an app (even if it contains a single doc) and publishing a doc, is quite heavily baked into rsconnect, and I think it would be hard to change now.

For your workflow, you might try switching to `deployDoc()`.
