### ISSUE TITLE
problem with async shiny apps

### ISSUE THREAD

**Issue by asalavaty** [rstudio/rsconnect#488]
Hi,

I have a shiny app that I transformed one of its expensive functions into an async one. The app works fine on my local machine (Mac) as well as shinyapps.io server in NON-async format. It also works perfectly in async format on my local machine but not on the shinyapps.io server.

Here's my app address: https://asalavaty.shinyapps.io/IVI_Shiny_app/

I would appreciate any help.

**Comment by akshaybholee** [comment]
Hello asalavaty. How did you solve this issue?
