### ISSUE TITLE
suggest API keys on FIPS digest errors

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#489]
Calls to `rsconnect::generateToken` can fail to generate an RSA key on FIPS-enabled servers. See https://github.com/rstudio/rsconnect/issues/452 for examples.

Let's trap the OpenSSL digest error and rewrite it to suggest that folks use API keys, per https://github.com/rstudio/rsconnect/issues/452#issuecomment-684016227.

**Comment by jmcphers** [comment]
Good idea.
