### ISSUE TITLE
rsconnect::applications() fails because shinyapps API may not return consistent output format

### ISSUE THREAD

**Issue by jfunction** [rstudio/rsconnect#495]
I called rsconnect::applications() and got an error:
```
Error in rbind.data.frame(..., stringsAsFactors = FALSE) : 
  numbers of columns of arguments do not match
```

The error is triggered at https://github.com/rstudio/rsconnect/blob/master/R/applications.R#L111 because the data coming back from /applications/ endpoint does not include the `size` attribute. This may be symptomatic of a more general problem and it may be an issue with the API rather than rsconnect but wanted to mention the issue regardless for someone to take further. 

Here is the data structure parsed from the endpoint for my application (I can share a non-redacted version with an rstudio employee if needed):

```
$id
[1] {REDACTED}

$name
[1] "kelchVis"

$url
[1] "https://{REDACTED}.shinyapps.io/kelchVis/"

$status
[1] "pending"

$created_time
[1] "2020-10-20T07:04:25"

$updated_time
[1] "2020-10-20T07:04:25"

$instances
[1] NA

$guid
[1] NA```

**Comment by aronatkins** [comment]
I was able to see the same problem using my shinyapps.io account. Could you try https://github.com/rstudio/rsconnect/pull/496? It should resolve this problem.
