### ISSUE TITLE
CRAN says rsconnect and reverse dependencies will be archived soon

### ISSUE THREAD

**Issue by jgabry** [rstudio/rsconnect#497]
I received the following email from CRAN because the shinystan package I maintain uses `rsconnect::deployApp()`: 

> We have repeatedly asked for an update making package rsconnect comply
> with the CRAN Policy, with no reply from the maintainer thus far.
> 
> Thus, package rsconnect is now scheduled for archival on 2021-04-12,
> and archiving this will necessitate also archiving its strong reverse
> dependencies.
> 
> Please negotiate the necessary actions.

Are you planning on submitting a version of rsconnect that complies with CRAN policies before the deadline? If not I will have to modify my package to not use rsconnect, which is ok but I would rather not do that if you plan of fixing rsconnect. Please advise, thanks!

**Comment by jmcphers** [comment]
I have not received any notices of CRAN policy violations. It's possible that they've been automatically discarded by my spam filter. I will get in touch with the CRAN maintainer.

**Comment by jgabry** [comment]
Thanks, yeah it could be a spam filter issue, that's happened to me before with CRAN emails. In case it helps you find it the most recent email I received was 2 days ago from Kurt Hornik and it had subject "CRAN package rsconnect and its reverse dependencies". It looks like jonathan at rstudio.com is included among the recipients.

**Comment by jmcphers** [comment]
rsconnect 0.8.17 is now on CRAN! https://cran.r-project.org/web/packages/rsconnect/index.html

**Comment by jgabry** [comment]
Awesome, thanks!
