### ISSUE TITLE
Packages in funny places aren't captured

### ISSUE THREAD

**Issue by akgold** [rstudio/rsconnect#499]
Two cases where required packages aren't captured:
1) If the package is only used to set default arguments in function definitions.
2) If the package is only used inside a `glue` string.

Neither the `here` nor the `scales` packages are captured for the code below:
```
my_fn <- function(x = here::here) {
   x
}

glue::glue("{scales::dollar(100)")
````

I've tar-ed and attached a project with this code and a working `renv` environment, so the code runs interactively, but dependencies aren't captured by `rsconnect` (probably actually `packrat`?).

[rstudio-export.zip](https://github.com/rstudio/rsconnect/files/6259895/rstudio-export.zip)

**Comment by aronatkins** [comment]
This is a packrat issue with dependency detection.

Given a plain directory containing the R Markdown document:

````markdown
---
title: "Untitled"
---

```{r}
here <- function(x = here::here()) {
  x
}
here()


glue::glue("{scales::dollar(100)}")
```
````

`packrat` sees the following dependencies:

```r
packrat:::dirDependencies(".")
# => [1] "rmarkdown" "glue"     
```

`renv` sees the following dependencies:

```r
renv::dependencies(".")
# => Finding R package dependencies ... Done!
# =>                                              Source   Package Require Version   Dev
# => 1 /.../test_rmd.Rmd rmarkdown                 FALSE
# => 2 /.../test_rmd.Rmd      glue                 FALSE
# => 3 /.../test_rmd.Rmd      here                 FALSE
```

Neither `packrat` nor `renv` see the `scales` reference that is embedded in a string. The `here` reference is only identified by `renv`.

The workaround for both of these situations is to make your package dependency explicit with a `library` statement.

```r
library("here")
library("scales")
```

**Comment by aronatkins** [comment]
With library statements, both `packrat` and `renv` find the dependencies:

```r
packrat:::dirDependencies(".")
# => [1] "rmarkdown" "here"      "scales"    "glue"     
renv::dependencies(".")
# => Finding R package dependencies ... Done!
# =>                                              Source   Package Require Version   Dev
# => 1 /.../test_rmd.Rmd rmarkdown                 FALSE
# => 2 /.../test_rmd.Rmd      glue                 FALSE
# => 3 /.../test_rmd.Rmd      here                 FALSE
# => 4 /.../test_rmd.Rmd    scales                 FALSE
```

**Comment by akgold** [comment]
Yes -- when I first deployed, I was confused why they weren't captured. Is this worth trying to update in either `packrat` or `renv`?

**Comment by aronatkins** [comment]
It feels like `packrat` should detect the `here` dependency, as that is a code-only dependency.

I'm OK that neither `packrat` nor `renv` automatically detects the `scales` dependency, as that appears to require processing strings to look for package references. I would rather nudge folks towards explicit `library` statements in this case.

CC @kevinushey who may have different thoughts.

**Comment by aronatkins** [comment]
Tracking the lack of a `here` dependency in `packrat` here: https://github.com/rstudio/packrat/issues/630

**Comment by aronatkins** [comment]
Packrat will identify the `here` dependency with https://github.com/rstudio/packrat/pull/631.

Not expanding `packrat` or `renv` to detect the in-string `scales` dependency at this time.
