### ISSUE TITLE
Faster deployments?

### ISSUE THREAD

**Issue by officialpatterson** [rstudio/rsconnect#500]
Currently building a new instance of RSC into our workflows and we're finding first deployments take hours and subsequent deployments are still slow imo - easy around 20 minutes even when using cached packages.

So why is deploying apps to RSC so slow compared to other deploying containers to other containerised environments? and How can we make it faster? (both inside RSC, and speeding up the deployment through RSC configuration)

**Comment by slopp** [comment]
@officialpatterson  I'd recommend following up with a support ticket on this one: https://support.rstudio.com/hc/en-us/requests/new 

We run lots of Connect servers in different architectures and I've never heard of any deployments taking as long as you describe. I doubt it has to do with the rsconnect R package.

A few things that can help speed up Connect deployments:
- Using RStudio Package Manager to provide pre-compiled package binaries
- Using fast shared storage for the Connect data directory

**Comment by slopp** [comment]
One other note, you may try your deployments with the GitHub versions of packrat and rsconnect, there were recent changes that improve the speed of the deployment _on the client_: https://github.com/rstudio/packrat/pull/615

If you are seeing slowness before content is uploaded to Connect in the deployment log, this change should help!

**Comment by aronatkins** [comment]
One update to @slopp's note -- all of the `packrat` performance improvements are now on CRAN with version 0.6.0. Try to see if you see different behavior with the most recent CRAN releases for both `rsconnect` and `packrat`.

```r
install.packages(c("packrat","rsconnect"))
```

**Comment by kevinushey** [comment]
Should the next release of rsconnect bump the required version of Packrat as well? (just to ensure users of rsconnect are always getting the latest and greatest in packrat)

**Comment by aronatkins** [comment]
@kevinushey That's a great call. I'll push an update to ask for packrat 0.6.0.

**Comment by aronatkins** [comment]
Updating packrat dependency in https://github.com/rstudio/rsconnect/pull/501

**Comment by officialpatterson** [comment]
Forgot to say, cheers for the help on this one!
