### ISSUE TITLE
incorrect error message - shiny.R -> server.R

### ISSUE THREAD

**Issue by Polkas** [rstudio/rsconnect#509]
https://github.com/rstudio/rsconnect/blob/c038a64d6d7a1baf596be5c6cdf5c3e2c4e37140/R/lint-framework.R#L129

`shiny.R` should be replaced with `server.R`, check out the next line too. This is very a important error message especially for new users so should be updated quickly .

**Comment by jmcphers** [comment]
Thanks for pointing that out, fixed now!
