### ISSUE TITLE
Error when deploying from R 3.1 and below

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#51]
We call `dir.exists` when building bundles:

https://github.com/rstudio/rsconnect/blob/39740fcbe00a1baffaa9381e3fca604a4f3d7f92/R/bundle.R#L382

This function is new in R 3.2.0.

**Comment by jjallaire** [comment]
We can create a dir_exists function like the rmarkdown package has:

https://github.com/rstudio/rmarkdown/blob/3d46213d750fd4ebb83e73d0df357f081c73f49f/R/util.R#L113-L115

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rsconnect/commit/6b4d42fc56e59e34cb50110be60b9742bd486a61
