### ISSUE TITLE
When calling writeManifest() on empty directory we do not show accurate error message 

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rsconnect#512]
**Pre-requisite:** Install `remotes::install_github("rstudio/rsconnect")`
```
RemoteRepo: rsconnect
RemoteUsername: rstudio
RemoteRef: HEAD
RemoteSha: 692339126802ec61be4a69541d6769f1cfc94c91
```

**Steps:**

1. Create a new project 
2. Do not add any files keep the dir empty 
3. Run `rsconnect::writeManifest()`

**Result:** 
```
 rsconnect::writeManifest()
Error in if ((grepl("rmd", appMode, fixed = TRUE) || appMode == "static") &&  : 
  missing value where TRUE/FALSE needed
```

**Comment by ChaitaC** [comment]
When u call writeManifest() on a sub-directory we do not show an accurate error message
1. Create a new directory
2. Add a shinyapp
3. Notice shiny app is created inside a subdirectory 
4. Now, without changing to sub directory call `rsconnect::writeManifest()`
**Result:** 
```
 rsconnect::writeManifest()
Error in inferAppPrimaryDoc(appPrimaryDoc = appPrimaryDoc, appFiles = appFiles,  : 
  Application mode static requires at least one document.
```

**Comment by aronatkins** [comment]
The first error (with `grepl`) comes from `inferAppPrimaryDoc` and is caused by an `appMode` with `NA` value. That `NA` comes from `inferAppMode` when it cannot determine the kind of content. In this case, we have an empty directory, but this could also happen with a directory containing a collection of files that do not indicate some known type of content.

**Comment by aronatkins** [comment]
It is probably safe to have `inferAppMode` call `stop` if it cannot detect the type of content.

**Comment by aronatkins** [comment]
The second error happened because `bundleFiles` enumerates the `child/app.R` and calls that "static" (since it is an unrecognized set of files).

**Comment by aronatkins** [comment]
I think the second case (static requires documents) is reasonable; addressing the empty-directory / NA issue in #513.
