### ISSUE TITLE
Getting an error from rsconnect while publishing on bookdown.org

### ISSUE THREAD

**Issue by compfinezbook** [rstudio/rsconnect#514]
Hi,

I'm trying to publish a book on bookdown.org but I'm getting an error which I'm unable to debug. After opening the bookdown project through RStudio IDE, I can build the book successfully (bookdown::gitbook). Then I try to publish it by this command but getting an error -

    bookdown::publish_book()
    Error in if (info$isdir) { : missing value where TRUE/FALSE needed

I used traceback() function and found the following message (the problem coming from rsconnect package) -

    traceback()
    5: maxDirectoryList(appDir, 0, 0, 0)
    4: listBundleFiles(appDir)
    3: bundleFiles(siteGenerator$output_dir)
    2: rsconnect::deploySite(siteDir = getwd(), siteName = name, account = account,
    server = server, render = render, logLevel = "normal")
    1: bookdown::publish_book()

My session info are as follow -

    sessionInfo()
    R version 4.0.5 (2021-03-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):
[1] compiler_4.0.5 bookdown_0.22 rsconnect_0.8.19 htmltools_0.5.1.1 tools_4.0.5
[6] yaml_2.2.1 rmarkdown_2.7 knitr_1.33 xfun_0.22 digest_0.6.27
[11] rlang_0.4.10 evaluate_0.14

I'm stuck on this problem and can't make any headway. Can you please help me?

Thanks.

**Comment by jmcphers** [comment]
@aronatkins could you take a look? Looks like this could have been introduced a few months ago in https://github.com/rstudio/rsconnect/commit/b0495c2dfd8ec9175396ea5ef5e991cc6a7b0167.

**Comment by aronatkins** [comment]
The error is coming from this line:

https://github.com/rstudio/rsconnect/blob/067891e54f93dc27f968471945c2fbaf0b1a3c18/R/bundle.R#L103

We are likely seeing `info$isdir` having an `NA` value for some reason.

Would you be able to run the following code from the same directory where you ran `bookdown::publish_book()`.

```r
dir <- rmarkdown::site_generator(".")$output_dir
contents <- list.files(dir, recursive = FALSE, all.files = TRUE, include.dirs = TRUE, no.. = TRUE, full.names = FALSE)
infos <- file.info(file.path(dir, contents), extra_cols = FALSE)
infos
 ```

For reference, here is what I see in my local environment with an example bookdown book:

```
                          size isdir mode               mtime               ctime               atime
_book/applications.html  10356 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/bookdown_files        96  TRUE  755 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:33
_book/final-words.html   10048 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/index.html         11041 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:33
_book/intro.html         16799 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/libs                 192  TRUE  755 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:33
_book/literature.html    10031 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/methods.html       10039 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/reference-keys.txt   114 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:34
_book/references.html    10292 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/search_index.json   2670 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:50
_book/style.css            172 FALSE  644 2021-06-04 17:06:33 2021-06-04 17:06:33 2021-06-04 17:06:34
```

**Comment by aronatkins** [comment]
I've made a change that skips the files that cannot be processed due to permissions problems, allowing deployment to continue. Files with permissions problems are enumerated but do not err the deployment.

A file with permissions problems might be displayed like:

```
Cannot determine file information for _book/intro.html; skipping
```

Could you try this change and let us know if it avoids the reported error?

```r
remotes::install_github("rstudio/rsconnect", ref="aron-issue-514")
```

We believe that there are permissions problems trying to read some of the target bookdown files. Do you know how those files were created? Could you confirm that they are visible to your user?

**Comment by aronatkins** [comment]
Update: After chatting with @jmcphers, we've made an adjustment to our proposed fix. Files which cannot be analyzed by `file.info` are allowed without warning, though not recursed through.

**Comment by compfinezbook** [comment]
Following your suggestion, I printed the infos. The partial output is shown below. One thing which is different (from the output you displayed) for a directory/folder, the size is being shown as zero.  But those folders are not empty. 

```
dir <- rmarkdown::site_generator(".")$output_dir
contents <- list.files(dir, recursive = FALSE, all.files = TRUE, include.dirs = TRUE, no.. = TRUE, full.names = FALSE)
infos <- file.info(file.path(dir, contents), extra_cols = FALSE)
infos
                                                                                      size isdir mode
_book/_bookdown_files                                                                    0  TRUE  777
_book/_main.epub                                                                   1413434 FALSE  666
_book/_main.pdf                                                                    6604952 FALSE  666
_book/_main.tex                                                                    1728193 FALSE  666
_book/01-ReturnCalculations.md                                                      121860 FALSE  666
_book/01-ReturnCalculations_files                                                        0  TRUE  777
_book/02-probReview.md                                                              153429 FALSE  666
_book/02-probReview_files                                                                0  TRUE  777
_book/03-matrixReview.md                                                             80257 FALSE  666
_book/03-matrixReview_files                                                              0  TRUE  777
_book/04-timeSeriesConcepts.md                                                       74143 FALSE  666
_book/04-timeSeriesConcepts_files                                                        0  TRUE  777
_book/05-DescriptiveStatistics.md                                                   114675 FALSE  666
_book/05-DescriptiveStatistics_files                                                     0  TRUE  777
_book/06-CERModel.md                                                                 55379 FALSE  666
_book/06-CERModel_files                                                                  0  TRUE  777
```

I did install and tried to publish the book again.
```
remotes::install_github("rstudio/rsconnect", ref="aron-issue-514")
```

This time I get a slightly different error message

```
> bookdown::publish_book()
Error in if (totalSize > getOption("rsconnect.max.bundle.size")) break : 
  missing value where TRUE/FALSE needed

> traceback()
5: maxDirectoryList(appDir, 0, 0, 0)
4: listBundleFiles(appDir)
3: bundleFiles(siteGenerator$output_dir)
2: rsconnect::deploySite(siteDir = getwd(), siteName = name, account = account, 
       server = server, render = render, logLevel = "normal")
1: bookdown::publish_book()

```

This is a shared project and I joined the team later. The bookdown project repository is on Dropbox and multiple people has access to it. We all can edit the R Markdown files and produce the html pages and pdf without any problem. Is there any YAML config option related to 'permission'? I'm not sure if I'm answering your 'permission' related question correctly.

**Comment by aronatkins** [comment]
Thanks so much for your update. I've adjusted the branch, which should avoid the `totalSize` issue you just observed. Reinstall `rsconnect` using that same command and you'll get past that error.

```r
remotes::install_github("rstudio/rsconnect", ref="aron-issue-514")
```

Additionally, I've added a note to the output in order to determine which files / directories are causing issues. That will look like:

```
File information for _book/bookdown_files is not available; listing as a normal file.
```

Thank you for the additional detail about your bookdown project. The fact that there are multiple people collaborating within a Dropbox folder could be related. The R `file.info` function is documented as returning `NA` values nor non-readable files. It is interesting that the file listing you shared does not include any of the `NA` values that are causing us trouble!

Could you confirm that you are able to completely regenerate the `_book` directory (creating the HTML and PDF)? You should be able to fully rename and/or remove this directory, as it is normally created by `bookdown`.

**Comment by aronatkins** [comment]
One additional note: Because `rsconnect` is unable to analyze some of the files and directories beneath `_book`, it is possible that the resulting deployment will be incomplete.

You can look at the full set of files that are being considered with the call:

```r
rsconnect::listBundleFiles("_book")
```

The output from this function should enumerate everything that will be deployed without attempting the actual deployment.

**Comment by compfinezbook** [comment]
Thank you so much for your help. The author of the book is making minor edits to the book before publishing it again on the bookdown.org. I'll try your suggestions as soon as he is done and give you an update soon.

**Comment by compfinezbook** [comment]
After reinstalling `rsconnect`, I ran this command `rsconnect::listBundleFiles("_book")` and got the following output (displaying only the first five files here)- 
```
> rsconnect::listBundleFiles("_book")
File information for _book/search_index (? Chen Yi-Chi ????? 2021-05-19).json is not available; listing as a normal file.
$totalSize
[1] 38052125

$totalFiles
[1] 586

$contents
  [1] "_bookdown_files/01-ReturnCalculations_files/figure-html/fig-logexp-1.png"                                   
  [2] "_bookdown_files/01-ReturnCalculations_files/figure-html/fig-YhooPlot-1.png"                                 
  [3] "_bookdown_files/01-ReturnCalculations_files/figure-html/figMsftChart-1.png"                                 
  [4] "_bookdown_files/01-ReturnCalculations_files/figure-html/figMsftSbuxGrowthDollar-1.png"                      
  [5] "_bookdown_files/01-ReturnCalculations_files/figure-html/figMsftSbuxPricesZoo-1.png"  
```
I think this file "search_index (? Chen Yi-Chi ????? 2021-05-19).json" was causing the problem. After removing this file, I could publish successfully by running this `bookdown::publish_book()`

Later, I removed the pre-existing"_book" directory from the project folder and built the book again to create a fresh "_book" directory. It worked fine and I could publish the book successfully.

On printing infos, the size of the folders is still being shown as zero but that is not causing any problem as of now. 
```
> dir <- rmarkdown::site_generator(".")$output_dir
> contents <- list.files(dir, recursive = FALSE, all.files = TRUE, include.dirs = TRUE, no.. = TRUE, full.names = FALSE)
> infos <- file.info(file.path(dir, contents), extra_cols = FALSE)
> infos
                                                                                       size isdir mode
_book/01-ReturnCalculations.md                                                       120857 FALSE  666
_book/01-ReturnCalculations_files                                                         0  TRUE  777
_book/02-probReview.md                                                               149980 FALSE  666
_book/02-probReview_files                                                                 0  TRUE  777
_book/03-matrixReview.md                                                              79678 FALSE  666
_book/03-matrixReview_files                                                               0  TRUE  777
_book/04-timeSeriesConcepts.md                                                        72716 FALSE  666
```
