### ISSUE TITLE
Installing to shinyapps.io: namespace ‘sass’ 0.3.1 is being loaded, but >= 0.4.0 is required

### ISSUE THREAD

**Issue by dcousin3** [rstudio/rsconnect#523]
I try to install a Shiny app to shinyapps.io using
```
library(rsconnect)
setwd("C:\\Users\\DenisCousineau\\Repositories")
rsconnect::deployApp('superb/inst/superbShiny')
```
However, the bundle reaches shyniapps.io but returns this error message:
`namespace ‘sass’ 0.3.1 is being loaded, but >= 0.4.0 is required`

I tripled-checked and the version installed on my computer is sass 0.4.0.

Is this error message related to the server shinyapps.io not up-to-date relative to this package? Or is it related to my own installation?

**Comment by kevinushey** [comment]
Can you share the full error you're seeing, just so we can confirm if this is indeed coming from shinyapps.io?

**Comment by dcousin3** [comment]
Hello,

The shiny apps is located at https://dcousin3.shinyapps.io/superbshiny

This is what I obtain:
***@***.***D76960.6F959590]

denis.

De : Kevin Ushey ***@***.***
Envoyé : 25 juin 2021 00:21
À : rstudio/rsconnect
Cc : Denis Cousineau; Author
Objet : Re: [rstudio/rsconnect] Installing to shinyapps.io: namespace ‘sass’ 0.3.1 is being loaded, but >= 0.4.0 is required (#523)

Attention : courriel externe | external email

Can you share the full error you're seeing, just so we can confirm if this is indeed coming from shinyapps.io?

**Comment by dcousin3** [comment]
In your opinion, is it a problem related to shinyapps.io?

**Comment by kevinushey** [comment]
Sorry for the late response. This seems like an issue with shinyapps.io, but I don't know for sure. You might want to raise this with the shinyapps.io team here: https://community.rstudio.com/c/shiny/8

**Comment by dcousin3** [comment]
Many thanks for looking into it.

De : Kevin Ushey ***@***.***
Envoyé : 13 juillet 2021 00:13
À : rstudio/rsconnect
Cc : Denis Cousineau; Author
Objet : Re: [rstudio/rsconnect] Installing to shinyapps.io: namespace ‘sass’ 0.3.1 is being loaded, but >= 0.4.0 is required (#523)

Attention : courriel externe | external email

Sorry for the late response. This seems like an issue with shinyapps.io, but I don't know for sure. You might want to raise this with the shinyapps.io team here: https://community.rstudio.com/c/shiny/8
