### ISSUE TITLE
Allow `rsconnect::writeManifest()` specify path to `primary_html`

### ISSUE THREAD

**Issue by elong0527** [rstudio/rsconnect#525]
I would like to create a `mainifest.json` file to deploy distill website to RStudio connect. 

To enable it, I will need to define location of `primary_html` manually in `mainifest.json`  after using
 
```
rsconnect::writeManifest(appPrimaryDoc = "index.rmd", contentCategory = "site")
```

Default: 
```  
"primary_html": null
```

Updated: 
```  
"primary_html": "docs/index.html"
```

**Comment by hadley** [comment]
I just published a distill site with `deploySite()` and didn't have any problems.
