### ISSUE TITLE
Is is possible to deploy a shiny app object "shiny.appobj."

### ISSUE THREAD

**Issue by christianholland** [rstudio/rsconnect#533]
Hi there,

is it possible to deploy a shiny app object with `rsconnect` on `shinyapps.io`?

I would image something like this, but this does (of course) not work since the argument appDir `must be a single element character vector`
```
library(shiny)
ui <- fluidPage(
  "Hello, world!"
)
server <- function(input, output, session) {
}
app <- shinyApp(ui, server)

rsconnect::deployApp(app)
```

Thank you for your support,
Christian

**Comment by aronatkins** [comment]
Thanks for the question. No, it is not possible to deploy an application object using `rsconnect`. You'll need to deploy the code for your application, along with any supporting files (images, data, etc.) required by the application.

Most folks will start deploying to `shinyapps.io` using an approach like the following:

1. Create a directory to contain this Shiny application; let's call it `hello-world`.
2. Write an `hello-world/app.R` with the contents of your application.
3. Use `rsconnect::deployApp` or the blue "publish" icon in the RStudio IDE.

Your `app.R` file would contain the application definition:

```r
# hello-world/app.R application code
library(shiny)
ui <- fluidPage(
  "Hello, world!"
)
server <- function(input, output, session) {
}
shinyApp(ui, server)
```

The RStudio Community has a shinyapps.io category that might be helpful, as well. https://community.rstudio.com/c/shiny/shinyappsio/24
