### ISSUE TITLE
Add an option to require unique app names

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/rsconnect#538]
Our app name generator allows an operation mode wherein unique app names are required:

https://github.com/rstudio/rsconnect/blob/main/R/title.R#L32

However, every call site for this function in `deployApp` passes "FALSE" to that parameter.

We should add an option to permit changing this behavior such that non-unique names produce deployment errors.

**Comment by hadley** [comment]
If we're automatically generating the app name, shouldn't we always make it unique? i.e. is there some reason we need to make this a user facing argument?

**Comment by aronatkins** [comment]
The only remaining exception is bookdown.org, which uses the content name to automatically construct its vanity URL. See `bookdown::publish_book`

**Comment by hadley** [comment]
And it occurs to me that the default `appName` should probably use `appPrimaryDoc` if set.  Currently if you're publishing a bunch of individual documents from a common directory, they'll all have the same default `appName`.

**Comment by hadley** [comment]
Oooh, but it does, implicitly, because `generateAppName()` is passed `recordPath`, not `appDir`.
