### ISSUE TITLE
Incorrect content_category set by rsconnect::writeManifest() for Bookdown when published via git

### ISSUE THREAD

**Issue by aja08379** [rstudio/rsconnect#539]
From related customer support ticket:

I found out that for some reason `rsconnect::writeManifest()` doesn't set the proper content_category to the manifest generated, it is showing up as `content_category: null`, and should be `site` instead of `null`.

The customer can change this directly in the `manifest.json`, push the change to the repo and deploy again; that should work.

**Comment by aronatkins** [comment]
Neither `rsconnect::deployApp` nor `rsconnect::writeManifest` automatically determine if the target content needs content category. We probably could detect things that look like sites, but that is not done today.

The `bookdown::publish_book` function calls `rsconnect::deploySite`, which forces a content category of "site". This can be accomplished using `rsconnect::writeManifest` with the following:

```r
rsconnect::writeManifest(contentCategory = "site")
```

**Comment by hadley** [comment]
For now, I think you could just encourage the customer to use `deploySite()`.

**Comment by hadley** [comment]
Oh I missed the important qualifier that this is with publishing with manifect + git.
