### ISSUE TITLE
deployApp creates an empty "shinyapps" directory

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#54]
Using rsconnect 0.4.1.2

Using deployApp() command, or deploying from the Publish button, an empty directory called "shinyapps" is created. This is regardless of the publish destination.

The actual deploy (dcf) files are in the "rsconnect" directory.

**Comment by jjallaire** [comment]
It looks like for all app deployments we call:

authorizedUsers -> getPasswordFile

Which leads to this code:

https://github.com/rstudio/rsconnect/blob/master/R/auth.R#L249-L252

which is what in turn creates the directory.

I'll work on a PR to prevent this....

**Comment by jjallaire** [comment]
PR here: https://github.com/rstudio/rsconnect/pull/55

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rsconnect/pull/55
