### ISSUE TITLE
How to convert `manifest.json` file to `packrat.lock` or `renv.lock` file

### ISSUE THREAD

**Issue by elong0527** [rstudio/rsconnect#541]
In a CI/CD pipeline, we need to restore R packages from `manifest.json` using packrat. 

I tried `rsconnect:::addPackratSnapshot(".")` but it seems not use `manifest.json` as source.

Could you guide a proper way to transfer `manifest.json` to `packrat.lock` or `renv.lock` file? 

In addition, the `renv:::renv_lockfile_from_manifest` seems have bugs. 

https://github.com/rstudio/renv/issues/832

**Comment by hadley** [comment]
I believe the `manifest.json` is primarily for our internal use, and not something we expect others to use.
