### ISSUE TITLE
rsconnect profile options ignored

### ISSUE THREAD

**Issue by JsizzleR** [rstudio/rsconnect#542]
When using rsconnect version 0.8.24, the settings in these files aren't taking effect:

```
$R_HOME/etc/rsconnect.site
~/.rsconnect_profile
$PROJECT/.rsconnect_profile
```

The two settings used were:

```
options(rsconnect.check.certificate = FALSE)
options(rsconnect.max.bundle.size = 5000000000)
```

Downgrading to the previous version used, 0.8.16, resolved the issue.

**Comment by aronatkins** [comment]
Using the 0.8.24 CRAN release of this package and `.rsconnect_profile` files in my home directory and project directory:

```r
# saved as $HOME/.rsconnect_profile
cat("ATTENTION: This is the HOME/.rsconnect_profile\n")
```

```r
# saved as PROJECT/.rsconnect_profile
cat("ATTENTION: This is the PROJECT/.rsconnect_profile\n")
options(rsconnect.max.bundle.size = 10)
```

A call to the `rsconnect::deployApp` function shows that the max bundle size is in effect:

``` r
rsconnect::deployApp(server = "SERVER-NAME", account = "ACCOUNT-NAME")
#> ATTENTION: This is the HOME/.rsconnect_profile
#> ATTENTION: This is the PROJECT/.rsconnect_profile
#> Error in bundleFiles(appDir): The directory /Users/aron/dev/rstudio/standalone/shiny-rsconnect-site cannot be deployed because it is too large (the maximum size is 10 bytes). Remove some files or adjust the rsconnect.max.bundle.size option.
```

The bundle size is not enforced, however, when specifying an enumerated set of files; this is the path often used by the RStudio IDE when deploying content.

```r
rsconnect::deployApp(server = "rsc.radixu.com", account = "aron", appFiles=c("app.R"))
#> ATTENTION: This is the HOME/.rsconnect_profile
#> ATTENTION: This is the PROJECT/.rsconnect_profile
#> ... deployment succeeds ...
```

The same behavior is seen with rsconnect-0.8.16.

**Comment by hadley** [comment]
@aronatkins in `runStartupScripts()` what do you think about logging the script being run when `logLevel %in% c("normal", "verbose")`? I think this is important enough to message about by default.

**Comment by aronatkins** [comment]
@hadley - more logging feels right, yes. Should the `source` parse into a named environment rather than global?

**Comment by hadley** [comment]
@aronatkins yeah, it should. And I don't think changing it to the correct default should affect existing code, since this all needs to be "side-effect"y code anyway.
