### ISSUE TITLE
Get pending invitation links from the library

### ISSUE THREAD

**Issue by durey** [rstudio/rsconnect#543]
We can currently invite users to an app using the the library, but, AFAIK, it is not possible to retrieve the invitation link after that. In case a user is already invited, we are forced to go to the web console manually to get the invitation link.

It would be REALLY appreciated to be allowed to retrieve invitation links from the library.

**Comment by durey** [comment]
Apparently, the `showInvited()` method returns the invitation links, but these links are only functional for the first 7 days after users were invited. From the 8th day to the 21th, links become expired and finally users get deleted. During these 14 days, we are forced to go manually and click the "Resend" button in the console.

Taking all that into account, I think that it would be great to have these new 2 features in `rsconnect`:

1. Another boolean field returned by `showInvited()` stating if the invitation link is still functional (first 7 days) or if it expired (following 14 days from then until the user gets deleted).
2. Another method in `rsconnect` to be able to perform the behaviour of the "Resend" button programmatically.

OR, on the other hand, wouldn't be this much easier?

1. The ability to programmatically change the expiration days threshold for invited users. That way we could set that, after 7 days, the user gets deleted instead of becoming expired. Programmatically we could just add them again, and programmatically we could retrieve the invitation link if needed. All problems would be solved. In summary, is the fact that invited users become expired after 7 days until removed after 21 days what is causing troubles, isn't it?

**Comment by durey** [comment]
A third possible approach (a less desired workaround):

1. The ability to programmatically remove invited users (currently, we can only remove accepted users).

That way, we could remove pending invited users after 6 days and add them programmatically right after. That way we could skip the 14 days of expired invitation links.

**Comment by kippandrew** [comment]
Thanks for the suggestions. All of these ideas are supported by the underlying shinyapps.io API, so they could be implemented fairly easily in the `rsconnect` package.

**Comment by durey** [comment]
@kippandrew , could be anyone interested in supporting this? or at least, could anyone point me in the right direction to try to do it myself (although I do not know the project at that level...))

**Comment by kippandrew** [comment]
Hi @durey. Apologies for the delayed response. We're going to talk about this internally and figure out if there is a way forward. Your suggestions are totally reasonable, and likely will help many people. I'm hoping there is a way we can fit these changes into our backlog, or possibly provide the information you would need to make them. Please stay tuned.

**Comment by durey** [comment]
@kippandrew , thank you very much!! We would be REALLY pleased with this new feature!
