### ISSUE TITLE
R 4.1.2 on shinyapps.io

### ISSUE THREAD

**Issue by MattCowgill** [rstudio/rsconnect#549]
When attempting to deploy (either locally or from GitHub Actions) I receive an error: 
`R version 4.1.2 currently unavailable` 

When will R 4.1.2 be available on shinyapps.io?

**Comment by kippandrew** [comment]
Thanks for the question. We're in the process of getting R 4.1.2 on shinyapps.io. I don't yet have an ETA, but I suspect it shouldn't be more than a week or so. We've been making some infrastructure improvements to shinyapps.io, which necessitated changing the R version update process.

**Comment by MattCowgill** [comment]
Hi @kippandrew thanks for the response. Is there an ETA on this? The lack of 4.1.2 support means that my Shiny apps can't be updated at the moment. (I update these apps via automated processes on GitHub Actions, and those Actions use the current release of R)

**Comment by stevenolen** [comment]
Hi @MattCowgill -- 4.1.2 is now available on shinyapps.io! Thanks for your patience and apologies for the inconvenience!

**Comment by MattCowgill** [comment]
Thanks very much @stevenolen
