### ISSUE TITLE
Configuration data stored in ~/Library/Application Support/R on macOS

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rsconnect#550]
From Brian Ripley:

> On macOS this leaves files behind in ~/Library/Application Support/R .
> That is not a permitted area under the CRAN policy ... look at what
> tools::R_user_dir() gives, and do make use of it.
> 
> Please correct before 2021-11-22 to retain your package on CRAN.

Unfortunately `tools::R_user_dir()` is new in R 4.0.0; we also have to be aware that on Linux, RStudio Workbench reads data from the configuration folder.

**Comment by jmcphers** [comment]
The contentious code:

https://github.com/rstudio/rsconnect/blob/e42166e4d0d39ead451165c30a0dd847dc11e639/R/config.R#L27-L45

And previous attempts to adhere to CRAN policy:

https://github.com/rstudio/rsconnect/commit/aca4c18fb39f0581ad52e234c618e3c9f1192c82

https://github.com/rstudio/rsconnect/commit/8088f0f40ec2cd19cf92bfd7fc2d735c29a7c53f

**Comment by jmcphers** [comment]
@gaborcsardi pointed out that making this work without a dependency on R 4.0 requires a polyfill, like this one in pkgcache:

https://github.com/r-lib/pkgcache/blob/e5be69024172e816fe45073b648b20200faf1eb3/R/cache-dirs.R#L39-L63

**Comment by kevinushey** [comment]
Does the backports package have a replacement we could use here?

**Comment by aronatkins** [comment]
We probably have an upgrade concern, as well, as existing records are in `~/Library/Application Support/R/rsconnect` (and were previously in the "connect" subdir); should we migrate or support both hierarchies?

Once the migration happens, older versions of `rsconnect` will not see that configuration.

**Comment by aronatkins** [comment]
`backports::R_user_dir` as of 1.1.6.

https://github.com/r-lib/backports/blob/main/NEWS.md#backports-116

**Comment by jmcphers** [comment]
IDE work needed to align to this is tracked here: https://github.com/rstudio/rstudio/issues/10119
