### ISSUE TITLE
Any GitHub package present in a manifest adds `null`-valued `GitHub*` values to all packages in the manifest

### ISSUE THREAD

**Issue by toph-allen** [rstudio/rsconnect#566]
I came across while running some smoke tests, described in https://github.com/rstudio/packrat/pull/656#issuecomment-1035221766.

In that instance, the presence of the `emo` package in the dependencies added the following fields to all other packages in the manifest.

```
      "GithubRepo": null,
      "GithubUsername": null,
      "GithubRef": null,
      "GithubSha1": null,
```

For packages installed from GitHub, these fields contain relevant information that Connect uses when restoring the environment. For other packages, they're meaningless.

This probably isn't cause for too much concern, because this have almost certainly always been there, but it might be worth removing them.

@aronatkins [suspects](https://github.com/rstudio/packrat/pull/656#issuecomment-1035284712) it is due to a data frame being serialized to JSON.

**Comment by hadley** [comment]
I think it's fine to ignore this. Fixing will require a substantial rewrite of the way that packrat files are parsed, and IMO it's not worth it. (The root problem is that we're reading the packrat file with `read.dcf()` which creates a data frame, which means that every record is forced to have the same fields.)
