### ISSUE TITLE
deployApp fails when deploying to existing shinyapps.io appName, but succeeds when deploying to new appName

### ISSUE THREAD

**Issue by dwachsmuth** [rstudio/rsconnect#574]
This is a hard problem to create a minimal reprex for, but I have a shinyapps.io app which is predictably failing to deploy at the `deploying: Starting instances` stage when I attempt to deploy over an existing appName, but deploys perfectly with identical settings and content when I specify a new appName. Once I've deployed it to a new appName, attempting to redeploy there will also fail.

I.e. if I my app is deployed with an appName `first_try`, the following fails:
```
rsconnect::deployApp(appName = "first_try", forceUpdate = TRUE)
```

While the following succeeds:
```
rsconnect::deployApp(appName = "second_try")
```

But, now that the app is alive at `second_try`, it will fail if I try to redeploy to that location.

The error message is the following (with a different Child Task # each time):
```
Error: Unhandled Exception: Child Task 1125639223 error: Unhandled Exception: Internal Server Error
```

The console output is as follows (this is with logLevel = "normal"):

```
Preparing to deploy application...DONE
Uploading bundle for application: 5851491...DONE
Deploying bundle: 5737768 for application: 5851491 ...
Waiting for task: 1125647446
  building: Processing bundle: 5737768
  building: Parsing manifest
  building: Building image: 6686420
  building: Installing system dependencies
  building: Fetching packages
  building: Building package: qs
  building: Building package: spatialwidget
  building: Building package: mapdeck
  building: Building package: rdeck
  building: Installing packages
  building: Installing files
  building: Pushing image: 6686420
  deploying: Starting instances
```

At which point the Task Log begins and produces a vast amount of output which appears to be truncated mid-entry based on some sort of character limit. And then the error prints.

If it helps, the site is sus-mcgill.shinyapps.io/sus-dev3. (The numbering scheme is because I can no longer updates sus-dev and sus-dev2!)

**Comment by ssinnott** [comment]
Hello!

I think this is an issue with the shinyapps.io platform and not related to the rsconnect package. It looks like you're eligible for email based tech support - so I would suggest opening a support issue on shinyapps.io rather then opening an issue over here.

Thanks!

Sean

**Comment by aronatkins** [comment]
Closing, as this issue should move to a support ticket for shinyapps.io, not filed against rsconnect.
