### ISSUE TITLE
Provide RStudio Addon for deployApp()

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rsconnect#579]
Just like {xaringan} package has a RStudio addon for `inf_mr()` for the currently open Rmd file, it would be nice if {rsconnect} provides an RStudio addon for `deployApp()` function for the current working directory.

**Comment by hadley** [comment]
How would you want that to be different from the existing publishing dialog?

**Comment by jooyoungseo** [comment]
As a VSCode and terminal user, I don't have the access to "publishing dialog" in RStudio IDE. #580 enables [vscode-R](https://github.com/REditorSupport/vscode-R) users to quickly execute `deployApp()` function via `R: Launch RStudio Addin` feature inside VSCode.
