### ISSUE TITLE
improve "cannot connect" errors

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#59]
I noticed this when testing against a development server (so, it was frequently up and down), but felt like this could happen in other contexts and we could give better messaging.

I typically run the server within a Vagrant instance and port-forward from localhost:3939 to instance:3939. The side-effect of this is that there are different errors depending on whether or not the Vagrant instance is up.

Here is the error when the Vagrant instance is down. It is a hard connection-refused.

```
Preparing to deploy application...Timing stopped at: 0.003 0 0.008 
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to localhost port 3939: Connection refused
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Here is the error when the Vagrant instance is up but the server is down. It is a softer failure, probably due to how the Vagrant port-forwarding works.

```
Preparing to deploy application...Timing stopped at: 0.002 0 0.008 
Error in function (type, msg, asError = TRUE)  : Empty reply from server
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

The difference in error is also visible just by hitting the endpoint with Curl.

I don't think the difference between these failures really matters -- we have good explanation text coming back from the network connection. What we should do is improve how we present this to the user.

**Comment by ChaitaC** [comment]
Currently running into this issue on Centos6-plain and Centos7. The error message is confusing and not helpful. In my case vagrant and server both were up and running and still I got the following message.

Error in function (type, msg, asError = TRUE)  : Empty reply from server
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by hadley** [comment]
Closing since this code has likely changed considerably in the last 7+ (!!) years. Please re-open if you still think it's important.
