### ISSUE TITLE
rsconnect: disallow deployment of qmd files as R Markdown

### ISSUE THREAD

**Issue by toph-allen** [rstudio/rsconnect#594]
Currently, `.qmd` files will be deployed as R Markdown content if no `quarto` argument is passed to `deployApp()`, and an R Markdown manifest will be created if no `quarto` is passed to `writeManifest()`.

This is because Quarto files and R Markdown files are detected [with the same regular expression](https://github.com/rstudio/rsconnect/blob/27c50cb1be28a05ad2a62682e867515580ab1691/R/bundle.R#L410), and the `quarto` argument determines the app mode assigned.

https://github.com/rstudio/rsconnect/blob/27c50cb1be28a05ad2a62682e867515580ab1691/R/bundle.R#L413-L420

https://github.com/rstudio/rsconnect/blob/27c50cb1be28a05ad2a62682e867515580ab1691/R/bundle.R#L430-L437

To change this, we should add a separate regex to detect `qmdFiles`. If `rmdFiles > `, the deployment will receive an `rmd`-related app mode. Otherwise, it will receive a `qmd`-related app mode.

Our reasoning in leaving this the other way was to make the selection of Quarto-related app modes manual, by passing in the `quarto` argument, which is a path to a Quarto binary. If the user does not pass that in, we won’t deploy as Quarto.

It almost seems silly to ask them to pass in a Quarto argument explicitly when we could just run `quarto inspect`. But I guess, they could get the same behavior by passing in `”quarto”` to that argument, because I don’t think we require a full path.

**Comment by ChaitaC** [comment]
- [ ] App deploys without an issue when quarto argument is passed

`rsconnect::deployApp(appDir = "/Users/chaitamacpro/Desktop/quarto1", server = "test_box", account = "chaitatest", quarto = quarto::quarto_path())`

```
Connect] Stopped session pings to http://127.0.0.1:34063
[Connect] Completed deployed execution
Application successfully deployed to http://localhost:3939/content/1fc7a7f5-16fa-4d23-9362-ed9590b11ea4/
```


- [ ] Without passing the quarto argument, you should see an error
`rsconnect::deployApp(appDir = "/Users/chaitamacpro/Desktop/quarto1", server = "test_box", account = "chaitatest")`

```
Uploading bundle for application: 764...Error in inferAppMode(appDir = appDir, appPrimaryDoc = appPrimaryDoc,  : 
  Attempting to deploy Quarto content without Quarto metadata. Please provide the path to a quarto binary to the 'quarto' argument.
```

**Comment by ChaitaC** [comment]
- Created a new project 
- add an rmd doc
- deploy passing quarto argument 
` rsconnect::deployApp(appDir = "/Users/chaitamacpro/Desktop/deployrMarkdown", server = "rsc.radixu.com", quarto = quarto::quarto_path())`
- https://rsc.radixu.com/connect/#/apps/8c802254-1a56-4191-b104-13f7f12db9e6/info/5453

Note: The app mode is R Markdown document. Is that expected?

**Comment by toph-allen** [comment]
When I deployed the Rmd file, it deployed with a Quarto app mode.

```
> rsconnect::deployApp(".", appPrimaryDoc = "rmdfile.Rmd", quarto = quarto::quarto_path(), server = "rsc.radixu.com")
Preparing to deploy document...DONE
Uploading bundle for document: 5672...DONE
Deploying bundle: 13125 for document: 5672 ...
[Connect] Building Quarto document...
```

https://rsc.radixu.com/connect/#/apps/6cc07579-932b-430e-9399-fa3a3b67905b/info/5454

When I deployed without passing in `appPrimaryDoc`, it deployed with an R Markdown app mode.
