### ISSUE TITLE
Should work published on rstudio-connect be open-source as well? (License compatibility)

### ISSUE THREAD

**Issue by dipterix** [rstudio/rsconnect#597]
Just had a discussion at https://github.com/rstudio/plumber/issues/250, since the R is GPL, if I write a plumber application, or a shiny app, then should the whole program be GPL even my code is proprietary?

If so, then anyone who publish their applications to RStudio Connect need to have their program as a whole subjecting to GPL license. And by delivering the whole program, should RStudio Connect publish their source code because of GPL license?

**Comment by hadley** [comment]
If you have concerns about licensing, the best person to talk to is a lawyer, who can help you understand the licensing issues for your exact situation. I have written some general info about licensing at https://r-pkgs.org/license.html, which might help: the main thing to understand here is that licenses only kick in if you're distributing the code, and simply hosting on a server would not usually be considered as distributing.
