### ISSUE TITLE
rsconnect::showLogs for collaborators

### ISSUE THREAD

**Issue by shahronak47** [rstudio/rsconnect#606]
Is it possible to see logs of shiny application hosted on rsconnect where I am a collaborator ? 

Some background - I am working on a shiny app where the owner of the app has left the company. Rest of us are collaborators. How do we deal with this situation?

**Comment by hadley** [comment]
`showLogs()` currently only works for shinyapps.io, so unfortunately no.

**Comment by aronatkins** [comment]
One additional note: The Connect Server API lets collaborators enumerate content jobs and obtain logs for each job, but this information is not available through the `rsconnect` package.

https://docs.posit.co/connect/api/#tag--Jobs
