### ISSUE TITLE
`rsconnect::deploySite()` `siteName` parameter doesn't accept names with periods.

### ISSUE THREAD

**Issue by antass** [rstudio/rsconnect#607]
When deploying a site via the `reconnect::deploySite()` command in RStudio, the `siteName` parameter rejects names with periods. This is not the case when deploying Shiny apps, for example, with RStudio's built-in "Publish" button.

This fails: `reconnect::deploySite(siteName="project-name.analysis.date")`.

This works: `reconnect::deploySite(siteName="project-name_analysis_date")`.

**Comment by hadley** [comment]
When I run this code, I get a pretty clear error:

```
POST https://colorado.posit.co/rsc/__api__/applications
Application name must be between 3 and 64 alphanumeric characters, dashes, and underscores.
```

i.e. this is a restriction of connect application names.
