### ISSUE TITLE
Deploying Error shinydashboardplus even i did not use it in the project 

### ISSUE THREAD

**Issue by mlotfic** [rstudio/rsconnect#613]
Error: Unable to retrieve package records for the following packages:
- "shinydashboardplus"
In addition: Warning message:
In FUN(X[[i]], ...) :
  Package 'shinydashboardplus' not available in repository or locally

**Comment by aronatkins** [comment]
It is likely that some other package depends on `shinydashboardplus`. From the CRAN details for the package (https://cran.rstudio.com/web/packages/shinydashboardPlus/), it has a number of reverse dependencies (though there may be others that are not part of CRAN).

Are any of those reverse dependencies used by your project?

You should be able to resolve this warning by installing the `shinydashboardplus` package, or removing the use of the package that is requiring it.
