### ISSUE TITLE
FR: .rsconnect_profile file for the server

### ISSUE THREAD

**Issue by stla** [rstudio/rsconnect#617]
Hello,

I need to execute some code on the server before the deployment. With the **.rsconnect_profile** file, the code is executed on my computer, not on the server. Therefore I use the **.Rprofile** file. But then I have to use a if-else in this file, to execute some code on my laptop and some code on the server. To be clearer, my **.Rprofile** file has form:

```r
os <- Sys.info()["sysname"]
if(os == "Windows") { # this is my computer
  ......
} else { # this is the RSconnect server
  ......
}
```

This is not highly convenient. It would be nice to have a file like **.rsconnect_profile** but whose contents are executed on the server.

**Comment by jmcphers** [comment]
This wouldn't be a feature of the rsconnect package but a feature of whichever server/site you're publishing to. Here are a couple of links that might help:

https://mraess.rbind.io/2018/07/the-awesomeness-that-is-the-global-r-file-or-how-to-clean-up-your-shiny-app/

https://cran.r-project.org/web/packages/config/vignettes/introduction.html

**Comment by stla** [comment]
I'm afraid I haven't been clear enough. The `global.R` file cannot help here, because I want to run some code ***before*** the deployment. My problem is with the packages installation (I want to run `Sys.setenv(PATH = something)` in order that R finds **CMake** which is required to install a package). The file `global.R` is not executed before the packages installation.

**Comment by jmcphers** [comment]
Oh, I see! It's still the case that this feature would have to be supplied by the server -- the rsconnect package doesn't run code (or even exist) on the server. It just bundles up the application and sends it to the server; what happens from there is up to the server. 

Are you publishing to RStudio Connect?

**Comment by stla** [comment]
Yes, I publish on RStudio Connect, in the company I'm working in.

Ok, so there's no way to have a file similar to **.Rprofile**.

**Comment by stla** [comment]
Just a correction of my first post (in case if someone reads it). In **.Rprofile**, it would be better to do:

```r
if(Sys.getenv("CONNECT_SERVER") == "the url to the server/") {
  ......
} else {
  ......
}
```
