### ISSUE TITLE
We should remove the API check for plumber APIs when deploying to cloud or shinyapps.io.

### ISSUE THREAD

**Issue by ssinnott** [rstudio/rsconnect#619]
There's validation on the content type when the bundle is uploaded now - so we can remove this check,

https://github.com/rstudio/rsconnect/blob/main/R/deployApp.R#L339-L346

**Comment by omar-rs** [comment]
I am able to deploy a plumber API to cloud -- see: https://rstudiopbc.atlassian.net/wiki/spaces/ENG/pages/127893512/Cloud+Publishing+-+Plumber+API

Is this only a shinyapps.io issue?

**Comment by ssinnott** [comment]
This applies to both... but I think it only happens if you specify `contentCategory='api'`. I don't normally do that,

https://github.com/rstudio/rsconnect/blob/main/R/deployApp.R#L110-L135
