### ISSUE TITLE
ignore project-local python virtual environments by default

### ISSUE THREAD

**Issue by edavidaja** [rstudio/rsconnect#632]
An internal user encountered the following while attempting to deploy a reticulated project:

```
Error in enforceBundleLimits(appDir, files$totalSize, length(files$contents)) : 
  The directory /usr/home/jeremy.allen/projects/reticulate-with-venv cannot be deployed because it contains too many files (the maximum number of files is 10000). Remove some files or adjust the rsconnect.max.bundle.files option.`
```

you can work around this by adjusting the max bundle files or by specifying `appFiles` but ignoring the files to begin with might be a better default.

**Comment by hadley** [comment]
What directories do we need to ignore?

**Comment by edavidaja** [comment]
The Python command line interface ignores some conventional names for virtual environment directories: https://github.com/rstudio/rsconnect-python/blob/master/rsconnect/bundle.py#L37-L50
 and checks for directories that are likely to contain a virtual environment:
https://github.com/rstudio/rsconnect-python/blob/94dbd28797ee503d66411f736da6edc29fcf44ed/rsconnect/bundle.py#L541-L543
