### ISSUE TITLE
Release tag needed for 0.8.29

### ISSUE THREAD

**Issue by slodge** [rstudio/rsconnect#650]
I see 0.8.29 in https://cran.r-project.org/web/packages/rsconnect/index.html - but don't see a corresponding tag in the releases in this repo - https://github.com/rstudio/rsconnect/releases

**Comment by slodge** [comment]
(just checked the date in CRAN - looks like this was yesterday ... :+1: ... guess I was lucky on the day I chose to upgrade! )

**Comment by aronatkins** [comment]
Yep. Lucky! 🍀 

We submitted to CRAN yesterday, but it had not gone final before going offline. We don't create tags until a release has been accepted.

rsconnect 0.8.29 was published last night and we created a release tag this morning.
https://github.com/rstudio/rsconnect/releases/tag/v0.8.29
