### ISSUE TITLE
"proceed with deployment" default value

### ISSUE THREAD

**Issue by r2evans** [rstudio/rsconnect#652]
I might be misreading this, but when I get a warning on app-deployment such as

```
Do you want to proceed with deployment? [Y/n]: 
```

I interpret the upper-case `Y` to be the default value. However, pressing just return in this case defaults to `n`. With a default of "n" (I am _not_ suggesting changing the default behavior), I expect to see

```
Do you want to proceed with deployment? [y/N]: 
```

There is precedence in many unix-based tools.

Barely a question, really really minor. Just a comment on UX. Thanks!

**Comment by aronatkins** [comment]
Thanks. Looks like we've got two prompts and they've got different defaults, which aren't represented in the "y/n" message appropriately; probably the result of some copy-paste.

When there's a lint error, we want "no" to be the default:

https://github.com/rstudio/rsconnect/blob/6157c6c453d55de064b7f891363f3a065aa81907/R/deployApp.R#L298-L304

When updating, we want "yes" to be the default:

https://github.com/rstudio/rsconnect/blob/6157c6c453d55de064b7f891363f3a065aa81907/R/deployApp.R#L827-L833

**Comment by r2evans** [comment]
Do you think that changing the first to `[y/N]` would be enough and acceptable?

**Comment by aronatkins** [comment]
@r2evans - yep; that's what i've proposed in https://github.com/rstudio/rsconnect/pull/653! Thanks!
