### ISSUE TITLE
cloud rmd deploys no longer work

### ISSUE THREAD

**Issue by mslynch** [rstudio/rsconnect#777]
For Posit Cloud, rsconnect is supposed to (for the time being) coerce rmd-static to rmd-shiny. This no longer seems to be happening – cloud receives a bundle with `"appmode": "static"` in the manifest, which is unsupported.

**Comment by aronatkins** [comment]
@mslynch - this problem is only with the current GitHub version, not the CRAN release, correct?

**Comment by mslynch** [comment]
This happens on the latest CRAN release. I haven't tried this using the current GitHub version.

**Comment by aronatkins** [comment]
Could you try to create a reproducible example? What is contained in the directory you are trying to deploy? What command / technique are you using to deploy?

The "static" app-mode is generally meant for HTML, not code running on the server; it's quite different from Rmd code that we pretend is a Shiny Rmd for shinyapps.io.
