### ISSUE TITLE
Publish failure when document exists in home directory

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rsconnect#78]
Repro:

1. Create a file `~/test.Rmd`,
2. Attempt to publish it to Connect (using the RStudio dialog), with source code:

I get the following output:

```
Error in rsconnect::deployApp(appDir = "~", appFiles = c("test.Rmd"),  : 
  /Users/kevinushey/~ does not exist
Execution halted
```

Not sure if this should be fixed on the `rsconnect` or IDE side (e.g. the `appDir` should probably be `~/`, not `~`; but `rsconnect` could still handle this case)

**Comment by jjallaire** [comment]
@kevinushey Let's log everything we find in FogBugz for now so we can triage and burn down in one place (I logged this bug in FogBugz as 4899)
