### ISSUE TITLE
Cannot publish Shiny application from Rstudio with Norwegian locale

### ISSUE THREAD

**Issue by paalhaugen** [rstudio/rsconnect#792]
Previously send as support issue, filed again here.

I have a subscription to Shinyapps, and I have published some applications. However, I can no longer publish working apps to the site. I am using Rstudio RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
And R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"
rsconnect version 0.8.29

The publication process starts but halts when using packrat. No error messages are given. The application appears on shinyapps.io as "Deploying" but nothing more happens.
I found some indications that it is related to my locale, but no luck in figuring out how to overcome the problem.

Below is an output from the deployment when I try to publish
![image](https://user-images.githubusercontent.com/94442352/226833531-870a8537-aba4-455a-b4e8-17f48eec3521.png)

As a side note, I also found this thread. I tried to follow the suggestions, however no luck for me so far….

 

[Deploying Shiny app to shinyapps.io stops at: "Starting to perform package snapshot" - shiny / shinyapps.io - Posit Forum (rstudio.com)](https://community.rstudio.com/t/deploying-shiny-app-to-shinyapps-io-stops-at-starting-to-perform-package-snapshot/145558)

Further, I tested the “Old Faithful” example a and I get the exact same result as when I try to publish my own application. I have tried this example both with all the code within one file, and to split the code into server.r and ui.r, but there seem to be no difference.

Finally, here is a snapshot from my session info from this morning. I updated to the latest version of Rstudio, but no difference in behaviour regarding publishing.
![image](https://user-images.githubusercontent.com/94442352/226834197-24b4fa44-6adc-40ee-bee6-29e5d2d9a59f.png)

**Comment by aronatkins** [comment]
Could you verify that you have installed the latest `packrat` (0.9.1)? It's not showing up in the `sessionInfo()`.

```r
install.packages("packrat")
```

Your problem also appears similar to https://github.com/rstudio/rsconnect/issues/656, which should be resolved by some recent changes to locale handling.

```r
remotes::install_github("rstudio/rsconnect")
```

**Comment by paalhaugen** [comment]
Hi
I Installed the latest packrat version, but no changes to the functionality.

I installed the github version of rsconnect, and now the publish function in Rstudio does not work at all. Seems to have broken some functionalities in the program.

**Comment by hadley** [comment]
@paalhaugen do you mind trying to deploy the app with code? That will let us figure out if the dev version of rsconnect has fixed the problem. The code should be something like this:

```R
rsconnect::deployApp("D:/Repos/Shiny apps/vikenco", server = "shinyapps.io",  appName = "vikenco")
```

And would you mind copying and pasting the error you see in RStudio so I can fix that problem? 

Thanks!

**Comment by paalhaugen** [comment]
Dear Hadley
Thanks for reaching out.
I was at a conference yesterday, so I had to test remotely.
Today I am back at the office, and deploying with code gives no errors, and I can deploy my apps again.
I am very happy, but don’t quite understand what has happened?

I will have to try to publish from within R studio to see what happens.


But what a nice start to a Friday to have Shiny back a gain in the toolbox 😊


Have a great weekend


Med hilsen / Best regards
Furuno Norge AS
Pål Haugen
Product Developer
Direct: +47 952 38 351 ● www.furuno.no ● Facebook ● LinkedIn

Fra: Hadley Wickham ***@***.***>
Sendt: torsdag 23. mars 2023 15:01
Til: rstudio/rsconnect ***@***.***>
Kopi: Pål Haugen ***@***.***>; Mention ***@***.***>
Emne: Re: [rstudio/rsconnect] Cannot publish Shiny application from Rstudio with Norwegian locale (Issue #792)


@paalhaugen<https://github.com/paalhaugen> do you mind trying to deploy the app with code? That will let us figure out if the dev version of rsconnect has fixed the problem. The code should be something like this:

rsconnect::deployApp("D:/Repos/Shiny apps/vikenco", server = "shinyapps.io",  appName = "vikenco")

And would you mind copying and pasting the error you see in RStudio so I can fix that problem?

Thanks!

**Comment by paalhaugen** [comment]
It is not possible to publish through Rstudio, but I can publish with code. When I publish with code I get the following warning:
Warning messages:
1: In Sys.setlocale("LC_CTYPE", ctype) :
  OS reports request to set locale to "Norwegian Bokmål_Norway.utf8" cannot be honored
2: In Sys.setlocale("LC_CTYPE", loc) :
  OS reports request to set locale to "Norwegian Bokmål_Norway.utf8" cannot be honored

Does this help?

**Comment by hadley** [comment]
Does RStudio give you an error message when you attempt to publish?  

You can ignore those warnings about locale; I'm not sure what's causing them but they're not important.

**Comment by hadley** [comment]
Hmmmm, maybe the update to rsconnect didn't succeeded, and the actual difference is between publishing from the IDE and publishing with code? Would you mind running `packageVersion("rsconnect")` to confirm which version of rsconnect you have?

**Comment by paalhaugen** [comment]
This seems veird. R returns 
> packageVersion("rsconnect")
[1] �\u0080\u00980.8.29.9000�\u0080\u0099

**Comment by hadley** [comment]
That is weird. Can you try in a fresh R session? What version of R are you using?

**Comment by paalhaugen** [comment]
Hi, sorry for the late reply.
I have restarted R and I get this output
packageVersion("Rsconnect"):
[1] '0.8.29.9000'

I am using R version 4.2.2

**Comment by hadley** [comment]
Hi @paalhaugen — are you still seeing this problem with the latest version of rsconnect?

**Comment by paalhaugen** [comment]
@hadley Sorry for my late reply. I just tested, and everything works super. Thank you, Shiny for both R and Python is a dream to work with!!

**Comment by hadley** [comment]
Awesome, glad to hear that it's all working once more.
