### ISSUE TITLE
Connect Logs Should Include Identifying Tag

### ISSUE THREAD

**Issue by pfizzy** [rstudio/rsconnect#807]
I want to download my application logs to better monitor usage and track down any errors which might have happened. One slight wrinkle is that the Posit Connect server logs get interspersed with the application events. While I greatly appreciate the Connect logs being available, they do generate a bit of noise that requires filtering.

Could all Posit Connect logs be prefaced with an identifying tag, so that they can be easily separated from the running application? Some of the logged events already receive a `[rsc-session]` preface, I would just like to see this applied everywhere.

Currently I see something like the below 

```
2023/04/07 20:47:05.082434064 
2023/04/07 20:47:05.298891310 Running on host: XXXXXX
2023/04/07 20:47:05.298928781 Working directory: /opt/rstudio-connect/mnt/app
...
2023/04/07 21:58:18.803415056 [rsc-session] Received signal: interrupt
2023/04/07 21:58:18.803451855 [rsc-session] Terminating subprocess with SIGINT ...
```

Could it be made more like the below?

```
2023/04/07 20:47:05.082434064 [rsc-session] 
2023/04/07 20:47:05.298891310 [rsc-session] Running on host: XXXXXX
2023/04/07 20:47:05.298928781 [rsc-session] Working directory: /opt/rstudio-connect/mnt/app
...
2023/04/07 21:58:18.803415056 [rsc-session] Received signal: interrupt
2023/04/07 21:58:18.803451855 [rsc-session] Terminating subprocess with SIGINT ...
```

Application logs would be presented without modification.

Sorry if there is a better place to request this, but it was my best guess.

**Comment by aronatkins** [comment]
Thanks for the suggestion. I'll take this onto our Connect (internal) board and manage it there.

In case it's helpful: Some of the messages without `[rsc-session]` are produced by the Connect-packaged R or Python code that is used to bootstrap the runtime environment, but other messages are not so easily controlled -- they might be produced by whatever packages you are using in your content.

Are you able to control the messages produced by your content? Could those messages receive a prefix?

Are you able to share more complete examples, especially some with the errors you were trying to locate? You can create a support ticket if you don't want to post those logs publicly. Reference this ticket and it'll get directed to me. <https://support.posit.co/>

**Comment by pfizzy** [comment]
I could put a prefix onto all of my application entries, but then I would want to ensure some consistency across all of the hosted applications (eg Alice’s logs start with `myapp\t`, but Bob uses `shinycode:`, etc). Non-expert users who manually trigger log events are unlikely to always insert the prefix. I was hoping to get reliable tagging managed by the host. Either on the platform’s actions or the user code. Some key that would enable a generic log extraction to yank application events.

In this particular instance, I am not debugging anything wrong with Connect, just my own application errors. That being said, I can carve out some time to generate a reproducible example I could share through the support channel.

**Comment by aronatkins** [comment]
@pfizzy Thanks in advance for sharing whatever you can.

Some folks solve this problem by creating a package / conventions to help create consistent log messages across all applications. It does take some work to get that strategy adopted, but means you can easily separate output from your code from output by other code.

You could, for example, use the `logger` package to declare a custom message format. You could even emit JSON, if you want to use code to analyze the output. Some examples: https://daroczig.github.io/logger/articles/customize_logger.html#custom-log-record-layout
