### ISSUE TITLE
`writeManifest` fails when encountering archived packages

### ISSUE THREAD

**Issue by Lytol** [rstudio/rsconnect#809]
Using [rowr](https://packagemanager.posit.co/client/#/repos/2/packages/rowr) as an example:

* Install `rowr` using `devtools::install_version('rowr', '1.1.3')` as directed by Posit Package Manager
* Run `rsconnect::writeManifest()` to create the `manifest.json`
* [Using CRAN version of `rsconnect`]: `manifest.json` is written with a warning, but the "Repository" field is `null`, which Connect will fail to deploy without an accompanying packrat.lock (for example, using Git deployment)
* [Using devel version of `rsconnect`]: fails immediately with the following error:
```
rsconnect::writeManifest()
Error in `createAppManifest()`:
! All packages must be installed from a reproducible location.
✖ Can't re-install packages installed from source: rowr.
ℹ See `rsconnect::appDependencies()` for more details.
Run `rlang::last_trace()` to see where the error occurred.
```

This looks related to #508 with the note that while the current CRAN version deploys cleanly from push-button deployment to Connect, it will fail on a Git deployment (which only uses the `manifest.json`).

**Comment by aronatkins** [comment]
The CRAN release of `rsconnect` produces a warning for this situation and produces a manifest with a `null` repository entry associated with `rowr`.

``` r
remotes::install_version('rowr', '1.1.3')
#> Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/rowr/rowr_1.1.3.tar.gz
writeLines(c(
  "library(shiny)",
  "library(rowr)",
  "ui <- fluidPage('hi, shiny')",
  "server <- function(input, output) {}",
  "shinyApp(ui = ui, server = server)"
), "app.R")
rsconnect::writeManifest()
#> Warning: 
#> * May be unable to deploy package dependency 'rowr'; could not
#>    determine a repository URL for the source 'CRAN'.
#> 
#> * Unable to determine the source location for some packages. Packages
#>    should be installed from a package repository like CRAN or a version
#>    control system. Check that options('repos') refers to a package
#>    repository containing the needed package versions.
m <- jsonlite::fromJSON("manifest.json")
m$packages$rowr$Repository
#> NULL
```

<sup>Created on 2023-04-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by aronatkins** [comment]
@hadley - Is rsconnect able to populate the repository field for archived packages?

Connect currently errs on a `null` repository entry, while shinyapps.io assumes it should install the package from CRAN.

**Comment by hadley** [comment]
Yeah, we should be able to. I probably just missed a branch. I'll try and take a look next week.

**Comment by hadley** [comment]
With #791 we appear to be back to the same situation as the CRAN version; i.e. it creates a manifest with `"Source": "CRAN", "Repository": null,` (albeit without a warning).  Is that the correct behaviour?

**Comment by aronatkins** [comment]
It's "better".

shinyapps.io can process that kind of manifest (it falls back to "CRAN" on unknown repository URLs) but Connect doesn't handle those `null` values. Connect rejects `manifest.json` which have unknown repository URLs. If needed, we can adjust Connect (ignore `null` repository URLs and hope that the package can be found in one of the repositories associated with another package).

Does #791 indicate that `renv` also cannot determine a repository location for archived packages?

**Comment by hadley** [comment]
I had to fix a couple more bugs in #791, but I can now deploy an app that uses `rowr` and I get this error, as you described:

```
Performing manifest.json to packrat transformation.
Cannot create packrat data from manifest.json: Cannot transform manifest into packrat.lock: package rowr does not define Repository
```

I could certainly adapt that PR fill some repository for archived packages, but it's not obvious what to do. How does shinyapps.io determine that rowr is an archived package and what repository url does it use?

**Comment by aronatkins** [comment]
shinyapps.io has well-known locations for "CRAN", but needs repository URLs for other names. I'll send the reference separately.

**Comment by aronatkins** [comment]
We have decided that Connect will allow manifest.json when packages have an empty `Repository`, as that can happen for archived packages. `rsconnect` will permit manifest creation and log about the lack of information, as this situation can also happen when the R session is not configured with a full set of `repos` URLs.

```json
{
  "packages": {
    "rowr": {
      "Source": "CRAN",
      "Repository": null,
      "description": {
      }
    }
  }
}
```

**Comment by aronatkins** [comment]
Posit Connect 2023.05.0 contains the change to repository handling.
