### ISSUE TITLE
"unused argument (accountDetails)" error when deploying application

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#81]
With latest rsconnect, deployApp() causes this error:

```
Preparing to deploy application...DONE
Uploading bundle for application: 180...Error in bundleApp(target$appName, appDir, appFiles, appPrimaryDoc, assetTypeName,  : 
  unused argument (accountDetails)
Calls: <Anonymous> -> withStatus -> force -> bundleApp
Execution halted
```

**Comment by jmcphers** [comment]
thanks, missed a file in the last commit!

**Comment by jjallaire** [comment]
Just want to clarify that this defect does NOT exist in the current preview version (which has version fba0fd0f291157c8400beae0cc998c0c01b70406 of rsconnect). Just a sanity check as we are thinking about sending out the RSC preview email later this afternoon.

**Comment by jmcphers** [comment]
That's correct. The defect was introduced with https://github.com/rstudio/rsconnect/commit/2e613c81adaad008f310d55513bee751571569e3 (ironically to make it possible to drive the code from a test...) so only existed for a few hours.
