### ISSUE TITLE
Loading library in reticulate package stops public deployment

### ISSUE THREAD

**Issue by Archarlie2000** [rstudio/rsconnect#812]
I have been trying to deploy a shinny app that utilize reticulate package with primer3-py and pandas library. 

here is what the python file looks like

I have installed pandas, primer3 through "pip install".

## This function is used to debug. So I only load the library for the sake of simplicty
def function_text(k):
   import(pandas)
   import(primer3-py)
   k = primer3.calc_tm("ATAT")
   return(k)
   
   The application works well local. While I deploy through shinny. It displayed An error has occurred. Check your logs or contact the app author for clarification. The error message has not further error content.
   
   Thank you for reviewing.

**Comment by aronatkins** [comment]
@Archarlie2000 - could you please include a more complete reprex and more of the generated output that you see during the deploy?

**Comment by aronatkins** [comment]
Closing this issue, as it sounds like you are able to successfully deploy (perhaps to https://shinyapps.io). Please send along more details if you continue to have trouble.
