### ISSUE TITLE
deploySite does not work for non-RMarkdown sites

### ISSUE THREAD

**Issue by omar-rs** [rstudio/rsconnect#813]
`deploySite()` looks specifically for static files and directories generated with rmarkdown, so it will not work for sites generated by Quarto because the static artifacts are slightly different.

**Comment by hadley** [comment]
Looks like this should be a straightforward fix to a regex: https://github.com/rstudio/rsconnect/blob/envvars/R/deploySite.R#L80

**Comment by omar-rs** [comment]
And possibly here too:
https://github.com/rstudio/rsconnect/blob/5533a945b8f2bddf73710b8a645644de3b3b9639/R/deploySite.R#L53

**Comment by hadley** [comment]
Ah yeah, we basically need something to parallel `rmarkdown::site_generator()` that extracts the equivalent info from the quarto metadata.

**Comment by omar-rs** [comment]
Maybe the `quarto` R [package](https://cran.r-project.org/web/packages/quarto/index.html) might be able to provide this info via `quarto::quarto_inspect()`

**Comment by hadley** [comment]
I talked with @jjallaire about this, and I think long term goal is to have this code live in rsconnect.
