### ISSUE TITLE
Update project_id on redeploy for Cloud

### ISSUE THREAD

**Issue by mslynch** [rstudio/rsconnect#815]
Currently, we use the environment variable `LUCID_APPLICATION_ID` to determine whether the user is executing their deploy within a project, and if it is, create the output with an association to that project. We should also update the project association if the user redeploys from a different project.

Also see https://github.com/rstudio/rsconnect-python/issues/409.

**Comment by hadley** [comment]
@mslynch can I assume you'll tackle this one?

**Comment by mslynch** [comment]
Right.
