### ISSUE TITLE
Connect server registration sad due to `object 'getAuthToken' not found`

### ISSUE THREAD

**Issue by meatballhat** [rstudio/rsconnect#816]
I'm using `rstudio/rsconnect@48e9a99602a096b14a41c8717ac8974ca713560b` mostly to get the fix from #810 and now a new error has approached:

```
Error in lapply(l, function(ele) { : object 'getAuthToken' not found
```

which happens in roughly the same place as #810 after clicking the `Connect Account` button

![image](https://user-images.githubusercontent.com/45143/233073124-8a48ea64-4c4d-46a9-89bf-3103dac75ff0.png)

I don't see any references to `getAuthToken` in the rsconnect code, so I'm guessing this is coming from:

https://github.com/rstudio/rstudio/blob/adf009da13910f7aae13b49a44b6dd31c2ee27df/src/cpp/session/modules/SessionRSConnect.R#L231-L233

**Comment by hadley** [comment]
I think `getAuthToken()` probably turned into `getAuthTokenAndUser()`, so `ide.R` needs a shim for the old name.

Thanks for discovering these bugs for us 😄

**Comment by hadley** [comment]
Change made in #772

**Comment by hadley** [comment]
There's also something wrong with how the IDE ends up calling `addServer()` because it doesn't add the trailing `__api__` like an interactive call to `addServer()` does

**Comment by hadley** [comment]
Ugh, there's a lot broken here 😭  I'll fix it today.

**Comment by meatballhat** [comment]
@hadley Thank you! 💖
