### ISSUE TITLE
ShinyApps cannot install packages from custom AWS repository with a UserAgent

### ISSUE THREAD

**Issue by StefanMusch** [rstudio/rsconnect#835]
Hi there,

I've been struggling with deploying an app that uses packages hosted on a custom private CRAN. Specifically, we host our packages on [http://g6tr-cran.s3.amazonaws.com/](http://g6tr-cran.s3.amazonaws.com/). It's a publically accessible URL, but only when we set the correct `HTTPUserAgent` can we actually install packages. E.g., this call will work in base R (if we provide the correct useragent string)

```{r}

options(repos = c(
  G6TR = "http://g6tr-cran.s3.amazonaws.com",
))

options(HTTPUserAgent = paste(
  # system description to get access to RSPM
  paste0(
    "R/", getRversion(), ' R (', 
    getRversion(), " ",
    R.version$platform, " ",
    R.version$arch, " ",
    R.version$os, ")"
  ),
  # access key for internal CRAN
  "FAKEUSERAGENTSTRING"
))

install.packages("g6tr.ui")
```

However, when setting these options in a shiny app, the installation for this package fails. 

```{r}
Preparing to deploy application...DONE
Uploading bundle for application: 9027000...DONE
Deploying bundle: 7173447 for application: 9027000 ...
Waiting for task: 1297212850
  building: Building image: 8527160
  error: Building package: g6tr.ui
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 1297212851 failed: Error building image: Error fetching g6tr.ui (0.1.5) source. Error downloading package source: HTTP 403: Forbidden
Execution halted
```

Initially I thought it was because the options didn't get parsed correctly, but when wrapping it in a  `renderText({})` call it output the ` UserAgent` and `repos` options correctly. Is there something I'm missing, or should there be an alternative way to pass headers to RSConnect / Packrat?

**Comment by omar-rs** [comment]
Hi Stefan,

It is not possible to use a private package with the application code when you deploy it to shinyapps.io; the package must be available in CRAN, a GitHub repo, or BioConductor.  This is outlined in the shinyapps.io [documentation](https://docs.posit.co/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud) - see the `Package sources` section.

While the code that you provided works locally by overriding the `options` headers to pass the access key, shinyapps.io will not run this code when it tries to install your package.  

If you decide to make this package available via a private GitHub repo, shinyapps,io will be able to install this package, provided that you follow the instructions here: 
https://docs.posit.co/shinyapps.io/getting-started.html#important-note-on-github-packages
