### ISSUE TITLE
Deploy hangs when too many files in the application directory

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#84]
Originally reported here:

https://support.rstudio.com/hc/communities/public/questions/207541817-Strange-message-during-deploy

I reproduced the issue by having 200 image files in my application directory with filenames like: `USZ11_sitting_conv copy 200.png`

Deploy starts and Deploy tab shows this:

```
WARNING: '-e {~+~options(repos~+~=~+~c(CRAN='https://cran.rstudio.com/'),~+~download.file.method~+~=~+~'curl',~+~download.file.extra~+~=~+~'-L~+~-f');~+~rsconnect::deployApp(appDir~+~=~+~'~/ShinyApps/many-files',appFiles~+~=~+~c('server.R',~+~'ui.R',~+~'images/USZ11_sitting_conv~+~copy~+~1.png',~+~'images/USZ11_sitting_conv~+~copy~+~10.png',~+~'images/USZ11_sitting_conv~+~copy~+~100.png',~+~'images/USZ11_sitting_conv~+~copy~+~101.png',~+~'images/USZ11_sitting_conv~+~copy~+~102.png',~+~'images/USZ11_sitting_conv~+~copy~+~103.png',~+~'images/USZ11_sitting_conv~+~copy~+~104.png',~+~'images/USZ11_sitting_conv~+~copy~+~105.png',~+~'images/USZ11_sitting_conv~+~copy~+~106.png',~+~'images/USZ11_sitting_conv~+~copy~+~107.png',~+~'images/USZ11_sitting_conv~+~copy~+~108.png',~+~'images/USZ11_sitting_conv~+~copy~+~109.png',~+~'images/USZ11_sitting_conv~+~copy~+~11.png',~+~'images/USZ11_sitting_conv~+~copy~+~110.png',~+~'images/USZ11_sitting_conv~+~copy~+~111.png',~+~'images/USZ11_sitting_conv~+~copy~+~112.png',~+~'image
```

and it just hangs at this point (you cannot publish again).

We should handle the situation more gracefully; if there is a hard limit on the number of files or the string length, we should report that and exit properly.

**Comment by jjallaire** [comment]
We'll track this within FogBugz along with the other RStudio IDE issues we're burning down for this release (see bug 5409 there).

**Comment by jmcphers** [comment]
It's now fixed; we pass the files into the package as a manifest rather than a long string.
