### ISSUE TITLE
URL parse error when server URL given without protocol

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#861]
Using RStudio 2023.08.0-daily+40 (and others), R-4.3.0 and rsconnect as of a3d883cbf3ff37fce603a7276cf7cbbec2c0ef12,
attempting to add a server without protocol encounters an URL parse error.

Go through the IDE Publishing UI to add a new account: Tools->Global Options->Publishing->Connect->Posit Connect and enter "colorado.posit.co/rsc/" as the server URL.

The console shows the following error:

```
Error in parseHttpUrl(url) : Invalid url: colorado.posit.co/rsc/__api__
```

The UI shows:

<img width="533" alt="image" src="https://github.com/rstudio/rsconnect/assets/362187/171eb008-7481-4d4e-938a-4d39ea420756">

**Comment by aronatkins** [comment]
Workaround: Add protocol to the server URL: `https://colorado.posit.co/rsc/`.

**Comment by ronblum** [comment]
Note: The connection works with R 3.6.3.

**Comment by ChaitaC** [comment]
R 4.1.0
```
RemoteType: github
RemoteRepo: rsconnect
RemoteSha: f3725d77260f412b4be0a1228486b63a5d8d5656
```



**Before :** 
<img width="549" alt="Screenshot 2023-06-25 at 9 59 59 PM" src="https://github.com/rstudio/rsconnect/assets/17551950/5b317b11-6498-4c27-8241-7c9982bcafef">

**After the fix with latest rsconnect dev** 

<img width="533" alt="Screenshot 2023-06-25 at 10 03 07 PM" src="https://github.com/rstudio/rsconnect/assets/17551950/29ecc30b-7f4e-4a2b-b5bb-4c3bcddf697b">
