### ISSUE TITLE
Error when trying to deploy a shiny app with a non-CRAN package dependency

### ISSUE THREAD

**Issue by rappster** [rstudio/rsconnect#88]
When trying to deploy a shiny app that depends on a non-CRAN/self-authored package to [shinyapps.io](http://www.shinyapps.io/) via `rsconnect::deployApp()`, I get the following error:

    Preparing to deploy application...DONE
    Uploading bundle for application: 73721...Fehler in findLocalRepoForPkg(pkg, repos, fatal = fatal) : 
      No package 'timetrackr' found in local repositories specified
    Ruft auf: <Anonymous> ... getPackageRecordsLocalReposImpl -> findLocalRepoForPkg
    Ausf�hrung angehalten

Reading the [getting started manual](http://shiny.rstudio.com/articles/shinyapps.html) initially gave me the impression that package dependencies are automatically transferred/installed on [shinyapps.io](http://www.shinyapps.io/)

> Package dependencies
>
> When you deploy your application, the rsconnect package attempts to detect the packages that your application uses. rsconnect sends this list of packages and their dependencies along with your application to the shinyapps.io service. Then shinyapps.io builds and installs the packages into the R library for your application. The first time you deploy your application, it may take some time to build these packages (depending on how many packages are used). However, you will not wait for these packages to build during future deployments (unless you upgrade or downgrade a package).

After reading the error message and thinking about, I rather suspect that my package must live in a publicly accessible repository. So I put it in my [`drat`](https://github.com/rappster/drat) repository and added the repository URL to `options("repos")`, but I'm still seeing the error.

Did I do anything wrong?

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
  [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] digest_0.6.8         RSQLite_1.0.0        DBI_0.3.1            DT_0.1.40           
[5] shinydashboard_0.5.1 shiny_0.12.2         drat_0.1.0           timetrackr_0.1      

loaded via a namespace (and not attached):
  [1] Rcpp_0.12.1       roxygen2_5.0.0    mime_0.4          R6_2.1.1         
[5] jsonlite_0.9.19   xtable_1.7-4      git2r_0.11.0      magrittr_1.5     
[9] stringi_1.0-1     devtools_1.9.1    tools_3.2.2       stringr_1.0.0    
[13] htmlwidgets_0.5   yaml_2.1.13       rsconnect_0.4.1.7 httpuv_1.3.3     
[17] memoise_0.2.1     htmltools_0.2.6  
```

**Comment by kippandrew** [comment]
If you're trying to install  package that exists on GitHub, the easiest way is to use `devtools::install_github()` to install the package locally. Using `install_github` allows the dependency to be automatically be picked up and installed when you run `deployApp()`. This method is best because it works for public or private repositories (provided you've enabled private repository access on your shinyapps.io account).

If you still want to use a DRAT repository (or other custom CRAN like repository), you need to use `install.packages()` to install the package but you also need to be sure use the list form of `options(repos)` to set the repository URL. For example:

If my DRAT repo was called "MyRepo" I would do:

```R
options(repos = c("MyRepo"="http://packages.example.com", "CRAN"="https://cran.rstudio.org"))
install.packages("myCustomPackage")
```

This ensures we can map `MyRepo` to a proper URL when we go to fetch the package sources during build time.

You can review your application dependencies using `rsconnect::appDependencies()` to make sure they look correct.

**Comment by rappster** [comment]
Thanks for the quick reply!

Hmm... I'm afraid I still don't understand where the installing packages part needs to take place in order for `rsconnect` being able to pick it up. 

My app lives in file `app.R`, and there I only call `library(<pkg>`), but there are no explicit `install.packages(<pkg>)` statements. Would I put them there, or in some other file below my app directory, say `dependencies.R`?

I did, of course, made sure that all packages are installed (I tried every option there is for installation) before running the app (otherwise it would also not run locally).

**Comment by kippandrew** [comment]
I think you're over thinking this. Perhaps it will help if I explain: 

There are two pieces to the dependency resolution with shinyapps.io: First, dependencies are enumerated by scanning application files for packages used (by looking for `library()`, `require()`, etc). Once a recursive list of package dependencies is generated, we attempt to determine the origin of each package (was it from CRAN, GitHub, etc). Determining the origin of a package depends on how the package was installed locally to your computer. In some cases packages have to be installed in a specific way for us to be able reliably detect their origin.

All this means is that you just need to have your packages installed using one of the methods I listed above, and they should be properly detected. You should not have any calls to `install.package` in your source code.

**Comment by rappster** [comment]
Alright, I think I got you now. The way you described it above was in fact how I presumed things were working. And I think I also did find what threw me off: after trying `install.packages(<pkg>)` or `devtools::install_github(<pkg>)`, I didn't immediatley run `rsconnect::deployApp()`, but might have updated run `CTRL + SHFT + B` in RStudio (which re-installs my package "the wrong" way for `rsconnect`)

Works fine now, thanks!!

**Comment by kippandrew** [comment]
Glad you got it working.

Also I'd like to invite you to join the [shinyapps-users](https://groups.google.com/forum/#!forum/shinyapps-users) discussion group. It's a great place for these types of questions. The GH issue tracker is only occasionally browsed.

**Comment by rappster** [comment]
Great, thanks for the pointer

**Comment by tenshis** [comment]
> (provided you've enabled private repository access on your shinyapps.io account).

This was the missing piece of the puzzle. Thanks!

**Comment by jcubic** [comment]
Nothing works I'm not able to deploy the app even that I have previews version. There is warning but this should not be related I have message:

```
Unhandled Exception: Child Task 729520470 failed: Error building image: Error fetching ggtips (0.3.2) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: ggtips (0.3.2)
Package 'ggtips 0.3.2' was installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores
```

I've tried opens and installing from github nothing works it try to install from CRAN.

**Comment by vishakha-gautam11041997** [comment]
Hi, I'm trying to deploy dropClust package in the shiny server but it keeps giving me an error
```
Error: Unhandled Exception: Child Task 905911468 failed: Error building image: Error building dropClust (2.1.0). Build exited with non-zero status: 1
Execution halted
```
I have installed this package from the command :
```
library(devtools)
install_github("debsin/dropClust", dependencies = T)
```
Can anyone help me figure how should I solve this problem?
