### ISSUE TITLE
bioconductor repository urls are different now

### ISSUE THREAD

**Issue by samperman** [rstudio/rsconnect#880]
Using the latest `rsconnect` from github main, i can install a BioConductor package like this:
```
install.packages("BiocManager")
BiocManager::install("airpart")
```

Then any resulting manifest that rsconnect creates will include a package like this:
```
    "airpart": {
      "Package": "airpart",
      "Version": "1.8.0",
      "Source": "Bioconductor",
      "Repository": "https://bioconductor.org/packages/3.17/bioc",
      ... snipped ...
    },
```

If i use the latest `rsconnect` from CRAN, then I install Bioconductor packages like this:
```
install.packages("BiocManager")
BiocManager::install("airpart")
options(repos=BiocManager::repositories())
```

And the resulting manifest looks like so:
```
    "airpart": {
      "Package": "airpart",
      "Version": "1.8.0",
      "Source": "Bioconductor",
      "Repository": "https://bioconductor.org/packages/3.17/bioc/src/contrib",
      ... snipped ...
    },
```

Note that with the older version of `rsconnect` the "Repository" url ends with `src/contrib`

**Comment by aronatkins** [comment]
@hadley - it feels as if the bioc URLs without the `src/contrib` is correct, but that is not the behavior of old rsconnect. 

We blindly strip when using packrat today:

https://github.com/rstudio/rsconnect/blob/f3725d77260f412b4be0a1228486b63a5d8d5656/R/bundlePackagePackrat.R#L97-L108

We get similar behavior when using renv.

The related code in released rsconnect:

https://github.com/rstudio/rsconnect/blob/9ce427edf03b6d243a4074264dbc950242b0a295/R/bundle.R#L1048-L1112

Should we NEWS this change? shinyapps.io and posit.cloud need to change, as they expect src/contrib today.

**Comment by aronatkins** [comment]
The shinyapps.io manifest processing is being updated to handle bioc URLs with/without `src/contrib`.

**Comment by hadley** [comment]
Yeah, I think we should just document this.

**Comment by hadley** [comment]
That change was introduced in #781 ([here](https://github.com/rstudio/rsconnect/pull/781/commits/df2f5d7b1c67b54bde055947a7713906cd05edf4#r1140211526) in particular). It replaced the previous using `grepl()` which only affected CRAN repositories.

I'm happy to document this, but I'm not sure where — this only affects the manifest which is only used by us, and it sounds like the right people already know about it.

**Comment by aronatkins** [comment]
Fair enough -- leaving this as-is. We've got this issue to record the existence of this change, and that's enough for now.
