### ISSUE TITLE
manifest schema is different if using packrat

### ISSUE THREAD

**Issue by samperman** [rstudio/rsconnect#881]
If I enable packrat:
```
options(rsconnect.packrat = TRUE)
```

And generate a manifest for an R Markdown doc:
```
rsconnect::writeManifest(appFiles=c("mydoc.Rmd"))
```

The manifest it generates has a different schema than if I do not enable packrat. In particular, the `description` of each package is an array rather than an object.

### With packrat:
```
  "packages": {
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "CRAN",
      "Repository": "http://rspm/default/__linux__/focal/latest",
      "description": ["Package: R6", ... etc ]
```

### Without packrate:
```
  "packages": {
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "CRAN",
      "Repository": "http://rspm/default/latest",
      "description": {
        "Package": "R6",
```

**Comment by aronatkins** [comment]
The additional fields beneath the package (`Package=R6` and `Version=2.5.1`) are a change from the CRAN release but are not causing problems with either Connect or shinyapps/posit.cloud.

The structure of the `description` subdocument appears to be causing the trouble.

**Comment by hadley** [comment]
Yeah, that should be an easy fix. I'll try and take a look later today/this week.

**Comment by aronatkins** [comment]
Previously, we used `packageDescription()`:

https://github.com/rstudio/rsconnect/blob/9ce427edf03b6d243a4074264dbc950242b0a295/R/bundle.R#L680-L692

Now, we read the description file:

https://github.com/rstudio/rsconnect/blob/84b140cb4e44c191e30d755886b58ef4439a31e6/R/bundlePackagePackrat.R#L29-L31

**Comment by aronatkins** [comment]
The `description` is added differently when using renv:

https://github.com/rstudio/rsconnect/blob/84b140cb4e44c191e30d755886b58ef4439a31e6/R/bundlePackageRenv.R#L34-L53

We probably need a single helper to extract the package description and ready it for the manifest.
