### ISSUE TITLE
Next release target date?

### ISSUE THREAD

**Issue by fh-kpikhart** [rstudio/rsconnect#882]
I'm unsure of the proper way to contact a package owner with this type of question. Apologies if this is not it! We're just wondering when you are targeting a next release of `rsconnect`? We are eagerly awaiting the new feature that leverages `renv` for `writeManifest()`. Thanks for any insight into a target date!

**Comment by hadley** [comment]
We are planning for a release soon. I don't think we can give an exact date, but we are actively working on it, and it shouldn't be too far away.
