### ISSUE TITLE
connectApiUser() + deployApp() does not work

### ISSUE THREAD

**Issue by DavZim** [rstudio/rsconnect#884]
Note this is a cross-post from [this SO question](https://stackoverflow.com/questions/76571006/rsconnect-cannot-publish-to-server-when-account-is-setup-programmatically-with-a) but condensed slightly.

## Issue

When I use `connectApiUser()` and `deployApp()` to connect to an RSConnect server and deploy something, I get an error, which I don't get when I use `deployApp()` after manually connecting to the RSConnect server (see Manual Connection below):

```R
# not real info ...
RSCONNECT_USER   <- "myuser"
RSCONNECT_SERVER <- "myconnect-server.com"
APIKEY           <- "mysecret (working!) API-Key"

app_id           <- "123"
app_name         <- "test-app"
app_folder       <- "app"

library(rsconnect)
packageVersion("rsconnect") # latest version as of 2023-06-28
#> [1] ‘0.8.29’


## 1 connect to the server and add user ====

removeServer(RSCONNECT_SERVER)
#> Warning... The server 'myconnect-server.com' is not currently registered

addServer(paste0("https://", RSCONNECT_SERVER), RSCONNECT_SERVER)
#> Server 'myconnect-server.com' added successfully: https://myconnect-server.com


# Note the error is expected as the user is not yet registered.
removeAccount(RSCONNECT_USER)
#> Error... account named 'myuser' does not exist

connectApiUser(
  account = RSCONNECT_USER,
  server = RSCONNECT_SERVER,
  apiKey = APIKEY
)
#> Account registered successfully: myuser



## 2 check connections ====

servers()[, c("name", "url")]
#>                    name                           url
#> 1  myconnect-server.com  https://myconnect-server.com
#> 2          shinyapps.io   https://api.shinyapps.io/v1
#> 3           posit.cloud   https://api.shinyapps.io/v1

accounts()
#>     name                server
#> 1 myuser  myconnect-server.com


## 3 Deploy to the server ====

deployApp(
  appDir = app_folder,
  appName = app_name,
  appId = app_id,
  account = RSCONNECT_USER,
  launch.browser = FALSE,
  forceUpdate = TRUE,
  server = RSCONNECT_SERVER
)
#> Preparing to deploy application...Error: HTTP 404
#> GET https://myconnect-server.com/applications/123
#> 404 page not found
```

## Manual Connection

When I connect to a connect server manually (clicking the blue share button, authenticating etc, and then publishing the content) I can then programmatically re-publish/update my app like this

```R
rsconnect::deployApp(
  appDir = app_dir,   # app/
  appName = app_name, # test-app
  appId = app_id,     # 123 as noted from the manual step; app already exists with this ID
  account = RSCONNECT_USER, # myuser
  launch.browser = FALSE,
  forceUpdate = TRUE,
  server = RSCONNECT_SERVER # the connect-server address
)
#> Preparing to deploy application...DONE
#> Uploading bundle for application: 123...DONE
#> Deploying bundle: xyz for application: 123 ...
#> ...
#> Application successfully deployed to https://myconnect-server.com/content/...
```

Note that the manual connect process uses the same server and user. Also the APIKey is valid as tested using other functions.

**Comment by aronatkins** [comment]
What version of rsconnect were you using? The `addServer()` function is a little awkward to use with the current CRAN release (0.8.29). The `addConnectServer()` function is probably what you want. The documentation doesn't make this very clear.

Could you try the following:

```r
addConnectServer(paste0("https://", RSCONNECT_SERVER), RSCONNECT_SERVER)
```

This call pattern is effectively the same as calling:

```r
addServer(paste0("https://", RSCONNECT_SERVER, "/__api__"), RSCONNECT_SERVER)
```

The `addConnectServer()` function makes sure that the stored Connect server URL points to the base API path rather than the server root. This requirement is not clearly explained in the documentation.

The current GitHub development version of rsconnect removes this distinction between the two functions. Both `addServer()` and `addConnectServer()` adjust the server URL and become functionally equivalent. We are deprecating `addConnectServer()` with the next release.

**Comment by DavZim** [comment]
Perfect, that solves it for me!
