### ISSUE TITLE
deployDoc and deploySite do not include the quarto version

### ISSUE THREAD

**Issue by samperman** [rstudio/rsconnect#885]
Note, this testing was done when deploying to Posit Cloud

If I run `rsconnect::deployDoc` or `rsconnect::deploySite`, the resulting manifest does not include the quarto version used. However, if I use `rsconnect::writeManifest` the resulting manifest does include the quarto version.

For cloud to do the right thing, it will need to know the version of quarto.

**Comment by hadley** [comment]
I think this is possibly a "bug" in `writeManifest()` because it doesn't set `isCloudServer` correctly:  https://github.com/rstudio/rsconnect/blob/description-manifest/R/bundle.R#L201-L203

**Comment by aronatkins** [comment]
Cloud had never needed the Quarto version before; this feels like a new requirement. That said, removing the `isCloudServer` checks the manifest-creation workflow means that the manifest is agnostic to the deployment target.

@samperman - can posit.cloud and shinyapps.io both cope with the existence of a quarto sub-document in the manifest.json?

**Comment by samperman** [comment]
good question. its likely that they do not support it in all cases right now, but if it makes things consistent, i can make sure we add support so things work if its there or not.

**Comment by samperman** [comment]
sounds good. i'll update this ticket once that support is in place. thanks!
