### ISSUE TITLE
libsasl2-dev needed on shinyapps.io to intall the mongolite package

### ISSUE THREAD

**Issue by DimitriF** [rstudio/rsconnect#89]
Hello,
After discussion [here](https://github.com/jeroenooms/mongolite/issues/25#issuecomment-168539160), it seems that ```libsasl2-dev ``` is missing on the shinyapps.io server to install the package ```mongolite```.
Is it possible to fix it?
Thanks in advance.
Dimitri

**Comment by jjallaire** [comment]
@CBarraford @kippandrew Not sure if you are watching here, FYI we may need libsasl2-dev on the shinyapps.io image.

**Comment by kippandrew** [comment]
libsasl2-dev was added a few weeks back.
