### ISSUE TITLE
posit.cloud + shinyapps publishing both list as api.shinyapps.io

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#905]
1. Publish a Shiny application to posit.cloud.
2. The IDE drop-down reports that content as api.shinyapps.io.
3. Publish that same application to shinyapps.io.
4. The IDE drop-down reports a second content item using api.shinyapps.io.

<img width="201" alt="image" src="https://github.com/rstudio/rsconnect/assets/362187/0812f70c-3ef7-4361-8c69-5b24f955cefd">

The publish dialog correctly shows the destination server. The drop-down is wrong; it gives no indication of the destination.

<img width="280" alt="image" src="https://github.com/rstudio/rsconnect/assets/362187/5b5d2417-d138-4978-b843-4888a4c1989c">

<img width="274" alt="image" src="https://github.com/rstudio/rsconnect/assets/362187/c81f0c87-a389-4254-9e80-c8cb91233c11">

**Comment by hadley** [comment]
What does `accounts()` and `servers()` return for you? Do we know how the IDE is generating this label?

**Comment by aronatkins** [comment]
Note: This appears to be an issue with the CRAN release of rsconnect as well as the development version, likely rooted in the fact that both shinyapps.io and posit.cloud use the same API URL.
