### ISSUE TITLE
rPubs upload size limited

### ISSUE THREAD

**Issue by englianhu** [rstudio/rsconnect#91]
https://github.com/rstudio/markdown/issues/79#issue-134818028

Any efficient solution?
https://support.rstudio.com/hc/en-us/community/posts/201223973-Rpubs-Upload-error-500

**Comment by jmcphers** [comment]
Sorry, those links don't describe an upload problem so we can't help much here. If you're still having trouble, we suggest posting in our forum:

https://community.rstudio.com/
