### ISSUE TITLE
incorrect "current" connect API call

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#92]
https://github.com/rstudio/rsconnect/blame/241966709451c599b57b647272490bdc9db8d4d5/R/connect.R#L62

The call `/users/current/` should be `/users/current`

**Comment by jjallaire** [comment]
We should get this fixed right away so the fix gets into the RStudio IDE
public release. Can you give us a PR for the fix and confirm it works
against both Connect and (if applicable) shinyapps.io?

**Comment by aronatkins** [comment]
While `/users/current` is our canonical URL, I've just verified that we also accept `/users/current/` (like shinyapps). I wrongly thought the trailing slash was causing a problem while tracking down another issue.

Closing this as invalid.

**Comment by jjallaire** [comment]
Okay, great, thanks!
