### ISSUE TITLE
Deployments with `renv.lock` do not preserve `renv.lock` in content bundle

### ISSUE THREAD

**Issue by kmasiello** [rstudio/rsconnect#926]
Push button deployment of simple shiny app with `renv.lock` included succeeds with renv v 1.0.0.9000 and rsconnect v 1.0.1, however the bundle downloaded from the Source Versions in Connect only has app.R and manifest.json in it. The lock file is not preserved.

**Comment by aronatkins** [comment]
Confirmed. A simple Shiny application within an renv project creates a bundle that contains the `app.R` and a `manifest.json`, but not the source `renv.lock`. We use the `renv.lock` during bundling, but it is discarded along the way.

**Comment by aronatkins** [comment]
Removed by https://github.com/rstudio/rsconnect/blob/a5db8323584ecc682332d8b59d172827a253a06e/R/bundlePackage.R#L42-L43

We can probably preserve the `renv.lock` file but remove the `renv` directory.
