### ISSUE TITLE
rsconnect.packrat does not apply to push-button deployment

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#935]
From a project that does not use renv (a very simple Shiny application will suffice):

```r
options(rsconnect.packrat = TRUE)
```

Deploy the project using push-button deployment. The "Deploy" pane will show:

```
ℹ Capturing R dependencies with renv
```

Deploying the same project using the console:

```r
reconnect::deployApp()
```

we see the output:

```
ℹ Capturing R dependencies with packrat
```

It appears that not all R options make their way to the deploy R session.

**Comment by aronatkins** [comment]
@kevinushey What's our best option to have a setting from the R console apply in the R deployment session? Is an environment variable more likely to work than an R option? Are only certain options / environment variables propagated?

**Comment by kevinushey** [comment]
Environment variables would be the most reliable, since those should be propagated automatically -- AFAIK we don't try to propagate any specific options (except maybe repos).

**Comment by tyner** [comment]
Note: `?rsconnect::appDependencies` metions `options(rsconnect.packrat = TRUE)` but there is no mention of the environment variable approach.
