### ISSUE TITLE
allow app-mode override

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rsconnect#948]
Let the caller override the inferred type of content.

Separated from #942.

**Comment by dragonstyle** [comment]
Thanks for opening this. 

I think this fix is essential as this provides a way for a caller to control the type of content without relying on inference (which can't anticipate all possible deployment scenarios that callers could create). 

Quarto Manuscript publishing to connect is broken in RStudio until this issue, or some other workaround is discovered, though @Hadley and I reviewed the issues and concluded this was likely to be the best fix.
