### ISSUE TITLE
Rsconnect package is out of date

### ISSUE THREAD

**Issue by ntyndall** [rstudio/rsconnect#970]
Hi there, 

Firstly, thanks for all the hard work on this repo! I have a bunch of dashboards that publish to shinyapps.io that are all heavily reliant on a particular version of renv (0.13.2), and I am using rsconnect (0.8.28) at the moment, but all of a sudden all my dashboards have failed to refresh due to a 426 error code

![image](https://github.com/rstudio/rsconnect/assets/25510323/1fe9ef7c-cf19-4ad0-9150-68e863f08c5a)

Do I really have to start bumping versions across my entire suite of dashboards/reports to make things work with renv 1.0.2?

Thanks!

**Comment by aronatkins** [comment]
Unfortunately, shinyapps.io and posit.cloud now require newer versions of rsconnect. By association, that also means you will need a newer version of renv.

The announcement of this change:
https://community.rstudio.com/t/notice-posit-cloud-shinyapps-io-dropping-support-for-rsconnect-1-0-1/172078

I'm going to close this issue, but please file issues against rsconnect and/or renv if you have problems updating your projects.
