### ISSUE TITLE
My .env file is not visible when deploying app on shiny server

### ISSUE THREAD

**Issue by tatjana-lebesgue** [rstudio/rsconnect#972]
I could not deploy my app on shiny server:
 - please update to the latest available on CRAN
 so I updated rsconnect package and now my .env file is not visible: It is no longer among the files I can select

**Comment by aronatkins** [comment]
Could you tell us more about your project and how you are attempting to deploy?

I just tried the following steps and the `.env` file was selected when deploying:

```r
# create a new project
usethis::create_project("~/Desktop/using-env")
# within this project, create a skeleton shiny app
# and an .env file.
writeLines(c(
        "shinyApp(ui = fluidPage('having an environment.'), server = function(input, output){})"
    ), "app.R")
writeLines(c(
        "# the .env file"
    ), ".env")
```

I then used the "publish" icon:

<img width="314" alt="image" src="https://github.com/rstudio/rsconnect/assets/362187/3fbe1961-3f8c-4b5d-b17d-06499dc15fcb">

**Comment by tatjana-lebesgue** [comment]
I am using same way to deploy app on shiny server, selecting files from rstudio and clicking on publish icon:
<img width="1216" alt="Screenshot 2023-08-22 at 20 06 28" src="https://github.com/rstudio/rsconnect/assets/92876745/0776cd62-38e4-4c4c-a982-67017e9adc40">

My ui is dashboardPage with a lot of elements I dont dont which details are important. But I know that hen I try to deploy usinf rsconnect version 0.8.29 I can see my .env file (but cant deploy)

**Comment by aronatkins** [comment]
@tatjana-lebesgue I have somehow managed to get one of my projects into the same state. I'm continuing to dig. I'm not sure the cause nor a workaround at this point.

**Comment by aronatkins** [comment]
With rsconnect-0.8.29:

```
> rsconnect::listBundleFiles(getwd())$contents
[1] ".env"  "app.R"
```

With rsconnect-1.0.2:

```
> rsconnect::listBundleFiles(getwd())$contents
[1] "app.R"
```

**Comment by aronatkins** [comment]
The `.env` directory is now regarded as a well-known path for Python virtual environments:

https://github.com/rstudio/rsconnect/blob/0d052a0f6164e5f2a95a0e9e94c85a804ecf6672/R/bundleFiles.R#L182-L184

This was done in https://github.com/rstudio/rsconnect/pull/700

@tatjana-lebesgue - is it possible to rename that `.env` file, perhaps to `.Renviron`? Are you using other tools which expect the `.env` filename?

I'm continuing to see if we can allow `.env` files again, but in the mean time, using some other name should let you deploy again.

**Comment by tatjana-lebesgue** [comment]
I did that, and now it's working! 
I was using the 'dotenv' package and then was expecting the '.env' filename (regards consistency in other projects). 

Thank you for the quick response and help @aronatkins :)

**Comment by aronatkins** [comment]
@tatjana-lebesgue The development version of rsconnect should let you use `.env` files once again.

```r
remotes::install_github("rstudio/rsconnect")
```

Please let us know if you encounter any other difficulties.
