### ISSUE TITLE
Ensure manifest data is encoded as UTF-8

### ISSUE THREAD

**Issue by mslynch** [rstudio/rsconnect#974]
shinyapps.io and Posit Cloud presume `manifest.json` to be valid JSON encoded in UTF-8. However, some of the data in this file comes from `DESCRIPTION` files, which may not be encoded in UTF-8. If we see that `DESCRIPTION`'s `Encoding` field is not UTF-8, we should attempt to convert it.

**Comment by hadley** [comment]
I think it's very rare for the `Encoding` to be non-UTF-8.

**Comment by mslynch** [comment]
> I think it's very rare for the `Encoding` to be non-UTF-8.

That's my impression as well – and it should be ever rarer still for `DESCRIPTION` to also contain characters that are only valid in latin-1. But we had a customer try to use a package like this (`relaimpo`).

**Comment by hadley** [comment]
And particularly annoying in that case is that the only field that is non-ASCII is `Packaged`, which is definitely not very important.

**Comment by tyatposit** [comment]
validated.  worked fine for me install/call `relaimpo` and deploy to both cloud and shinyapps which sounds like was a package with a DESCRIPTION encoded as UTF-8.

- created new shinyapp
- `install.packages('relaimpo')`
- called `library(relaimpo)`
- deployed the app to both shinyapps and cloud
- app built and loaded up without issue
