### ISSUE TITLE
Republishing to RPubs, Error: HTTP/2 stream 1 was reset

### ISSUE THREAD

**Issue by zhengxiaoUVic** [rstudio/rsconnect#976]
AN ERROR OCCURS when I knit an Rmd into HTML and republish (update existing) it to RPubs. There is no problem with the initial upload or republishing long ago Rmd.

`Error in curl::curl_fetch_memory(url, handle = handle) :  HTTP/2 stream 1 was reset Calls: <Anonymous> -> http -> <Anonymous> Execution halted`

I have tried the simplest HTML document. So, the error is not due to the file size.

R version 4.3.1
RStudio version 2023.09.0+463 
macOS Ventura 13.5.2
MacBook Air, M2

I fixed the republishing issue by downgrading the "rsconnect" R package.

```
remove.packages("rsconnect") #Remove Installed Packages
remotes::install_version("rsconnect", version = "0.8.29") #Installing a Specific Version of a Package
```

Any higher versions of rsconnect (e.g., 1.0.0, 1.0.1, 1.0.2, 1.1.0 and latest 1.1.1) will cause the error regarding "HTTP/2 stream 1 was reset". After downgrading "rsconnect", RMD files with failed republishing will still not be republished. You need to upload a fresh one.

**Comment by aronatkins** [comment]
Additional changes to `deploymentRecord` occurred in https://github.com/rstudio/rsconnect/pull/702...

**Comment by hadley** [comment]
It's probably my fault 😭

**Comment by aronatkins** [comment]
Argument removal (when and last-sync) in https://github.com/rstudio/rsconnect/commit/8f19a2a6b2e7d857f90f1246d994420eddd686fb

**Comment by aronatkins** [comment]
> It's probably ~my~ our fault 😭

The collective! 

<img width="325" alt="image" src="https://github.com/rstudio/rsconnect/assets/362187/3ca4cb7c-1120-4c06-93b5-2f1f9944d8fc">

**Comment by JBell39** [comment]
I don't know what I am doing wrong. Here is my updated dcf:

name: Document
title:
username:
account: rpubs
server: rpubs.com
hostUrl: rpubs.com
appId: https://api.rpubs.com/api/v1/document/1099849/f24f13c92bd4430a8e6d83d25154f1fc
bundleId: http://rpubs.com/publish/claim/1099849/37d672b76e4748539e6d5983395371e5
url:  https://rpubs.com/bellj39/1099849
version: 1
