### ISSUE TITLE
When app is too large, deployment fails with unhelpful error

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rsconnect#98]
Error in RCurl::curlPerform(url = url, .opts = options, customrequest = method, : 
long vectors not supported yet: ../include/Rinlinedfuns.h:137 
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous> 
Execution halted

Proposal: Catch error condition and surface user-actionable message during deploy process.  There is currently code in shinyapps.io that surfaces an “application bundle too large” message, but this RCurl error is hitting first.

**Comment by jmcphers** [comment]
To further complicate matters there's an RCurl limit (demonstrated here) which is lower than the actual bundle size limit; if the application is too big for RCurl but not too big for shinyapps.io, we should suggest setting `options(rsconnect.http = "curl")` as the transport.

**Comment by JoseLastra** [comment]
i'm having the same problem. In which part of the code you should put that option line???

**Comment by rahulkravi** [comment]
Hi,
Did you figure out the solution to the issue.
I am also facing the very same error.
Even changing to options(rsconnect.http = "curl") does not work as the error code still refers to Rcurl.
Not sure why!

**Comment by jmcphers** [comment]
The new version of rsconnect (0.8.15, released in July) has a new curl-based transport that should accept larger bundles gracefully. Let us know if you still see the problem there!

**Comment by greenjune-ship-it** [comment]
Hi Jonathan!
@jmcphers 

I have faced the same issue on rsconnect v.0.8.16.
However, ```options(rsconnect.http = "curl")``` worked for me!
