### ISSUE TITLE
showProperties() continue giving a ! Couldn't find any deployments matching supplied criteria

### ISSUE THREAD

**Issue by AlejandroAyllon** [rstudio/rsconnect#985]
I opened an issue with this problem here: https://github.com/rstudio/rsconnect/issues/980. Thanks @aronatkins for investigate and fix an issue related with `showProperties()` here: https://github.com/rstudio/rsconnect/pull/984. I have installed the development version of `rsconnect` and I tried to use this function again, but unfortunately the same problem continue. ¿Someone with the same problem?, ¿any idea about the reason or way to fix it?
Thanks in advance.

**Comment by aronatkins** [comment]
Could you see what `rsconnect::deployments()` tells you?
What directory are you using when calling `rsconnect::showProperties()`?

Both of these functions need to be called from the directory containing your Shiny application (assuming you are using Shiny).

I can recreate the "Couldn't find any deployments matching supplied criteria." error when calling `rsconnect::showProperties()` from a directory containing a Shiny application that has not been deployed. When the directory contains a previously deployed Shiny application, `rsconnect::showProperties()` works without issue.

**Comment by AlejandroAyllon** [comment]
@aronatkins , I get a empty `data.frame` when I run `rsconnect::deployments()` (12 columns but 0 rows). I think the problem is the same as it´s explained in this issue https://github.com/rstudio/rsconnect/issues/980, I deploy apps in a different machine that the one I use to develop. The last version try to get them of `./rsconnect/shinyapps.io/prototypenvp/`. As @alvarosantamariagomez said: "This was not a problem before the last version change. Before the change, only the account (token) and the app details was enough to run `showLogs()`.". In addition, another functions like `rsconnect::applications()` can get every app than has been deployed in my Shinyapps account, but not with `showLogs()` or `showProperties()`.

**Comment by AlejandroAyllon** [comment]
Hi @aronatkins. I just tested and the problem has been resolved with this version. I will be aware when the new version is deployed with this fix.
Thanks a lot! 👍
