### ISSUE TITLE
Should catch bad path problem at deploy time

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rsconnect#99]
If you use "./data/data.csv" instead of "data/data.csv", for example, as a path to accessing files, the deploy succeeds but the app fails at runtime:

Error in value[[3L]](cond) : error reading from connection 
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous> 
Execution halted

**Comment by kevinushey** [comment]
Paths with a leading `./` shouldn't be an issue (it appears to be okay in this dummy app, e.g. https://beta.rstudioconnect.com/kushey/hello/).

Do we have a reproducible example?

**Comment by ajmcoqui** [comment]
I thought I did, but I don't - I'm able to use "./data/data.csv" just fine now.  There must have been something wrong elsewhere; I will try to determine what the problem actually was.
