### ISSUE TITLE
 rsconnect::deployApp fails to deploy an app with library on github (private repo) - http 401 unautorized

### ISSUE THREAD

**Issue by porfila** [rstudio/rsconnect#990]
This is a simple procedure to reproduce the problem

1/ Fork the daff package from https://github.com/edwindj/daff
on your own github environment

2/ install the package from git (devtools::install_github("xxxx/daff"))

3/ create a standard shiny app project

4/ insert library(daff) in the script
....
library(shiny)
library(daff)
...
5/ This is the error we have

Unhandled Exception: Child Task 1334338495 failed: Error building image: Error fetching daff (0.3.8) source. Error accessing GitHub repository porfila/daff. HTTP 401: Unauthorized

**Comment by porfila** [comment]
This is a simple procedure to reproduce the problem

1/ Fork the daff package from https://github.com/edwindj/daff
on your own github environment

2/ install the package from git (devtools::install_github("xxxx/daff"))

3/ create a standard shiny app project

4/ insert library(daff) in the script
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(daff)
# Define UI for application that draws a histogram
ui <- fluidPage(
....

6/ This is the error we have

Unhandled Exception: Child Task 1334338495 failed: Error building image: Error fetching daff (0.3.8) source. Error accessing GitHub repository porfila/daff. HTTP 401: Unauthorized
Exécution arrêtée

**Comment by porfila** [comment]
thank you. The github account was already linked, I unchecked / checked the private repo checkbox on shiny io , and now it is working

**Comment by aronatkins** [comment]
Marking this closed, as re-linking with GitHub resolved the problem. If you continue to have trouble, please post to the community site or file a support request.

https://community.rstudio.com/c/shiny/shinyappsio/24
